#!/usr/bin/env python3
"""Propose confirmed-chunk entries for the interior entries the port cannot emit.

The oracle translates a guest function the first time it executes it, so its
dump directory is a set of addresses that ran. 689 of them are not function
starts in the canonical Ghidra atlas, which means codegen emits none of them
and each surfaces as an unqualified indirect call the moment the guest arrives.
0x820D3710, reached by pressing START during the title screen, is one.

The oracle only says WHICH addresses to look at. AGENTS.md forbids letting it
define boundaries, so everything written into an entry here comes from the
binary and from the Ghidra-derived atlas:

  owner   the atlas function whose range contains the address
  size    from the address to its first blr/bctr inclusive, bounded by the
          owner's own end, so an entry never spills past the function Ghidra
          drew
  hash    sha256 of exactly those bytes in the extracted basefile

An address with no atlas owner is not proposed at all -- 125 of the 689 are in
that state and need a Ghidra pass, not a generated guess.

Nothing is applied. Adding these to config/confirmed-chunks.toml renumbers
every generated line, which is a campaign-level decision; see
reports/AC6_DEMO_CODEGEN_BOUNDARY_COUPLING.md before running with --emit.

usage: propose_interior_entries.py ORACLE_LIST [--emit OUT.toml] [--limit N]
"""
from __future__ import annotations

import argparse
import bisect
import hashlib
import json
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ATLAS = ROOT / "analysis/demo/ac6-demo-static-decomp-atlas-v1.json"
BASEFILE = ROOT / ".build/Default.xex.base.bin"
BASE = 0x82000000
TERMINATORS = (0x4E800020, 0x4E800420)  # blr, bctr
MAX_EXTENT = 0x200


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("oracle", type=Path)
    parser.add_argument("--atlas", type=Path, default=ATLAS)
    parser.add_argument("--basefile", type=Path, default=BASEFILE)
    parser.add_argument("--emit", type=Path)
    parser.add_argument("--limit", type=int)
    arguments = parser.parse_args()

    image = arguments.basefile.read_bytes()
    word = lambda address: struct.unpack_from(">I", image, address - BASE)[0]
    atlas = json.loads(arguments.atlas.read_text())
    starts = {int(f["entry"], 16) for f in atlas["functions"]}
    ranges = sorted((int(lo, 16), int(hi, 16), int(f["entry"], 16))
                    for f in atlas["functions"] for lo, hi in f["ranges"])
    lows = [entry[0] for entry in ranges]

    text = arguments.oracle.read_text(errors="replace")
    executed = {int(m, 16) for m in
                re.findall(r"/hirdump_title_\d+/([0-9A-Fa-f]{8})\b", text)}
    interior = sorted(a for a in executed if a not in starts)

    proposed, orphan, uncapped = [], 0, 0
    for address in interior:
        index = bisect.bisect_right(lows, address) - 1
        owner = None
        while index >= 0:
            low, high, entry = ranges[index]
            if low <= address <= high:
                owner = (low, high, entry)
                break
            index -= 1
        if owner is None:
            orphan += 1
            continue
        low, high, entry = owner
        cursor = address
        terminated = False
        while cursor <= high and cursor - address < MAX_EXTENT:
            if word(cursor) in TERMINATORS:
                terminated = True
                break
            cursor += 4
        if not terminated:
            # No blr/bctr within the owner or within MAX_EXTENT. Emitting a
            # size here would be the search limit, not the function's extent,
            # and a wrong size is worse than no entry: the build would hash
            # and compile bytes that are not the callee.
            uncapped += 1
            continue
        size = min(cursor + 4, high + 1) - address
        raw = image[address - BASE:address - BASE + size]
        proposed.append((address, size, entry, low, high,
                         hashlib.sha256(raw).hexdigest()))

    print(f"interior={len(interior)} proposed={len(proposed)} "
          f"orphan={orphan} unterminated={uncapped}")
    if arguments.emit is None:
        for address, size, entry, _, _, digest in proposed[:arguments.limit or 5]:
            print(f"  0x{address:08X} size=0x{size:X} owner=0x{entry:08X} "
                  f"sha256={digest[:16]}")
        return 0

    lines = ["# Generated by tools/propose_interior_entries.py. NOT APPLIED.",
             "# Each address was executed by the oracle and is interior to a",
             "# canonical Ghidra function; the extent and hash come from the",
             "# basefile, never from the oracle.", ""]
    for address, size, entry, low, high, digest in proposed[:arguments.limit]:
        lines += [
            "[[function]]",
            f"address = 0x{address:08X}",
            f"size = 0x{size:X}",
            'kind = "callable-inner-chunk"',
            f'evidence = "canonical-ghidra:ace-combat-6-demo/Default.xex '
            f'owner=0x{entry:08X} range 0x{low:08X}..0x{high:08X}; extent to '
            f'first blr/bctr; oracle-executed candidate"',
            f'byte_sha256 = "{digest}"',
            "",
        ]
    arguments.emit.write_text("\n".join(lines), encoding="utf-8")
    print(f"emitted={min(len(proposed), arguments.limit or len(proposed))} "
          f"path={arguments.emit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
