#include "ac6/retail_content.h"

#include <zlib.h>

#include <algorithm>
#include <array>
#include <cerrno>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <fstream>
#include <limits>
#include <numeric>
#include <optional>
#include <string_view>
#include <system_error>
#include <unistd.h>

namespace ac6 {
namespace {

constexpr std::array<std::uint8_t, 8> kIndexMagic{'A', 'C', '6', 'R', 'I', 'D', 'X', 0};
constexpr std::array<std::uint8_t, 8> kCurrentMagic{'A', 'C', '6', 'R', 'C', 'U', 'R', 0};
constexpr std::uint32_t kIndexVersion = 2;
constexpr std::uint32_t kIndexHeaderSize = 224;
constexpr std::uint32_t kIndexRecordSize = 108;
constexpr std::uint32_t kCurrentSize = 48;

// Fractional-pi words selected by the PAL mode-1 decoder, one eight-byte pad
// for each low table-index byte. This is the same deterministic mathematical
// table generated by tools/ac6_mode1_codec.py; it contains no retail payload.
constexpr std::array<std::uint64_t, 256> kMode1Pads{
    0x85a308d313198a2eull, 0x03707344a4093822ull, 0x299f31d0082efa98ull, 0xec4e6c89452821e6ull,
    0x38d01377be5466cfull, 0x34e90c6cc0ac29b7ull, 0xc97c50dd3f84d5b5ull, 0xb54709179216d5d9ull,
    0x8979fb1bd1310ba6ull, 0x98dfb5ac2ffd72dbull, 0xd01adfb7b8e1afedull, 0x6a267e96ba7c9045ull,
    0xf12c7f9924a19947ull, 0xb3916cf70801f2e2ull, 0x858efc16636920d8ull, 0x71574e69a458fea3ull,
    0xf4933d7e0d95748full, 0x728eb658718bcd58ull, 0x82154aee7b54a41dull, 0xc25a59b59c30d539ull,
    0x2af26013c5d1b023ull, 0x286085f0ca417918ull, 0xb8db38ef8e79dcb0ull, 0x603a180e6c9e0e8bull,
    0xb01e8a3ed71577c1ull, 0xbd314b2778af2fdaull, 0x55605c60e65525f3ull, 0xaa55ab9457489862ull,
    0x63e8144055ca396aull, 0x2aab10b6b4cc5c34ull, 0x1141e8cea15486afull, 0x7c72e993b3ee1411ull,
    0x636fbc2a2ba9c55dull, 0x741831f6ce5c3e16ull, 0x9b87931eafd6ba33ull, 0x6c24cf5c7a325381ull,
    0x289586773b8f4898ull, 0x6b4bb9afc4bfe81bull, 0x6628219361d809ccull, 0xfb21a991487cac60ull,
    0x5dec8032ef845d5dull, 0xe98575b1dc262302ull, 0xeb651b8823893e81ull, 0xd396acc50f6d6ff3ull,
    0x83f442392e0b4482ull, 0xa484200469c8f04aull, 0x9e1f9b5e21c66842ull, 0xf6e96c9a670c9c61ull,
    0xabd388f06a51a0d2ull, 0xd8542f68960fa728ull, 0xab5133a36eef0b6cull, 0x137a3be4ba3bf050ull,
    0x7efb2a98a1f1651dull, 0x39af017666ca593eull, 0x82430e888cee8619ull, 0x456f9fb47d84a5c3ull,
    0x3b8b5ebee06f75d8ull, 0x85c12073401a449full, 0x56c16aa64ed3aa62ull, 0x363f77061bfedf72ull,
    0x429b023d37d0d724ull, 0xd00a1248db0fead3ull, 0x49f1c09b075372c9ull, 0x80991b7b25d479d8ull,
    0xf6e8def7e3fe501aull, 0xb6794c3b976ce0bdull, 0x04c006bac1a94fb6ull, 0x409f60c45e5c9ec2ull,
    0x196a246368fb6fafull, 0x3e6c53b51339b2ebull, 0x3b52ec6f6dfc511full, 0x9b30952ccc814544ull,
    0xaf5ebd09bee3d004ull, 0xde334afd660f2807ull, 0x192e4bb3c0cba857ull, 0x45c8740fd20b5f39ull,
    0xb9d3fbdb5579c0bdull, 0x1a60320ad6a100c6ull, 0x402c7279679f25feull, 0xfb1fa3cc8ea5e9f8ull,
    0xdb3222f83c7516dfull, 0xfd616b152f501ec8ull, 0xad0552ab323db5faull, 0xfd23876053317b48ull,
    0x3e00df829e5c57bbull, 0xca6f8ca01a87562eull, 0xdf1769dbd542a8f6ull, 0x287effc3ac6732c6ull,
    0x8c4f5573695b27b0ull, 0xbbca58c8e1ffa35dull, 0xb8f011a010fa3d98ull, 0xfd2183b84afcb56cull,
    0x2dd1d35b9a53e479ull, 0xb6f84565d28e49bcull, 0x4bfb9790e1ddf2daull, 0xa4cb7e3362fb1341ull,
    0xcee4c6e8ef20cadaull, 0x36774c01d07e9efeull, 0x2bf11fb495dbda4dull, 0xae909198eaad8e71ull,
    0x6b93d5a0d08ed1d0ull, 0xafc725e08e3c5b2full, 0x8e7594b78ff6e2fbull, 0xf2122b648888b812ull,
    0x900df01c4fad5ea0ull, 0x688fc31cd1cff191ull, 0xb3a8c1ad2f2f2218ull, 0xbe0e1777ea752dfeull,
    0x8b021fa1e5a0cc0full, 0xb56f74e818acf3d6ull, 0xce89e299b4a84fe0ull, 0xfd13e0b77cc43b81ull,
    0xd2ada8d9165fa266ull, 0x8095770593cc7314ull, 0x211a1477e6ad2065ull, 0x77b5fa86c75442f5ull,
    0xfb9d35cfebcdaf0cull, 0x7b3e89a0d6411bd3ull, 0xae1e7e4900250e2dull, 0x2071b35e226800bbull,
    0x57b8e0af2464369bull, 0xf009b91e5563911dull, 0x59dfa6aa78c14389ull, 0xd95a537f207d5ba2ull,
    0x02e5b9c583260376ull, 0x6295cfa911c81968ull, 0x4e734a41b3472dcaull, 0x7b14a94a1b510052ull,
    0x9a532915d60f573full, 0xbc9bc6e42b60a476ull, 0x81e6740008ba6fb5ull, 0x571be91ff296ec6bull,
    0x2a0dd915b6636521ull, 0xe7b9f9b6ff34052eull, 0xc585566453b02d5dull, 0xa99f8fa108ba4799ull,
    0x6e85076a4b7a70e9ull, 0xb5b32944db75092eull, 0xc4192623ad6ea6b0ull, 0x49a7df7d9cee60b8ull,
    0x8fedb266ecaa8c71ull, 0x699a17ff5664526cull, 0xc2b19ee1193602a5ull, 0x75094c29a0591340ull,
    0xe4183a3e3f54989aull, 0x5b429d656b8fe4d6ull, 0x99f73fd6a1d29c07ull, 0xefe830f54d2d38e6ull,
    0xf0255dc14cdd2086ull, 0x8470eb266382e9c6ull, 0x021ecc5e09686b3full, 0x3ebaefc93c971814ull,
    0x6b6a70a1687f3584ull, 0x52a0e286b79c5305ull, 0xaa5007373e07841cull, 0x7fdeae5c8e7d44ecull,
    0x5716f2b8b03ada37ull, 0xf0500c0df01c1f04ull, 0x0200b3ffae0cf51aull, 0x3cb574b225837a58ull,
    0xdc0921bdd19113f9ull, 0x7ca92ff694324773ull, 0x22f547013ae5e581ull, 0x37c2dadcc8b57634ull,
    0x9af3dda7a9446146ull, 0x0fd0030eecc8c73eull, 0xa4751e41e238cd99ull, 0x3bea0e2f3280bba1ull,
    0x183eb3314e548b38ull, 0x4f6db9086f420d03ull, 0xf60a04bf2cb81290ull, 0x24977c795679b072ull,
    0xbcaf89afde9a771full, 0xd9930810b38bae12ull, 0xdccf3f2e5512721full, 0x2e6b7124501adde6ull,
    0x9f84cd877a584718ull, 0x7408da17bc9f9abcull, 0xe94b7d8cec7aec3aull, 0xdb851dfa63094366ull,
    0xc464c3d2ef1c1847ull, 0x3215d908dd433b37ull, 0x24c2ba1612a14d43ull, 0x2a65c45150940002ull,
    0x133ae4dd71dff89eull, 0x10314e5581ac77d6ull, 0x5f11199b043556f1ull, 0xd7a3c76b3c11183bull,
    0x5924a509f28fe6edull, 0x97f1fbfa9ebabf2cull, 0x1e153c6e86e34570ull, 0xeae96fb1860e5e0aull,
    0x5a3e2ab3771fe71cull, 0x4e3d06fa2965dcb9ull, 0x99e71d0f803e89d6ull, 0x5266c8252e4cc978ull,
    0x9c10b36ac6150ebaull, 0x94e2ea78a5fc3c53ull, 0x1e0a2df4f2f74ea7ull, 0x361d2b3d1939260full,
    0x19c279605223a708ull, 0xf71312b6ebadfe6eull, 0xeac31f66e3bc4595ull, 0xa67bc883b17f37d1ull,
    0x018cff28c332ddefull, 0xbe6c5aa565582185ull, 0x68ab9802eecea50full, 0xdb2f953b2aef7dadull,
    0x5b6e2f841521b628ull, 0x29076170ecdd4775ull, 0x619f151013cca830ull, 0xeb61bd960334fe1eull,
    0xaa0363cfb5735c90ull, 0x4c70a239d59e9e0bull, 0xcbaade14eecc86bcull, 0x60622ca79cab5cabull,
    0xb2f3846e648b1eafull, 0x19bdf0caa02369b9ull, 0x655abb5040685a32ull, 0x3c2ab4b3319ee9d5ull,
    0xc021b8f79b540b19ull, 0x875fa09995f7997eull, 0x623d7da8f837889aull, 0x97e32d7711ed935full,
    0x166812810e358829ull, 0xc7e61fd696dedfa1ull, 0x7858ba9957f584a5ull, 0x1b2272639b83c3ffull,
    0x1ac24696cdb30aebull, 0x532e30548fd948e4ull, 0x6dbc312858ebf2efull, 0x34c6ffeafe28ed61ull,
    0xee7c3c735d4a14d9ull, 0xe864b7e342105d14ull, 0x203e13e045eee2b6ull, 0xa3aaabeadb6c4f15ull,
    0xfacb4fd0c742f442ull, 0xef6abbb5654f3b1dull, 0x41cd2105d81e799eull, 0x86854dc7e44b476aull,
    0x3d816250cf62a1f2ull, 0x5b8d2646fc8883a0ull, 0xc1c7b6a37f1524c3ull, 0x69cb749247848a0bull,
    0x5692b285095bbf00ull, 0xad19489d1462b174ull, 0x23820e0058428d2aull, 0x0c55f5ea1dadf43eull,
    0x233f70613372f092ull, 0x8d937e41d65fecf1ull, 0x6c223bdb7cde3759ull, 0xcbee74604085f2a7ull,
    0xce77326ea6078084ull, 0x19f8509ee8efd855ull, 0x61d99735a969a7aaull, 0xc50c06c25a04abfcull,
};

struct TableEntry final {
  std::uint32_t index{};
  std::uint32_t group{};
  std::uint64_t offset{};
  std::uint64_t stored_size{};
  std::uint64_t expanded_size{};
  RetailArchive archive{};
  RetailStorageCodec codec{};
};

std::uint32_t read_be32(const std::uint8_t* bytes) noexcept {
  return (static_cast<std::uint32_t>(bytes[0]) << 24u) |
         (static_cast<std::uint32_t>(bytes[1]) << 16u) |
         (static_cast<std::uint32_t>(bytes[2]) << 8u) |
         static_cast<std::uint32_t>(bytes[3]);
}

void append_u32(std::vector<std::uint8_t>& output, std::uint32_t value) {
  output.push_back(static_cast<std::uint8_t>(value >> 24u));
  output.push_back(static_cast<std::uint8_t>(value >> 16u));
  output.push_back(static_cast<std::uint8_t>(value >> 8u));
  output.push_back(static_cast<std::uint8_t>(value));
}

void append_u64(std::vector<std::uint8_t>& output, std::uint64_t value) {
  append_u32(output, static_cast<std::uint32_t>(value >> 32u));
  append_u32(output, static_cast<std::uint32_t>(value));
}

void append_digest(std::vector<std::uint8_t>& output, const Sha256Digest& digest) {
  output.insert(output.end(), digest.begin(), digest.end());
}

bool add_within(std::uint64_t left, std::uint64_t right,
                std::uint64_t limit) noexcept {
  return left <= limit && right <= limit - left;
}

bool read_file(const std::filesystem::path& path, std::uint64_t maximum_size,
               std::vector<std::uint8_t>& bytes) {
  std::error_code error;
  const std::uintmax_t size = std::filesystem::file_size(path, error);
  if (error || size > maximum_size || size > std::numeric_limits<std::size_t>::max()) {
    return false;
  }
  std::ifstream input(path, std::ios::binary);
  if (!input) return false;
  bytes.resize(static_cast<std::size_t>(size));
  if (!bytes.empty()) {
    input.read(reinterpret_cast<char*>(bytes.data()),
               static_cast<std::streamsize>(bytes.size()));
  }
  return input && input.peek() == std::ifstream::traits_type::eof();
}

bool read_range(const std::filesystem::path& path, std::uint64_t offset,
                std::uint64_t size, std::vector<std::uint8_t>& bytes) {
  if (size > std::numeric_limits<std::size_t>::max() ||
      offset > static_cast<std::uint64_t>(std::numeric_limits<std::streamoff>::max())) {
    return false;
  }
  std::ifstream input(path, std::ios::binary);
  if (!input) return false;
  input.seekg(static_cast<std::streamoff>(offset));
  if (!input) return false;
  bytes.resize(static_cast<std::size_t>(size));
  if (!bytes.empty()) {
    input.read(reinterpret_cast<char*>(bytes.data()),
               static_cast<std::streamsize>(bytes.size()));
  }
  return input && static_cast<std::size_t>(input.gcount()) == bytes.size();
}

bool qualify_file(const std::filesystem::path& path, std::uint64_t expected_size,
                  const Sha256Digest& expected_digest, Sha256Digest& actual) {
  std::error_code error;
  if (!std::filesystem::is_regular_file(path, error) || error ||
      std::filesystem::file_size(path, error) != expected_size || error) {
    return false;
  }
  return sha256_file(path, actual, expected_size) && actual == expected_digest;
}

RetailContentError qualify_source_files(const std::filesystem::path& source,
                                        const RetailIdentityPolicy& policy,
                                        std::string& detail) {
  Sha256Digest actual{};
  const auto files = std::array{
      std::pair{source / "default.xex",
                std::pair{policy.identity.xex_size, policy.identity.xex_sha256}},
      std::pair{source / "DATA.TBL",
                std::pair{policy.identity.data_table_size,
                          policy.identity.data_table_sha256}},
      std::pair{source / "DATA00.PAC",
                std::pair{policy.identity.data00_size, policy.identity.data00_sha256}},
      std::pair{source / "DATA01.PAC",
                std::pair{policy.identity.data01_size, policy.identity.data01_sha256}},
  };
  for (const auto& qualified : files) {
    std::error_code error;
    if (!std::filesystem::is_regular_file(qualified.first, error) || error) {
      detail = "missing retail source file: " + qualified.first.filename().string();
      return RetailContentError::SourceMissing;
    }
    if (!qualify_file(qualified.first, qualified.second.first,
                      qualified.second.second, actual)) {
      detail = "retail identity mismatch: " + qualified.first.filename().string();
      return RetailContentError::SourceIdentityMismatch;
    }
  }
  if (policy.media.required) {
    for (const auto& asset : policy.media.assets) {
      if (asset.filename == nullptr || asset.size == 0 || asset.sha256 == Sha256Digest{}) {
        detail = "media policy contains an unresolved identity";
        return RetailContentError::SourceIdentityMismatch;
      }
      const auto path = source / asset.filename;
      if (!qualify_file(path, asset.size, asset.sha256, actual)) {
        detail = "retail media identity mismatch: " + path.filename().string();
        return RetailContentError::SourceIdentityMismatch;
      }
    }
  }
  return RetailContentError::None;
}

std::filesystem::path archive_path(const std::filesystem::path& source,
                                   RetailArchive archive) {
  return source / (archive == RetailArchive::Data00 ? "DATA00.PAC" : "DATA01.PAC");
}

std::filesystem::path blob_path(const std::filesystem::path& cache,
                                const Sha256Digest& digest) {
  const std::string hex = sha256_hex(digest);
  return cache / "blobs" / "sha256" / hex.substr(0, 2) / hex;
}

bool parse_table(std::span<const std::uint8_t> bytes,
                 const RetailIdentityPolicy& policy,
                 const RetailImportLimits& limits,
                 std::vector<TableEntry>& entries,
                 std::string& detail) {
  if (bytes.size() < 8) {
    detail = "DATA.TBL is smaller than its header";
    return false;
  }
  const std::uint32_t count = read_be32(bytes.data());
  const std::uint32_t packs = read_be32(bytes.data() + 4);
  if (count != policy.data_table_entries || packs != policy.pack_count ||
      count == 0 || count > limits.maximum_table_entries ||
      bytes.size() != 8u + static_cast<std::uint64_t>(count) * 16u) {
    detail = "DATA.TBL shape or qualified counts mismatch";
    return false;
  }
  entries.clear();
  entries.reserve(count);
  for (std::uint32_t index = 0; index < count; ++index) {
    const std::uint8_t* row = bytes.data() + 8u + index * 16u;
    TableEntry entry;
    entry.index = index;
    entry.group = read_be32(row);
    entry.offset = read_be32(row + 4);
    entry.stored_size = read_be32(row + 8);
    entry.expanded_size = read_be32(row + 12);
    entry.archive = (entry.group & 0x01000000u) != 0
                        ? RetailArchive::Data01
                        : RetailArchive::Data00;
    entry.codec = (entry.group & 0x00020000u) != 0
                      ? RetailStorageCodec::Mode1PiXorRaw
                      : RetailStorageCodec::Mode1PiXorRawDeflate;
    const std::uint64_t archive_size =
        entry.archive == RetailArchive::Data00
            ? policy.identity.data00_size
            : policy.identity.data01_size;
    if (entry.stored_size == 0 || entry.expanded_size == 0 ||
        !add_within(entry.offset, entry.stored_size, archive_size)) {
      detail = "DATA.TBL contains an invalid PAC range at entry " +
               std::to_string(index);
      return false;
    }
    if (std::any_of(entries.begin(), entries.end(),
                    [&entry](const TableEntry& previous) {
                      return previous.archive == entry.archive &&
                             previous.offset == entry.offset &&
                             previous.stored_size == entry.stored_size;
                    })) {
      detail = "DATA.TBL contains a duplicate PAC range at entry " +
               std::to_string(index);
      return false;
    }
    entries.push_back(entry);
  }
  return true;
}

bool select_entries(const std::vector<TableEntry>& table,
                    std::span<const std::uint32_t> requested,
                    const RetailImportLimits& limits,
                    std::vector<TableEntry>& selected,
                    std::string& detail) {
  if (requested.empty()) {
    detail = "no DATA.TBL entries requested";
    return false;
  }
  selected.clear();
  std::uint64_t total = 0;
  for (const std::uint32_t index : requested) {
    if (index >= table.size()) {
      detail = "DATA.TBL entry out of range: " + std::to_string(index);
      return false;
    }
    if (std::any_of(selected.begin(), selected.end(),
                    [index](const TableEntry& entry) { return entry.index == index; })) {
      detail = "duplicate DATA.TBL entry: " + std::to_string(index);
      return false;
    }
    const TableEntry& entry = table[index];
    if (entry.stored_size > limits.maximum_stored_size ||
        entry.expanded_size > limits.maximum_expanded_size ||
        !add_within(total, entry.expanded_size,
                    limits.maximum_total_expanded_size)) {
      detail = "DATA.TBL entry exceeds import limits: " + std::to_string(index);
      return false;
    }
    total += entry.expanded_size;
    selected.push_back(entry);
  }
  std::sort(selected.begin(), selected.end(),
            [](const TableEntry& left, const TableEntry& right) {
              return left.index < right.index;
            });
  return true;
}

bool inflate_raw(std::span<const std::uint8_t> input, std::size_t output_size,
                 std::vector<std::uint8_t>& output) {
  if (input.size() > std::numeric_limits<uInt>::max() ||
      output_size > std::numeric_limits<uInt>::max()) {
    return false;
  }
  output.assign(output_size, 0);
  z_stream stream{};
  stream.next_in = const_cast<Bytef*>(input.data());
  stream.avail_in = static_cast<uInt>(input.size());
  stream.next_out = output.data();
  stream.avail_out = static_cast<uInt>(output.size());
  if (inflateInit2(&stream, -MAX_WBITS) != Z_OK) return false;
  const int result = inflate(&stream, Z_FINISH);
  const bool passed = result == Z_STREAM_END && stream.avail_in == 0 &&
                      stream.total_out == output_size;
  inflateEnd(&stream);
  if (!passed) output.clear();
  return passed;
}

bool decode_payload(std::vector<std::uint8_t> stored, const TableEntry& entry,
                    std::vector<std::uint8_t>& payload) {
  retail_mode1_xor(stored, entry.index);
  if (entry.codec == RetailStorageCodec::Mode1PiXorRaw) {
    if (stored.size() != entry.expanded_size) return false;
    payload = std::move(stored);
    return true;
  }
  return inflate_raw(stored, static_cast<std::size_t>(entry.expanded_size), payload);
}

bool write_file_sync(const std::filesystem::path& path,
                     std::span<const std::uint8_t> bytes) {
  const int descriptor = ::open(path.c_str(), O_WRONLY | O_CREAT | O_EXCL, 0600);
  if (descriptor < 0) return false;
  std::size_t written = 0;
  while (written < bytes.size()) {
    const ssize_t count = ::write(descriptor, bytes.data() + written,
                                  bytes.size() - written);
    if (count < 0 && errno == EINTR) continue;
    if (count <= 0) {
      ::close(descriptor);
      return false;
    }
    written += static_cast<std::size_t>(count);
  }
  const bool synced = ::fsync(descriptor) == 0;
  const bool closed = ::close(descriptor) == 0;
  return synced && closed;
}

void sync_directory(const std::filesystem::path& path) noexcept {
  const int descriptor = ::open(path.c_str(), O_RDONLY | O_DIRECTORY);
  if (descriptor >= 0) {
    (void)::fsync(descriptor);
    (void)::close(descriptor);
  }
}

bool rename_replace(const std::filesystem::path& from,
                    const std::filesystem::path& to) {
  if (::rename(from.c_str(), to.c_str()) != 0) return false;
  sync_directory(to.parent_path());
  return true;
}

bool verified_file(const std::filesystem::path& path, std::uint64_t size,
                   const Sha256Digest& digest) {
  std::error_code error;
  if (!std::filesystem::is_regular_file(path, error) || error ||
      std::filesystem::file_size(path, error) != size || error) {
    return false;
  }
  Sha256Digest actual{};
  return sha256_file(path, actual, size) && actual == digest;
}

class StagingDirectory final {
 public:
  bool create(const std::filesystem::path& cache) {
    std::error_code error;
    const std::filesystem::path parent = cache / ".staging";
    std::filesystem::create_directories(parent, error);
    if (error) return false;
    for (unsigned ordinal = 0; ordinal < 100; ++ordinal) {
      path_ = parent / ("import-" + std::to_string(::getpid()) + "-" +
                        std::to_string(ordinal));
      if (std::filesystem::create_directory(path_, error)) return true;
      if (error && error != std::errc::file_exists) return false;
      error.clear();
    }
    return false;
  }

  const std::filesystem::path& path() const noexcept { return path_; }

  ~StagingDirectory() {
    if (!path_.empty()) {
      std::error_code ignored;
      std::filesystem::remove_all(path_, ignored);
    }
  }

 private:
  std::filesystem::path path_;
};

bool publish_blob(const std::filesystem::path& cache,
                  const std::filesystem::path& staging,
                  std::span<const std::uint8_t> bytes,
                  const Sha256Digest& digest) {
  const std::filesystem::path destination = blob_path(cache, digest);
  if (verified_file(destination, bytes.size(), digest)) return true;
  std::error_code error;
  std::filesystem::create_directories(destination.parent_path(), error);
  if (error) return false;
  const std::filesystem::path temporary = staging / sha256_hex(digest);
  if (!write_file_sync(temporary, bytes)) return false;
  if (rename_replace(temporary, destination)) return true;
  std::filesystem::remove(temporary, error);
  return verified_file(destination, bytes.size(), digest);
}

std::vector<std::uint8_t> make_index(const RetailIdentityPolicy& policy,
                                     const std::vector<RetailContentRecord>& records,
                                     const Sha256Digest& media_manifest_sha256) {
  std::vector<std::uint8_t> bytes;
  bytes.reserve(kIndexHeaderSize + records.size() * kIndexRecordSize);
  bytes.insert(bytes.end(), kIndexMagic.begin(), kIndexMagic.end());
  append_u32(bytes, kIndexVersion);
  append_u32(bytes, kIndexHeaderSize);
  append_u32(bytes, kIndexRecordSize);
  append_u32(bytes, static_cast<std::uint32_t>(records.size()));
  append_u32(bytes, policy.data_table_entries);
  append_u32(bytes, policy.pack_count);
  append_digest(bytes, policy.identity.xex_sha256);
  append_digest(bytes, policy.identity.data_table_sha256);
  append_digest(bytes, policy.identity.data00_sha256);
  append_digest(bytes, policy.identity.data01_sha256);
  append_u64(bytes, policy.identity.xex_size);
  append_u64(bytes, policy.identity.data_table_size);
  append_u64(bytes, policy.identity.data00_size);
  append_u64(bytes, policy.identity.data01_size);
  append_digest(bytes, media_manifest_sha256);
  for (const RetailContentRecord& record : records) {
    append_u32(bytes, record.data_table_index);
    append_u32(bytes, record.group);
    bytes.push_back(static_cast<std::uint8_t>(record.archive));
    bytes.push_back(static_cast<std::uint8_t>(record.codec));
    bytes.push_back(0);
    bytes.push_back(0);
    append_u64(bytes, record.source_offset);
    append_u64(bytes, record.stored_size);
    append_u64(bytes, record.expanded_size);
    append_u64(bytes, record.payload_size);
    append_digest(bytes, record.stored_sha256);
    append_digest(bytes, record.payload_sha256);
  }
  return bytes;
}

bool publish_index(const std::filesystem::path& cache,
                   const std::filesystem::path& staging,
                   std::span<const std::uint8_t> index,
                   const Sha256Digest& digest) {
  std::error_code error;
  const std::filesystem::path directory = cache / "indices";
  std::filesystem::create_directories(directory, error);
  if (error) return false;
  const std::filesystem::path destination = directory / (sha256_hex(digest) + ".ac6idx");
  if (!verified_file(destination, index.size(), digest)) {
    const std::filesystem::path temporary = staging / "index.ac6idx";
    if (!write_file_sync(temporary, index)) return false;
    if (!rename_replace(temporary, destination) &&
        !verified_file(destination, index.size(), digest)) {
      return false;
    }
  }
  std::vector<std::uint8_t> current;
  current.insert(current.end(), kCurrentMagic.begin(), kCurrentMagic.end());
  append_u32(current, kIndexVersion);
  append_u32(current, kCurrentSize);
  append_digest(current, digest);
  const std::filesystem::path temporary = staging / "current";
  return write_file_sync(temporary, current) &&
         rename_replace(temporary, cache / "current");
}

class BinaryReader final {
 public:
  explicit BinaryReader(std::span<const std::uint8_t> bytes) : bytes_(bytes) {}

  bool magic(const std::array<std::uint8_t, 8>& expected) {
    if (remaining() < expected.size() ||
        !std::equal(expected.begin(), expected.end(), bytes_.begin() + offset_)) {
      return false;
    }
    offset_ += expected.size();
    return true;
  }

  bool u8(std::uint8_t& value) {
    if (remaining() < 1) return false;
    value = bytes_[offset_++];
    return true;
  }

  bool u16(std::uint16_t& value) {
    std::uint8_t high{}, low{};
    if (!u8(high) || !u8(low)) return false;
    value = static_cast<std::uint16_t>((high << 8u) | low);
    return true;
  }

  bool u32(std::uint32_t& value) {
    if (remaining() < 4) return false;
    value = read_be32(bytes_.data() + offset_);
    offset_ += 4;
    return true;
  }

  bool u64(std::uint64_t& value) {
    std::uint32_t high{}, low{};
    if (!u32(high) || !u32(low)) return false;
    value = (static_cast<std::uint64_t>(high) << 32u) | low;
    return true;
  }

  bool digest(Sha256Digest& value) {
    if (remaining() < value.size()) return false;
    std::copy_n(bytes_.begin() + offset_, value.size(), value.begin());
    offset_ += value.size();
    return true;
  }

  std::size_t remaining() const noexcept { return bytes_.size() - offset_; }

 private:
  std::span<const std::uint8_t> bytes_;
  std::size_t offset_{};
};

bool read_current(const std::filesystem::path& cache, Sha256Digest& index_digest,
                  std::string& detail) {
  std::vector<std::uint8_t> bytes;
  if (!read_file(cache / "current", kCurrentSize, bytes) ||
      bytes.size() != kCurrentSize) {
    detail = "cache current record is missing or truncated";
    return false;
  }
  BinaryReader reader(bytes);
  std::uint32_t version{}, size{};
  if (!reader.magic(kCurrentMagic) || !reader.u32(version) || !reader.u32(size) ||
      !reader.digest(index_digest) || reader.remaining() != 0 ||
      version != kIndexVersion || size != kCurrentSize) {
    detail = "cache current record is incompatible";
    return false;
  }
  return true;
}

bool parse_index(std::span<const std::uint8_t> bytes,
                 const RetailIdentityPolicy& policy,
                 const RetailImportLimits& limits,
                 RetailSourceIdentity& identity,
                 Sha256Digest& media_manifest_sha256,
                 std::vector<RetailContentRecord>& records,
                 std::string& detail) {
  BinaryReader reader(bytes);
  std::uint32_t version{}, header_size{}, record_size{}, record_count{};
  std::uint32_t table_entries{}, pack_count{};
  if (!reader.magic(kIndexMagic) || !reader.u32(version) ||
      !reader.u32(header_size) || !reader.u32(record_size) ||
      !reader.u32(record_count) || !reader.u32(table_entries) ||
      !reader.u32(pack_count) || version != kIndexVersion ||
      header_size != kIndexHeaderSize || record_size != kIndexRecordSize ||
      record_count == 0 || record_count > limits.maximum_table_entries ||
      table_entries != policy.data_table_entries || pack_count != policy.pack_count) {
    detail = "content index header is incompatible";
    return false;
  }
  if (!reader.digest(identity.xex_sha256) ||
      !reader.digest(identity.data_table_sha256) ||
      !reader.digest(identity.data00_sha256) ||
      !reader.digest(identity.data01_sha256) ||
      !reader.u64(identity.xex_size) || !reader.u64(identity.data_table_size) ||
      !reader.u64(identity.data00_size) || !reader.u64(identity.data01_size) ||
      !reader.digest(media_manifest_sha256) ||
      identity != policy.identity ||
      reader.remaining() != static_cast<std::size_t>(record_count) * record_size) {
    detail = "content index retail identity or size mismatch";
    return false;
  }
  records.clear();
  records.reserve(record_count);
  std::uint64_t total = 0;
  for (std::uint32_t ordinal = 0; ordinal < record_count; ++ordinal) {
    RetailContentRecord record;
    std::uint8_t archive{}, codec{};
    std::uint16_t reserved{};
    if (!reader.u32(record.data_table_index) || !reader.u32(record.group) ||
        !reader.u8(archive) || !reader.u8(codec) || !reader.u16(reserved) ||
        !reader.u64(record.source_offset) || !reader.u64(record.stored_size) ||
        !reader.u64(record.expanded_size) || !reader.u64(record.payload_size) ||
        !reader.digest(record.stored_sha256) ||
        !reader.digest(record.payload_sha256) || reserved != 0 || archive > 1 ||
        codec < 1 || codec > 2 || record.data_table_index >= table_entries ||
        record.stored_size == 0 || record.expanded_size == 0 ||
        record.payload_size == 0 ||
        record.stored_size > limits.maximum_stored_size ||
        record.expanded_size > limits.maximum_expanded_size ||
        record.payload_size > limits.maximum_expanded_size ||
        record.expanded_size != record.payload_size ||
        !add_within(total, record.payload_size,
                    limits.maximum_total_expanded_size) ||
        (!records.empty() &&
         record.data_table_index <= records.back().data_table_index)) {
      detail = "content index record is invalid at ordinal " +
               std::to_string(ordinal);
      records.clear();
      return false;
    }
    record.archive = static_cast<RetailArchive>(archive);
    record.codec = static_cast<RetailStorageCodec>(codec);
    const RetailArchive group_archive =
        (record.group & 0x01000000u) != 0 ? RetailArchive::Data01
                                         : RetailArchive::Data00;
    const RetailStorageCodec group_codec =
        (record.group & 0x00020000u) != 0
            ? RetailStorageCodec::Mode1PiXorRaw
            : RetailStorageCodec::Mode1PiXorRawDeflate;
    const std::uint64_t archive_size =
        record.archive == RetailArchive::Data00 ? identity.data00_size
                                                : identity.data01_size;
    const bool duplicate_range = std::any_of(
        records.begin(), records.end(), [&record](const RetailContentRecord& previous) {
          return previous.archive == record.archive &&
                 previous.source_offset == record.source_offset &&
                 previous.stored_size == record.stored_size;
        });
    if (record.archive != group_archive || record.codec != group_codec ||
        !add_within(record.source_offset, record.stored_size, archive_size) ||
        (record.codec == RetailStorageCodec::Mode1PiXorRaw &&
         record.stored_size != record.expanded_size) ||
        duplicate_range) {
      detail = "content index record metadata is inconsistent at ordinal " +
               std::to_string(ordinal);
      records.clear();
      return false;
    }
    total += record.payload_size;
    records.push_back(record);
  }
  return reader.remaining() == 0;
}

}  // namespace

RetailIdentityPolicy RetailIdentityPolicy::pal() {
  RetailIdentityPolicy policy;
  policy.identity.xex_size = 7483392;
  policy.identity.data_table_size = 14824;
  policy.identity.data00_size = 2267086848ull;
  policy.identity.data01_size = 664141824ull;
  policy.data_table_entries = 926;
  policy.pack_count = 2;
  policy.media = RetailMediaPolicy::pal();
  (void)parse_sha256("acc302c1599c7a2fd38bd5a7de395b418a157d7001b6f986ab7113f45711bcde",
                     policy.identity.xex_sha256);
  (void)parse_sha256("82700410d305dc2d24e24d378ce5b9b63f240ac208842d7620b608fac15d50f5",
                     policy.identity.data_table_sha256);
  (void)parse_sha256("c3ed20ec6ef0260671d9cd5f3e088fab2a8d983cb6739efab350c87c6fb74816",
                     policy.identity.data00_sha256);
  (void)parse_sha256("eddb687418d4b49e36dd8b4e06f387e79be9c0792e97ea3405ab00dab76c03b4",
                     policy.identity.data01_sha256);
  return policy;
}

const char* retail_content_error_name(RetailContentError error) noexcept {
  switch (error) {
    case RetailContentError::None: return "none";
    case RetailContentError::InvalidArgument: return "invalid_argument";
    case RetailContentError::SourceMissing: return "source_missing";
    case RetailContentError::SourceIdentityMismatch: return "source_identity_mismatch";
    case RetailContentError::DataTableInvalid: return "data_table_invalid";
    case RetailContentError::EntryDuplicate: return "entry_duplicate";
    case RetailContentError::EntryOutOfRange: return "entry_out_of_range";
    case RetailContentError::SourceRangeInvalid: return "source_range_invalid";
    case RetailContentError::SizeLimitExceeded: return "size_limit_exceeded";
    case RetailContentError::DecodeFailed: return "decode_failed";
    case RetailContentError::CacheIoFailed: return "cache_io_failed";
    case RetailContentError::CacheIncompatible: return "cache_incompatible";
    case RetailContentError::CacheIncomplete: return "cache_incomplete";
    case RetailContentError::CacheDigestMismatch: return "cache_digest_mismatch";
  }
  return "unknown";
}

void retail_mode1_xor(std::span<std::uint8_t> bytes,
                      std::uint32_t data_table_index) noexcept {
  const std::uint64_t pad = kMode1Pads[data_table_index & 0xffu];
  for (std::size_t index = 0; index < bytes.size(); ++index) {
    const unsigned shift = 56u - static_cast<unsigned>(index & 7u) * 8u;
    bytes[index] ^= static_cast<std::uint8_t>(pad >> shift);
  }
}

RetailContentImporter::RetailContentImporter(RetailIdentityPolicy policy,
                                             RetailImportLimits limits)
    : policy_(std::move(policy)), limits_(limits) {}

RetailImportReport RetailContentImporter::run(
    const std::filesystem::path& source_root,
    const std::filesystem::path& cache_root,
    std::span<const std::uint32_t> data_table_entries) const {
  RetailImportReport report;
  const auto fail = [&](RetailContentError error, std::string detail) {
    report.error = error;
    report.detail = std::move(detail);
    return report;
  };
  if (source_root.empty() || cache_root.empty() ||
      limits_.maximum_table_entries == 0) {
    return fail(RetailContentError::InvalidArgument,
                "source and cache roots must be non-empty");
  }

  const RetailContentError source_error =
      qualify_source_files(source_root, policy_, report.detail);
  if (source_error != RetailContentError::None) {
    report.error = source_error;
    return report;
  }

  std::vector<std::uint8_t> table_bytes;
  if (!read_file(source_root / "DATA.TBL", limits_.maximum_table_size,
                 table_bytes)) {
    return fail(RetailContentError::DataTableInvalid,
                "cannot read bounded DATA.TBL");
  }
  std::vector<TableEntry> table;
  if (!parse_table(table_bytes, policy_, limits_, table, report.detail)) {
    report.error = report.detail.find("duplicate PAC range") != std::string::npos
                       ? RetailContentError::EntryDuplicate
                       : RetailContentError::DataTableInvalid;
    return report;
  }
  std::vector<std::uint32_t> complete_entries;
  if (data_table_entries.empty()) {
    complete_entries.resize(table.size());
    std::iota(complete_entries.begin(), complete_entries.end(), 0u);
    data_table_entries = complete_entries;
  }
  std::vector<TableEntry> selected;
  if (!select_entries(table, data_table_entries, limits_, selected,
                      report.detail)) {
    if (report.detail.starts_with("duplicate")) {
      report.error = RetailContentError::EntryDuplicate;
    } else if (report.detail.find("out of range") != std::string::npos) {
      report.error = RetailContentError::EntryOutOfRange;
    } else if (report.detail.find("limits") != std::string::npos) {
      report.error = RetailContentError::SizeLimitExceeded;
    } else {
      report.error = RetailContentError::InvalidArgument;
    }
    return report;
  }

  std::error_code error;
  std::filesystem::create_directories(cache_root, error);
  if (error) return fail(RetailContentError::CacheIoFailed, "cannot create cache root");
  StagingDirectory staging;
  if (!staging.create(cache_root)) {
    return fail(RetailContentError::CacheIoFailed,
                "cannot create cache staging directory");
  }

  std::vector<RetailContentRecord> records;
  Sha256Digest media_manifest_sha256{};
  if (!import_retail_media(source_root, cache_root, staging.path(), policy_.media,
                           media_manifest_sha256, report.detail)) {
    report.error = RetailContentError::CacheIoFailed;
    return report;
  }
  records.reserve(selected.size());
  for (const TableEntry& entry : selected) {
    std::vector<std::uint8_t> stored;
    if (!read_range(archive_path(source_root, entry.archive), entry.offset,
                    entry.stored_size, stored)) {
      return fail(RetailContentError::SourceRangeInvalid,
                  "short PAC read at DATA.TBL entry " +
                      std::to_string(entry.index));
    }
    RetailContentRecord record;
    record.data_table_index = entry.index;
    record.group = entry.group;
    record.archive = entry.archive;
    record.codec = entry.codec;
    record.source_offset = entry.offset;
    record.stored_size = entry.stored_size;
    record.expanded_size = entry.expanded_size;
    record.stored_sha256 = sha256_bytes(stored);
    std::vector<std::uint8_t> payload;
    if (!decode_payload(std::move(stored), entry, payload)) {
      return fail(RetailContentError::DecodeFailed,
                  "mode-1 decode failed at DATA.TBL entry " +
                      std::to_string(entry.index));
    }
    record.payload_size = payload.size();
    record.payload_sha256 = sha256_bytes(payload);
    if (!publish_blob(cache_root, staging.path(), payload,
                      record.payload_sha256)) {
      return fail(RetailContentError::CacheIoFailed,
                  "cannot publish payload blob at DATA.TBL entry " +
                      std::to_string(entry.index));
    }
    report.imported_bytes += payload.size();
    records.push_back(record);
  }

  // Re-qualify after all bounded reads. This closes the source mutation window:
  // an index is never published under the PAL identity if a PAC changed while
  // the importer was decoding it.
  const RetailContentError final_source_error =
      qualify_source_files(source_root, policy_, report.detail);
  if (final_source_error != RetailContentError::None) {
    report.error = final_source_error;
    return report;
  }

  const std::vector<std::uint8_t> index = make_index(policy_, records,
                                                     media_manifest_sha256);
  report.index_sha256 = sha256_bytes(index);
  if (!publish_index(cache_root, staging.path(), index, report.index_sha256)) {
    return fail(RetailContentError::CacheIoFailed,
                "cannot atomically publish content index");
  }
  report.imported_records = records.size();
  report.error = RetailContentError::None;
  return report;
}

RetailContentStore::RetailContentStore(RetailIdentityPolicy policy,
                                       RetailImportLimits limits)
    : policy_(std::move(policy)), limits_(limits) {}

bool RetailContentStore::fail(RetailContentError error, std::string detail) {
  records_.clear();
  error_ = error;
  detail_ = std::move(detail);
  return false;
}

void RetailContentStore::close() noexcept {
  cache_root_.clear();
  identity_ = {};
  index_sha256_ = {};
  records_.clear();
  media_ = RetailMediaStore{};
  error_ = RetailContentError::CacheIncomplete;
  detail_.clear();
}

bool RetailContentStore::open(const std::filesystem::path& cache_root) {
  close();
  if (cache_root.empty()) {
    return fail(RetailContentError::InvalidArgument, "cache root is empty");
  }
  Sha256Digest index_digest{};
  if (!read_current(cache_root, index_digest, detail_)) {
    return fail(detail_.find("incompatible") != std::string::npos
                    ? RetailContentError::CacheIncompatible
                    : RetailContentError::CacheIncomplete,
                detail_);
  }
  const std::filesystem::path index_path =
      cache_root / "indices" / (sha256_hex(index_digest) + ".ac6idx");
  const std::uint64_t maximum_index_size =
      kIndexHeaderSize +
      static_cast<std::uint64_t>(limits_.maximum_table_entries) * kIndexRecordSize;
  std::vector<std::uint8_t> index;
  if (!read_file(index_path, maximum_index_size, index)) {
    return fail(RetailContentError::CacheIncomplete,
                "content index is missing or too large");
  }
  if (sha256_bytes(index) != index_digest) {
    return fail(RetailContentError::CacheDigestMismatch,
                "content index digest mismatch");
  }
  Sha256Digest media_manifest_sha256{};
  if (!parse_index(index, policy_, limits_, identity_, media_manifest_sha256,
                   records_, detail_)) {
    return fail(RetailContentError::CacheIncompatible, detail_);
  }
  if (policy_.media.required) {
    if (!media_.open(cache_root, policy_.media) ||
        media_.manifest_sha256() != media_manifest_sha256) {
      return fail(RetailContentError::CacheIncomplete,
                  "content index references an unavailable media manifest");
    }
  } else if (media_manifest_sha256 != Sha256Digest{}) {
    return fail(RetailContentError::CacheIncompatible,
                "optional media policy cannot open a media-bound index");
  }
  for (const RetailContentRecord& record : records_) {
    if (!verified_file(blob_path(cache_root, record.payload_sha256),
                       record.payload_size, record.payload_sha256)) {
      return fail(RetailContentError::CacheIncomplete,
                  "payload blob is missing or corrupt for DATA.TBL entry " +
                      std::to_string(record.data_table_index));
    }
  }
  cache_root_ = cache_root;
  index_sha256_ = index_digest;
  error_ = RetailContentError::None;
  detail_.clear();
  return true;
}

const RetailContentRecord* RetailContentStore::find(
    std::uint32_t data_table_index) const noexcept {
  const auto found = std::lower_bound(
      records_.begin(), records_.end(), data_table_index,
      [](const RetailContentRecord& record, std::uint32_t index) {
        return record.data_table_index < index;
      });
  return found != records_.end() && found->data_table_index == data_table_index
             ? &*found
             : nullptr;
}

bool RetailContentStore::read_payload(std::uint32_t data_table_index,
                                      std::vector<std::uint8_t>& payload) const {
  const RetailContentRecord* record = find(data_table_index);
  if (record == nullptr ||
      !read_file(blob_path(cache_root_, record->payload_sha256),
                 limits_.maximum_expanded_size, payload) ||
      payload.size() != record->payload_size ||
      sha256_bytes(payload) != record->payload_sha256) {
    payload.clear();
    return false;
  }
  return true;
}

std::filesystem::path default_retail_cache_root() {
  if (const char* xdg = std::getenv("XDG_CACHE_HOME"); xdg != nullptr && *xdg != 0) {
    const std::filesystem::path root(xdg);
    if (root.is_absolute()) return root / "ac6-native";
  }
  if (const char* home = std::getenv("HOME"); home != nullptr && *home != 0) {
    const std::filesystem::path root(home);
    if (root.is_absolute()) return root / ".cache" / "ac6-native";
  }
  return {};
}

}  // namespace ac6
