#!/usr/bin/env python3
"""Run 0x82381068 against the port -- the cosine cycle 1410 refused a curve over.

Cycle 1410 read the layout-1 axis response curve at 0x82229470 and refused to
port it, because `std::cos` disagreed with this routine at one argument in 96
even after the block's float32 rounding. Cycle 1412 showed the way out on a
different routine: port the retail one. This is that, for this one.

IT IS DOUBLE PRECISION AND IT NEEDS NO ARBITRATION. 54 instructions, a leaf, and
NOT ONE VECTOR INSTRUCTION -- which is the whole difference from 0x8209CB70.
Every operation is an IEEE-754 double `fadd`, `fmul`, `fsub`, `fmadd` or
`fnmsub`, all exactly specified, so there is no association order to arbitrate
and no lane semantics to assert. The only two things a port can get wrong are
which operations are FUSED and the order of the Horner steps, and both are
readable off the listing.

WHAT IT COMPUTES, from the table at 0x8267A628:

    n = nearbyint((|x| + pi/2) * (1/pi))          fctid, round-to-nearest-even
    t = n - 0.5
    y = fnmsub(pi_lo, t, fnmsub(pi_hi, t, |x|))   Cody-Waite, two fused steps
    s = y * horner(y*y)                            an ODD series -- a SINE kernel
    if (n & 1) s = -s
    if (|x| == 0.0) return 1.0                     exact, before anything else
    return (|x| + pi/2 >= 220000000) ? NaN : s

THE BIAS IS WHAT MAKES IT A COSINE. The kernel is sine; adding pi/2 to |x|
before the reduction shifts it by a quadrant. Cycle 1410 identified this routine
as cosine EMPIRICALLY -- 3 of 7 exact against std::cos, 0 of 7 against std::sin
-- and the pi/2 at table+0 is the structural confirmation of that measurement.
Neither alone would have been enough: the empirical result had four misses it
could not explain, and the structure alone cannot tell a sine kernel biased by
pi/2 from a cosine kernel biased by nothing.

THE FUSED OPERATIONS ARE FUSED AND THE OTHERS ARE NOT. `fnmsub` and `fmadd` are
one rounding each; `fmul f0,f0,f13` at 0x82381108 is a plain multiply. A port
that fused the last multiply into the Horner chain, or unfused the reduction,
differs in the last bit -- and CMakeLists disables -ffp-contract for exactly
this reason (cycle 1412).

    python3 tools/audit_scalar_cos_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_scalar_cos_microexec.py --check --workdir W
"""

from __future__ import annotations

import argparse
import json
import math
import struct
from pathlib import Path

COS = 0x82381068
TABLE = 0x8267A628

HALF_PI = 1.5707963267948966       # table+0
INV_PI = 0.3183098861837907        # table+8
OVERFLOW_AT = 220000000.0          # table+16
EXACT_ARGUMENT = 0.0               # table+24, a float
EXACT_RESULT = 1.0                 # table+28, a float
HALF = 0.5                         # table+36, a float
PI_HI = 3.1415926534682512         # table+40
PI_LO = 1.2154201012607932e-10     # table+48

# table+112 down to table+56, then 1.0 from 0x82069C68. Horner in y*y.
POLYNOMIAL = [
    2.7204790957888847e-15,
    -7.642917806891047e-13,
    1.605893649037159e-10,
    -2.5052106798274583e-08,
    2.7557319210152756e-06,
    -0.0001984126984120184,
    0.008333333333333165,
    -0.16666666666666666,
    1.0,
]

# The curve at 0x82229470 calls this with |x| * (pi/2) for |x| in [0, 1], so
# [0, pi/2] is the domain that matters and it is swept densely. The rest are the
# routine's own seams: the exact-zero return, the quadrant boundaries, and both
# sides of the overflow guard.
SWEEP = 160
NAMED = [0.0, -0.0, HALF_PI, -HALF_PI, math.pi, -math.pi, 1.0, -1.0,
         0.7853981633974483, 3.0 * math.pi / 2.0, 2.0 * math.pi, 10.0, -10.0,
         1000.0, 219999999.0, 220000001.0, 1e-300, 4.9406564584124654e-324]

SPEC = """\
# Generated by tools/audit_scalar_cos_microexec.py --emit.
# 0x82381068 at {angle!r}.
#
# A scalar leaf: no vector instructions, nothing stubbed.  ONE asserted
# semantic, and it is the point of cycle 1413: the module executes `fctid` as
# though it were `fctidz`, truncating where the ISA rounds to nearest -- 3.683
# becomes 3 and 6.866 becomes 6.  Without the override this routine evaluates its
# sine kernel a whole quadrant outside its range and is wrong by up to 5.8e-09,
# which is what cycle 1410 measured and mistook for a property of the routine.
# f1 carries a DOUBLE in and a double out, so the seed is the full 64-bit value
# and not a float32 pattern -- a bare hex seed here would be a denormal.

function {fn:#010x}
case cos:{name}

region stack 0xC0000000 zero:0x2000

sp 0xC0001000
gpr r0 0
fpr f1 f:{angle!r}
steps 200
override 0x82381094 fctid
override 0x823810AC fnmsub
override 0x823810B4 fnmsub
override 0x823810BC fmadd
override 0x823810C4 fmadd
override 0x823810D0 fmadd
override 0x823810E4 fmadd
override 0x823810EC fmadd
override 0x823810F4 fmadd
override 0x823810FC fmadd
override 0x82381104 fmadd
capture fpr:f1
"""


def angles() -> list[float]:
    return NAMED + [HALF_PI * index / (SWEEP - 1) for index in range(SWEEP)]


def model(x: float) -> float:
    """The port, in Python. `retail_scalar_cos.cpp` is the same steps in C++."""
    magnitude = math.fabs(x)
    biased = HALF_PI + magnitude                       # 0x82381080
    scaled = INV_PI * biased                           # 0x82381090
    # fctid then fcfid: round to nearest even, back to double. fctidz on the same
    # value gives the integer whose low bit is the quadrant parity; since the
    # value is already integral the two agree, which is why one nearbyint serves.
    whole = math.nan if math.isinf(scaled) or math.isnan(scaled) else float(
        _round_half_even(scaled))
    parity = int(abs(whole)) & 1 if whole == whole else 0
    offset = whole - HALF                              # 0x823810A0, the float 0.5
    # 0x823810AC and 0x823810B4, both fnmsub: one rounding each.
    reduced = math.fma(-PI_HI, offset, magnitude)
    reduced = math.fma(-PI_LO, offset, reduced)

    square = reduced * reduced                         # 0x823810B8, plain fmul
    accumulator = POLYNOMIAL[0]
    for coefficient in POLYNOMIAL[1:]:
        accumulator = math.fma(accumulator, square, coefficient)  # fmadd, fused
    result = accumulator * reduced                     # 0x82381108, plain fmul
    if parity:
        result = -result                               # 0x82381110

    if magnitude == EXACT_ARGUMENT:                    # 0x82381118, fcmpu then beq
        return EXACT_RESULT
    # 0x82381138, fsel: >= 0 takes the NaN, so an argument at or past the guard
    # returns NaN rather than a reduced-to-nothing angle.
    return math.nan if biased - OVERFLOW_AT >= 0.0 else result


def _round_half_even(value: float) -> int:
    floor = math.floor(value)
    fraction = value - floor
    if fraction > 0.5:
        return int(floor) + 1
    if fraction < 0.5:
        return int(floor)
    return int(floor) + (int(floor) & 1)


def bits(value: float) -> int:
    return struct.unpack(">Q", struct.pack(">d", value))[0]


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for index, angle in enumerate(angles()):
        name = f"cos-{index}"
        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(SPEC.format(fn=COS, name=name, angle=angle), encoding="utf-8")
        manifest.append(f"{spec.resolve()} {(workdir / 'out' / (name + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    lines, failures, compared = [], 0, 0
    library_gap = 0
    for index, angle in enumerate(angles()):
        path = workdir / "out" / f"cos-{index}.json"
        if not path.exists():
            print(f"MISSING {path}")
            failures += 1
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            print(f"FAIL cos-{index}: exit={document['exit']!r}")
            failures += 1
            continue
        raw = document["registers"]["f1"]
        retail = struct.unpack(">d", struct.pack(">Q", int(raw, 16)))[0]
        port = model(angle)
        same = (bits(retail) == bits(port)
                or (math.isnan(retail) and math.isnan(port)))
        compared += 1
        if not same:
            failures += 1
            print(f"FAIL at {angle!r}: retail={retail!r} port={port!r}")
        if not math.isnan(retail) and abs(angle) < OVERFLOW_AT:
            if bits(retail) != bits(math.cos(angle)):
                library_gap += 1
        lines.append(f"{angle!r}\t{retail!r}\t{port!r}\t{'ok' if same else 'FAIL'}")
    print(f"cases={len(angles())} values={compared} failures={failures}")
    print(f"  and it is not std::cos: {library_gap} of {compared} differ from the library")
    if report:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text("angle\tretail\tport\tverdict\n" + "\n".join(lines) + "\n",
                          encoding="utf-8")
        print(f"wrote {report}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    if args.emit:
        return emit(args.workdir)
    if args.check:
        return check(args.workdir, args.report)
    parser.error("one of --emit or --check")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
