#!/usr/bin/env python3
"""Check each asserted VMX128 behaviour on its own, against a hand-computed answer.

Cycle 1295 implemented four operations the Xenon SLEIGH module leaves without
emulation semantics, validated none of them individually, and debugged them
through a 547-step composite of 271 instructions. The composite localised
nothing: three different inputs produced byte-identical output and there was no
way to say which of the four was at fault.

This is the missing half. Each case executes **one retail instruction**, with
every input seeded and the output register captured, and compares it against a
value worked out by hand and written down here beside it. A behaviour that
fails here fails alone.

The instruction addresses are real sites in the image, not synthesised
encodings, so the operand wiring under test is the wiring the harness will meet.

    python3 tools/audit_vmx128_behaviours.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_vmx128_behaviours.py --check --workdir W
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# A 32-byte fixture with every byte distinct, so a misplaced lane is visible as
# a value rather than as a coincidence.
FIXTURE = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
FIXTURE_BASE = 0xB6000000

# Two vectors whose words are all distinct and not palindromic, for the same
# reason. VA reads forward, VB backward.
VA = "00112233445566778899aabbccddeeff"
VB = "0f0e0d0c0b0a09080706050403020100"


def words(hex_text: str) -> list[str]:
    return [hex_text[i:i + 8] for i in range(0, 32, 8)]


VA_W, VB_W = words(VA), words(VB)

# vmrghw vD,vA,vB : vD = {vA[0], vB[0], vA[1], vB[1]}
EXPECT_MRGHW = VA_W[0] + VB_W[0] + VA_W[1] + VB_W[1]
# vmrglw vD,vA,vB : vD = {vA[2], vB[2], vA[3], vB[3]}
EXPECT_MRGLW = VA_W[2] + VB_W[2] + VA_W[3] + VB_W[3]

# vrlimi128 vD,vB,0x4,0x3 : rotate vB left by 3 words, then element i comes from
# the rotated vB when bit (3-i) of the mask is set and from vD otherwise.
# mask 0x4 = 0b0100 -> only element 1 comes from the rotated vB.
_ROT3 = [VB_W[(i + 3) & 3] for i in range(4)]
EXPECT_VRLIMI = VA_W[0] + _ROT3[1] + VA_W[2] + VA_W[3]

# lvlx: the bytes from EA to the end of EA's 16-byte block, left-justified,
# zero-filled. eb = EA & 0xF.
def expect_lvlx(offset: int) -> str:
    eb = offset & 0xF
    taken = FIXTURE[2 * offset: 2 * (offset + 16 - eb)]
    return taken + "00" * eb


CASES = [
    {
        "name": "vmrghw",
        # 0x820998E8  vmrghw v6,v10,v8 -> vs38 = CALLOTHER(vs42, vs40)
        "function": 0x820998E8,
        "vec": {"vs42": VA, "vs40": VB},
        "capture": "vs38",
        "expect": EXPECT_MRGHW,
    },
    {
        "name": "vmrglw",
        # 0x820998FC  vmrglw v10,v6,v5 -> vs42 = CALLOTHER(vs38, vs37)
        "function": 0x820998FC,
        "vec": {"vs38": VA, "vs37": VB},
        "capture": "vs42",
        "expect": EXPECT_MRGLW,
    },
    {
        "name": "vrlimi128",
        # 0x820A9B98  vrlimi128 vr12,vr13,0x4,0x3 -> vr12 = CALLOTHER(vr12, vr13, 4, 3)
        # The destination is an input: the instruction inserts under a mask.
        "function": 0x820A9B98,
        "vec": {"vr12": VA, "vr13": VB},
        "capture": "vr12",
        "expect": EXPECT_VRLIMI,
    },
]

# 0x820A9B8C  lvlx v13,r0,r8 -> vs45 = CALLOTHER(r0, r8)
# Three alignments: none, mid-block, and one byte-group from the end. The third
# is the one that fails if the zero-fill is on the wrong side.
for _offset in (0, 4, 12):
    CASES.append({
        "name": f"lvlx+{_offset}",
        "function": 0x820A9B8C,
        "gpr": {"r8": FIXTURE_BASE + _offset},
        "capture": "vs45",
        "expect": expect_lvlx(_offset),
    })

SPEC_HEADER = """\
# Generated by tools/audit_vmx128_behaviours.py --emit.
# One retail instruction, every input seeded, the output captured.
# Expected: 0x{expect}

function {function:#010x}
case vmx128:{name}
steps 1

region fixture {fixture_base:#010x} bytes:{fixture}
region stack   0xC0000000 zero:0x1000
sp 0xC0000E00

vmx on
"""


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for case in CASES:
        lines = [SPEC_HEADER.format(expect=case["expect"], function=case["function"],
                                    name=case["name"], fixture=FIXTURE,
                                    fixture_base=FIXTURE_BASE)]
        for register, value in case.get("gpr", {}).items():
            lines.append(f"gpr {register} {value:#010x}")
        for register, value in case.get("vec", {}).items():
            lines.append(f"vec {register} {value}")
        lines.append(f"capture vec:{case['capture']}")
        spec = workdir / "specs" / f"{case['name']}.spec"
        out = workdir / "out" / f"{case['name']}.json"
        spec.write_text("\n".join(lines) + "\n", encoding="utf-8")
        manifest.append(f"{spec.resolve()} {out.resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(CASES)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path) -> int:
    passed, failures = 0, []
    for case in CASES:
        path = workdir / "out" / f"{case['name']}.json"
        if not path.exists():
            failures.append(f"{case['name']}: no snapshot")
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        fired = document["provenance"].get("asserted_semantics", {})
        got = document.get("registers", {}).get(case["capture"], "")
        want = "0x" + case["expect"]
        if got != want:
            failures.append(f"{case['name']}: got {got} want {want} (fired {fired})")
            continue
        # An operation that never fired cannot have been tested, and a captured
        # register that happens to hold the seed would pass silently.
        if not fired:
            failures.append(f"{case['name']}: matched but no behaviour fired")
            continue
        passed += 1
    print(f"cases={len(CASES)} passed={passed} failures={len(failures)}")
    for failure in failures:
        print(f"  {failure}", file=sys.stderr)
    if failures:
        print("vmx128_behaviours=fail", file=sys.stderr)
        return 1
    print("vmx128_behaviours=pass")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return emit(arguments.workdir) if arguments.emit else check(arguments.workdir)


if __name__ == "__main__":
    raise SystemExit(main())
