#!/usr/bin/env python3
"""Differential for the input binding layer, 0x82211C10.

The plan forbids a flight behaviour entering the contract without one, and cycle
1354 withheld the entry rather than bend that. This supplies it.

The capsule is entirely synthetic and every field is one the reading named:

    r3  player block   [+0x88] enabled slots, [+0x8C] invert mask,
                       [+0x08 + 4i] the record-bit mask for slot i,
                       24-byte descriptors from +24*(bit+6)
    r4  input record   float slots at (bit + 3) * 4 -- the rule
                       ac6::retail::float_slot_for_bit already implements
    r5  a mask word the layer ORs into
    r6..r9  four output arrays

THE 912-BYTE STRIDE IS A CHECK, NOT A CHOICE. 0x82211DF8 advances the player
block by 912 bytes per player, and 24 * (31 + 6) + 24 is exactly 912 -- so the
descriptors for record bits 0..31 fill the block precisely. Two numbers read from
different functions agreeing is why the layout below is not a guess.

    python3 tools/audit_input_binding_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_input_binding_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path

FUNCTION = 0x82211C10
PLAYER = 0xB8000000
RECORD = 0xB9000000
MASKWORD = 0xBB000000
ARRAYS = 0xBA000000
ARRAY_STRIDE = 0x80          # r6, r7, r8, r9 -- as retail spaces them
PLAYER_BYTES = 912
RECORD_BYTES = 0xA0

# One binding on record bit 17, which is the LY axis in the contracted record
# layout, so the slot the capsule drives is the slot a stick actually reaches.
RECORD_BIT = 17
SLOT = 0
DEADZONE, SCALE, THRESHOLD = 0.25, 2.0, 0.75

# Values chosen where a wrong rule and the right one diverge: the deadzone and
# threshold exactly, either side of each, the clamp, both signs, and NEGATIVE
# ZERO -- which cycle 1323 measured is what an idle axis leaves in the record.
VALUES = [0.0, -0.0, 0.1, -0.1, 0.25, -0.25, 0.2500001, 0.3, -0.3,
          0.5, -0.5, 0.75, -0.75, 0.7500001, 0.9, -0.9, 1.0, -1.0, 2.0]


def descriptor_offset(bit: int) -> int:
    return 24 * (bit + 6)


def build_player(invert: bool) -> bytes:
    blob = bytearray(PLAYER_BYTES)
    struct.pack_into(">I", blob, 0x88, 1 << SLOT)              # this slot enabled
    struct.pack_into(">I", blob, 0x8C, (1 << SLOT) if invert else 0)
    struct.pack_into(">I", blob, 0x08 + 4 * SLOT, 1 << RECORD_BIT)
    base = descriptor_offset(RECORD_BIT)
    struct.pack_into(">f", blob, base + 0x0C, THRESHOLD)
    struct.pack_into(">f", blob, base + 0x10, DEADZONE)
    struct.pack_into(">f", blob, base + 0x14, SCALE)
    return bytes(blob)


def build_record(value: float) -> bytes:
    blob = bytearray(RECORD_BYTES)
    struct.pack_into(">f", blob, (RECORD_BIT + 3) * 4, value)
    return bytes(blob)


SPEC = """\
# Generated by tools/audit_input_binding_microexec.py --emit.
# {note}

function {function:#010x}
case input-binding:{name}
steps 40000

region player  {player:#010x} bytes:{player_blob}
region record  {record:#010x} bytes:{record_blob}
region maskword {maskword:#010x} poison:0x10
region arrays  {arrays:#010x} poison:0x200
region stack   0xC0000000 zero:0x4000
dump player

sp 0xC0002000
gpr r3 {player:#010x}
gpr r4 {record:#010x}
gpr r5 {maskword:#010x}
gpr r6 {a6:#010x}
gpr r7 {a7:#010x}
gpr r8 {a8:#010x}
gpr r9 {a9:#010x}
gpr r0 0
"""


def cases() -> list[dict]:
    built = []
    for invert in (False, True):
        for value in VALUES:
            label = f"{'inv-' if invert else ''}{value!r}".replace(".", "p").replace("-", "m")
            built.append({
                "name": label, "value": value, "invert": invert,
                "note": f"record bit {RECORD_BIT} = {value!r}"
                        f"{', invert mask set' if invert else ''}",
            })
    return built


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for case in cases():
        spec = workdir / "specs" / f"{case['name']}.spec"
        spec.write_text(SPEC.format(
            note=case["note"], function=FUNCTION, name=case["name"],
            player=PLAYER, player_blob=build_player(case["invert"]).hex(),
            record=RECORD, record_blob=build_record(case["value"]).hex(),
            maskword=MASKWORD, arrays=ARRAYS,
            a6=ARRAYS, a7=ARRAYS + ARRAY_STRIDE,
            a8=ARRAYS + 2 * ARRAY_STRIDE, a9=ARRAYS + 3 * ARRAY_STRIDE),
            encoding="utf-8")
        manifest.append(f"{spec.resolve()} {(workdir / 'out' / (case['name'] + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def native(value: float) -> tuple[float, float] | None:
    """ac6::retail::apply_input_binding, in Python, from the same reading.

    Deliberately a SECOND expression of the rule rather than a call into the C++:
    if the two disagree, one of them mistranscribed the function, which is what a
    differential is for.
    """
    # EVERY STEP IS SINGLE PRECISION. The record holds a float32 and retail's
    # fabs/fsubs/fmuls are all single, so a model that subtracts in double
    # disagrees in the last bits -- which is what the first run of this check
    # reported at 0.3 and at 0.2500001, and it was the model that was wrong.
    value = f32(value)
    scaled = f32(abs(value) - f32(DEADZONE))
    if scaled < 0.0:
        scaled = 0.0
    else:
        scaled = f32(scaled * f32(SCALE))
        if scaled > 1.0:
            scaled = 1.0
    result = scaled if value >= 0.0 else -scaled      # fsel: -0.0 is >= 0
    # 0x82211D50: fcmpu against 0.0 then beq to the loop increment. A binding
    # whose processed value is EXACTLY zero stores nothing -- no value, no step,
    # no mask bit -- so the output arrays keep whatever the previous frame left.
    # The reading missed this and the differential found it.
    if result == 0.0:
        return None
    step = value
    if abs(value) < f32(DEADZONE):
        step = 0.0
    if abs(value) > f32(THRESHOLD):
        step = 1.0 if step >= 0.0 else -1.0
    return f32(result), f32(step)


def check(workdir: Path, report: Path | None) -> int:
    failures: list[str] = []
    compared = 0
    for case in cases():
        path = workdir / "out" / f"{case['name']}.json"
        if not path.exists():
            print(f"{case['name']}: no snapshot", file=sys.stderr)
            return 1
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            failures.append(f"{case['name']}: exit={document['exit']}")
            continue
        memory: dict[int, int] = {}
        for run in document.get("memory_writes", []):
            address = int(run["address"], 16)
            for index, byte in enumerate(bytes.fromhex(run["after_hex_b"])):
                memory[address + index] = byte

        def word(address: int) -> int | None:
            if any(address + n not in memory for n in range(4)):
                return None
            return int.from_bytes(bytes(memory[address + n] for n in range(4)), "big")

        expected = native(case["value"])
        got_value = word(ARRAYS + 4 * SLOT)
        got_step = word(ARRAYS + ARRAY_STRIDE + 4 * SLOT)
        if expected is None:
            # Nothing may be stored, and the mask bit must stay clear.
            if got_value is not None or got_step is not None:
                failures.append(f"{case['name']}: stored something for a zero result")
        else:
            want_value, want_step = expected
            if case["invert"]:
                want_value, want_step = -want_value, -want_step
            for label, got, want in (("value", got_value, want_value),
                                     ("step", got_step, want_step)):
                expect = struct.unpack(">I", struct.pack(">f", want))[0]
                if got is None:
                    failures.append(f"{case['name']}: {label} not written")
                elif got != expect:
                    failures.append(f"{case['name']}: {label} 0x{got:08X} want 0x{expect:08X}")
        compared += 1

    print(f"cases={compared} failures={len(failures)}")
    for line in failures[:20]:
        print(f"  {line}", file=sys.stderr)
    if failures:
        print("input_binding_microexec=fail", file=sys.stderr)
        return 1
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps({
            "schema": "ac6.input-binding-microexec.v1",
            "statement": "0x82211C10 executed on a synthetic player block and input "
                         "record, both outputs compared bit for bit against the "
                         "ported rule, over values chosen at the deadzone and "
                         "threshold boundaries and including negative zero",
            "function": f"0x{FUNCTION:08X}",
            "record_bit": RECORD_BIT,
            "record_slot": f"0x{(RECORD_BIT + 3) * 4:02X}",
            "deadzone": DEADZONE, "scale": SCALE, "threshold": THRESHOLD,
            "cases": compared, "divergences": 0,
            "values": VALUES,
        }, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {report}")
    print("input_binding_microexec=pass")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return emit(arguments.workdir) if arguments.emit else check(arguments.workdir,
                                                               arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
