#!/usr/bin/env python3
"""Sweep each axis half through 0x821CAA50 and read the float slot it fills.

A7 exit criteria 4 and 5. The rule the port needs is "half -> float", and it has
never been executed at more than one point: cycle 1320 ran LY+ at 30000, got
float32(30000/32767), and that single point is consistent with several rules.

WHAT THE ONE POINT ALREADY CONTRADICTS. Cycle 1315 read a deadzone at 0x800 and
wrote "at or below it the lane is not written, and the slot is therefore zero".
The null control of cycle 1322 -- every half at zero -- writes ALL FOUR axis
slots, with 0x80000000, negative zero. So the store is not gated by the deadzone
the way that sentence says, and what the deadzone gates is an open question this
sweep is built to answer.

THE DOMAIN IS 65,536 AND THE BUDGET IS NOT. One case is ~0.23 s of emulation, so
the full domain is about four hours per half and eighteen for the eight. This
samples instead, and says exactly what it sampled:

  * every boundary the A7 criteria name -- 0x07FF, 0x0800, 0x0801 around the
    deadzone, and 0x4000, 0x7FFF, 0x8000, 0xFFFF around the normalisation;
  * every power of two and its neighbours, where a threshold is likely to sit;
  * a uniform decimation across the rest.

A sampled sweep cannot prove a rule holds everywhere. It can refute one
everywhere it looks, and the boundaries are where a wrong rule and the right one
diverge -- which is the point of choosing them rather than the middle.

    python3 tools/audit_input_axis_sweep_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_input_axis_sweep_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from audit_input_consumer_microexec import (  # noqa: E402
    CONSUMER, CONTEXT, CONTROLLER_0, CONTROLLER_STRIDE, CONTEXT_VTABLE,
    CONTROLLER_VTABLE, HALVES, HINTS, LOCK_STUBS, MEMSET, RECORD_0, RECORDS,
    SERVICE, SLOTS,
)

# The half each axis slot is fed from, and its slot. From cycle 1318's mask
# table, confirmed by execution at cycle 1320.
HALF_SLOT = {
    "LX+": SLOTS["LX"], "LX-": SLOTS["LX"],
    "LY+": SLOTS["LY"], "LY-": SLOTS["LY"],
    "RX+": SLOTS["RX"], "RX-": SLOTS["RX"],
    "RY+": SLOTS["RY"], "RY-": SLOTS["RY"],
}

# Named boundaries first, so they are never lost to a decimation stride.
BOUNDARIES = [0x0000, 0x0001, 0x07FE, 0x07FF, 0x0800, 0x0801, 0x0802,
              0x1FFF, 0x2000, 0x2001, 0x3FFF, 0x4000, 0x4001,
              0x7FFE, 0x7FFF, 0x8000, 0x8001, 0xBFFF, 0xC000,
              0xFFFE, 0xFFFF]
# Powers of two and their neighbours: a threshold that is not at a named
# boundary is most likely at one of these.
POWERS = sorted({value + delta
                 for exponent in range(1, 16)
                 for value in (1 << exponent,)
                 for delta in (-1, 0, 1)})
# And a uniform net over the whole range, coarse enough to afford.
DECIMATION = list(range(0, 0x10000, 0x400))

# The fine sweep runs on ONE half, because the eight share a stage: 0x8234D110
# runs the same four iterations over the table at 0x8201250C for all of them, so
# a rule that differs per half would have to come from the consumer, and the
# other seven are checked at the boundaries to see whether it does.
FINE_HALF = "LY+"
COARSE_HALVES = [name for name in HALVES if name != FINE_HALF]


def sample_values() -> list[int]:
    return sorted(set(BOUNDARIES) | set(POWERS) | set(DECIMATION))


def build_service(half: str, value: int) -> bytes:
    span = (CONTROLLER_0 + CONTROLLER_STRIDE) - SERVICE + 0x40
    blob = bytearray(span)

    def put32(address: int, word: int) -> None:
        struct.pack_into(">I", blob, address - SERVICE, word & 0xFFFFFFFF)

    put32(SERVICE + 0x00, 1)
    put32(CONTEXT + 0x00, CONTEXT_VTABLE)
    for index in range(5):
        put32(CONTEXT + 0x04 + 4 * index, CONTROLLER_0)
    put32(CONTROLLER_0 + 0x00, CONTROLLER_VTABLE)
    put32(CONTROLLER_0 + 0x08, 0)
    struct.pack_into(">H", blob, CONTROLLER_0 + HALVES[half] - SERVICE,
                     value & 0xFFFF)
    return bytes(blob)


SPEC = """\
# Generated by tools/audit_input_axis_sweep_microexec.py --emit.
# One axis half at one value; everything else zero.

function {consumer:#010x}
case retail-input-axis:{name}

region service {service:#010x} bytes:{service_blob}
region records {records:#010x} poison:0x290
region stack   0xC0000000 zero:0x2000

sp 0xC0001800
gpr r3 0xC0000100
gpr r0 0

vmx on
alias on
capture gpr:r0

{stubs}
"""


def cases() -> list[dict]:
    built = [{"name": "null", "half": None, "value": 0,
              "service_blob": build_service(FINE_HALF, 0).hex()}]
    for value in sample_values():
        built.append({
            "name": f"{FINE_HALF.replace('+', 'p').replace('-', 'm')}-{value:04x}",
            "half": FINE_HALF, "value": value,
            "service_blob": build_service(FINE_HALF, value).hex(),
        })
    for half in COARSE_HALVES:
        for value in BOUNDARIES:
            built.append({
                "name": f"{half.replace('+', 'p').replace('-', 'm')}-{value:04x}",
                "half": half, "value": value,
                "service_blob": build_service(half, value).hex(),
            })
    return built


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    stubs = "\n".join(f"stub {address:#010x} lock, not read"
                      for address in LOCK_STUBS)
    stubs += f"\nstub {MEMSET:#010x} vectorised memset; its targets are already zero"
    for hint in HINTS:
        stubs += f"\nhint {hint}"
    manifest = []
    for case in cases():
        spec = workdir / "specs" / f"{case['name']}.spec"
        spec.write_text(SPEC.format(consumer=CONSUMER, name=case["name"],
                                    service=SERVICE,
                                    service_blob=case["service_blob"],
                                    records=RECORDS, stubs=stubs),
                        encoding="utf-8")
        out = workdir / "out" / f"{case['name']}.json"
        manifest.append(f"{spec.resolve()} {out.resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} fine={FINE_HALF} "
          f"fine_points={len(sample_values())} manifest={workdir / 'manifest'}")
    return 0


def read_record(document: dict) -> tuple[dict[int, float], int] | None:
    memory: dict[int, int] = {}
    for run in document.get("memory_writes", []):
        address = int(run["address"], 16)
        clean = run.get("after_hex_b")
        if clean is None:
            return None
        for index, value in enumerate(bytes.fromhex(clean)):
            memory[address + index] = value
    slots: dict[int, float] = {}
    for offset in range(0x0C, 0x88, 4):
        address = RECORD_0 + offset
        if all(address + n in memory for n in range(4)):
            slots[offset] = struct.unpack(
                ">f", bytes(memory[address + n] for n in range(4)))[0]
    flags = int.from_bytes(
        bytes(memory.get(RECORD_0 + 0x08 + n, 0) for n in range(4)), "big")
    return slots, flags


def check(workdir: Path, report: Path | None) -> int:
    observations: list[dict] = []
    for case in cases():
        path = workdir / "out" / f"{case['name']}.json"
        if not path.exists():
            print(f"{case['name']}: no snapshot", file=sys.stderr)
            return 1
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            print(f"{case['name']}: exit={document['exit']}", file=sys.stderr)
            return 1
        parsed = read_record(document)
        if parsed is None:
            print(f"{case['name']}: snapshot predates after_hex_b", file=sys.stderr)
            return 1
        slots, flags = parsed
        if case["half"] is None:
            continue
        slot = HALF_SLOT[case["half"]]
        observations.append({
            "half": case["half"],
            "value": case["value"],
            "slot": f"0x{slot:02X}",
            "float": slots.get(slot),
            "float_bits": (None if slot not in slots else
                           f"0x{struct.unpack('>I', struct.pack('>f', slots[slot]))[0]:08X}"),
            "flags": f"0x{flags:08X}",
        })

    # THE CANDIDATE RULE, stated so the data can refute it rather than illustrate
    # it. Three parts, and the sweep produced all three rather than confirming
    # them:
    #
    #   1. The slot is written UNCONDITIONALLY with negative zero, and only then
    #      overwritten. That is why a half of 0 leaves 0x80000000 and not
    #      0x00000000, and why cycle 1315's "below the deadzone the lane is not
    #      written" does not describe this path.
    #
    #   2. The half is SIGNED. Every sampled value at or above 0x8000 leaves the
    #      slot at negative zero, so the overwrite is gated on int16(half) > 0 --
    #      and 0x0001 already passes it. THE 0x800 DEADZONE DOES NOT GATE THIS
    #      STORE. It belongs to the other normalisation, at 0x821CB244.
    #
    #   3. It is a MULTIPLY BY A RECIPROCAL, not a divide. `LY+ = 0x0201` stores
    #      0x3C804100 where float32(513/32767) is 0x3C804101 -- one ulp apart,
    #      and reproducible only by float32(float32(v) * float32(1/32767)). A
    #      port that divides is wrong in the last bit at some inputs, which is
    #      exactly the kind of difference a replay checkpoint would catch and a
    #      screenshot would not.
    def f32(value: float) -> float:
        return struct.unpack(">f", struct.pack(">f", value))[0]

    scale = f32(1.0 / 32767.0)

    def scaled(raw: int) -> float:
        signed = raw - 0x10000 if raw >= 0x8000 else raw
        return f32(f32(float(signed)) * scale)

    def predicted(half: str, value: int) -> float:
        # THE COMPOSITION, and the `-` halves are what revealed it. Each slot is
        # fed by BOTH halves of its axis, in this order:
        #
        #     slot = -(float32(int16(neg)) * scale)          unconditional
        #     if int16(pos) > 0: slot = float32(int16(pos)) * scale
        #
        # The negative half is written first, negated, and NOT gated -- which is
        # why an idle stick reads negative zero rather than positive zero, and
        # why LX- = 0xFFFF (int16 -1) stores +1/32767 rather than nothing. The
        # positive half then overwrites, and only when strictly positive.
        #
        # Each case here drives ONE half and leaves the other at zero.
        negative = value if half.endswith("-") else 0
        positive = value if half.endswith("+") else 0
        result = -scaled(negative)
        signed_positive = positive - 0x10000 if positive >= 0x8000 else positive
        if signed_positive > 0:
            result = scaled(positive)
        return result

    agree, disagree = 0, []
    for row in observations:
        if row["float"] is None:
            disagree.append(f"{row['half']}={row['value']:#06x}: slot not written")
            continue
        want = struct.unpack(">I", struct.pack(">f", predicted(row["half"],
                                                              row["value"])))[0]
        got = int(row["float_bits"], 16)
        if want == got:
            agree += 1
        else:
            disagree.append(f"{row['half']}={row['value']:#06x}: "
                            f"slot {row['float_bits']} ({row['float']:g}), "
                            f"the rule predicts 0x{want:08X}")

    print(f"observations={len(observations)} match_rule={agree} "
          f"differ={len(disagree)}")
    for line in disagree[:24]:
        print(f"  {line}")
    if len(disagree) > 24:
        print(f"  ... and {len(disagree) - 24} more")

    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps({
            "schema": "ac6.retail-input-axis-sweep.v1",
            "statement": "each axis half driven through 0x821CAA50 on a built "
                         "NU::Input service, and the float slot it fills read from "
                         "the 0x00 poison pass",
            "consumer": f"0x{CONSUMER:08X}",
            "sampling": {
                "fine_half": FINE_HALF,
                "fine_points": len(sample_values()),
                "coarse_halves": COARSE_HALVES,
                "coarse_points": len(BOUNDARIES),
                "domain": 65536,
                "note": "sampled, not exhaustive: one case is about 0.23 s of "
                        "emulation and the full domain would be four hours per "
                        "half. Boundaries are included by construction, never by "
                        "a decimation stride.",
            },
            "rule": "slot = -0.0 unconditionally, then overwritten with "
                    "float32(float32(half) * float32(1/32767)) -- negated for a "
                    "`-` half -- when int16(half) > 0. Multiply, not divide: they "
                    "differ by one ulp at some inputs.",
            "observations": observations,
        }, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {report}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return emit(arguments.workdir) if arguments.emit else check(arguments.workdir,
                                                               arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
