#!/usr/bin/env python3
"""Measure the general micro-execution harness against the specialised one.

``scripts/MicroExecuteScenarioParser.java`` produced the 138 committed
``analysis/microexec/**/*.ppc.json`` snapshots, and ten native ``*Bin`` readers
are checked against their digests. ``scripts/MicroExecuteFunction.java``
generalises that harness so a gameplay function can be micro-executed too:
named regions instead of three fixed bases, float arguments, parameterised call
interception, register capture.

A generalisation that changes an answer is not a generalisation. This tool
regenerates every committed case through the new harness and requires the
**semantic payload** - everything ``tools/compare_ac6_function_snapshots.py``
compares, which is `exit`, `registers`, `calls` and `memory_writes` - to be
identical. Provenance is deliberately excluded and deliberately differs: the
general harness describes named regions where the specialised one named a
payload, a record and a buffer.

``--emit`` writes the specs and a batch manifest; run the harness on the
manifest; then ``--check`` compares. Two phases because the middle one is a
Ghidra headless invocation, which does not belong inside a Python tool.

    python3 tools/audit_microexec_harness_calibration.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_microexec_harness_calibration.py --check --workdir W
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# The specialised harness's fixed layout, which every committed case used.
PAYLOAD_BASE = 0xB0000000
RECORD_BASE = 0xB4000000
BUFFER_BASE = 0xB5000000
RECORD_BYTES = 0x100
BUFFER_BYTES = 0x8000
STACK_BASE = 0xC0000000
STACK_BYTES = 0x1000
STACK_POINTER = 0xC0000E00  # STACK_TOP - 0x200, as MicroExecuteScenarioParser sets it
ERROR_PRINTER = 0x823828B8

# Excluded from the comparison, and named here rather than in a comment so the
# exclusion is auditable.
IGNORED = {"schema", "identity", "provenance", "notes"}

# AND ONE MORE, EXCLUDED CONDITIONALLY -- which is the point, because an
# unconditional exclusion here would hide a real regression.
#
# `region_dumps` is what the `dump` directive produces. The specialised harness
# had no such directive and its snapshots have no such key; the general harness
# emits the key ALWAYS, as `[]` when no spec asked for a dump. None of these 138
# specs asks, so the field is empty in every candidate and absent in every
# reference, and that difference is not semantic -- it is the same shape cycle
# 1321 handled for `after_hex_b`: a field the old harness could not produce.
#
# So it is dropped ONLY when empty. A calibration case that ever produced a
# non-empty dump would mean its spec changed, and that must fail rather than be
# normalised away.
#
# THIS HAD BEEN FAILING FOR 87 COMMITS. `region_dumps` arrived with the `dump`
# directive at f980b88a and the calibration was last run six commits before
# that, so every run since has reported 0 of 138 while CLAUDE.md and the plan
# both cite 138/138. Nothing was wrong with the harness. Cycle 1413 found the
# discrepancy while checking that its own two overrides had not broken anything,
# and the control that exonerated them -- reverting the harness to HEAD and
# getting the same 0 of 138 -- is also what proved this was old.
CONDITIONALLY_IGNORED_WHEN_EMPTY = ("region_dumps",)

SPEC = """\
# Generated by tools/audit_microexec_harness_calibration.py --emit.
# Reproduces {source} through the parameterised harness.

function {function}
case {case}

region payload {payload_base:#010x} file:{payload}
region record  {record_base:#010x} poison:{record_bytes:#x}
region buffer  {buffer_base:#010x} poison:{buffer_bytes:#x}
region stack   {stack_base:#010x} zero:{stack_bytes:#x}

sp  {stack_pointer:#010x}
gpr r3 record
gpr r4 payload+{node:#x}
gpr r5 buffer

stub {error_printer:#010x} error printer
"""


def committed_cases(root: Path) -> list[tuple[Path, dict]]:
    """Every snapshot the specialised harness produced, in a stable order."""
    cases = []
    for path in sorted(root.rglob("*.ppc.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        provenance = document.get("provenance", {})
        # The general harness's own output carries `regions`, not the three
        # fixed bases; skipping it keeps a workdir inside the tree harmless.
        if "payload_base" not in provenance:
            continue
        if document.get("identity", {}).get("implementation") != "ppc-pcode":
            continue
        cases.append((path, document))
    return cases


def node_offset(case: str) -> int:
    marker = "@node+"
    if marker not in case:
        raise SystemExit(f"unreadable case label: {case!r}")
    return int(case.split(marker, 1)[1], 16)


def emit(root: Path, workdir: Path, payload: Path) -> int:
    cases = committed_cases(root)
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for path, document in cases:
        identity = document["identity"]
        provenance = document["provenance"]
        for name, expected in (("payload_base", PAYLOAD_BASE),
                               ("record_base", RECORD_BASE),
                               ("buffer_base", BUFFER_BASE)):
            if int(provenance[name], 16) != expected:
                raise SystemExit(f"{path}: {name} is {provenance[name]}, not {expected:#x}")
        stem = path.name[: -len(".ppc.json")]
        # Batch directories reuse stems across classes; the parent keeps them apart.
        key = f"{path.parent.name}-{stem}" if path.parent != root else stem
        spec_path = workdir / "specs" / f"{key}.spec"
        out_path = workdir / "out" / f"{key}.ppc.json"
        spec_path.write_text(SPEC.format(
            source=path.as_posix(),
            function=identity["function"],
            case=identity["case"],
            payload=payload.as_posix(),
            payload_base=PAYLOAD_BASE,
            record_base=RECORD_BASE,
            buffer_base=BUFFER_BASE,
            stack_base=STACK_BASE,
            record_bytes=RECORD_BYTES,
            buffer_bytes=BUFFER_BYTES,
            stack_bytes=STACK_BYTES,
            stack_pointer=STACK_POINTER,
            node=node_offset(identity["case"]),
            error_printer=ERROR_PRINTER,
        ), encoding="utf-8")
        manifest.append(f"{spec_path.resolve()} {out_path.resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted specs={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


# THE COMPARISON IS ON THE SEMANTIC TRIPLE OF EACH WRITE RUN, NOT ON THE WHOLE
# RECORD, and cycle 1321 loosened it deliberately rather than by accident.
#
# The committed snapshots came from the SPECIALISED harness, which emitted
# {address, size, after_hex}. The general harness now also emits `after_hex_b`,
# the second poison pass, because `after_hex` alone cannot describe a
# read-modify-write. A field the old harness could not produce is not a semantic
# difference, and comparing whole dicts made all 138 cases fail on it.
#
# What is NOT loosened: address, size and after_hex are still compared exactly,
# run for run, in order. Those are what the digest is defined on and what a
# regression in the harness would move. A run that gained or lost bytes, moved,
# or changed a single byte of content still fails here.
SEMANTIC_KEYS = ("address", "size", "after_hex")


def normalise(document: dict) -> dict:
    trimmed = {k: v for k, v in document.items() if k not in IGNORED}
    for key in CONDITIONALLY_IGNORED_WHEN_EMPTY:
        if key in trimmed and not trimmed[key]:
            del trimmed[key]
    if "memory_writes" in trimmed:
        trimmed["memory_writes"] = [
            {k: run[k] for k in SEMANTIC_KEYS if k in run}
            for run in trimmed["memory_writes"]
        ]
    return trimmed


def check(root: Path, workdir: Path) -> int:
    cases = committed_cases(root)
    equal = 0
    failures: list[str] = []
    for path, reference in cases:
        stem = path.name[: -len(".ppc.json")]
        key = f"{path.parent.name}-{stem}" if path.parent != root else stem
        candidate_path = workdir / "out" / f"{key}.ppc.json"
        if not candidate_path.exists():
            failures.append(f"{key}: the harness produced no snapshot")
            continue
        candidate = json.loads(candidate_path.read_text(encoding="utf-8"))
        if candidate.get("identity", {}).get("case") != reference["identity"]["case"]:
            failures.append(f"{key}: case label differs")
            continue
        left = normalise(reference)
        right = normalise(candidate)
        if left == right:
            equal += 1
            continue
        differing = sorted(k for k in set(left) | set(right) if left.get(k) != right.get(k))
        failures.append(f"{key}: differs in {differing}")

    print(f"cases={len(cases)} equal={equal} failures={len(failures)}")
    for failure in failures[:20]:
        print(f"  {failure}", file=sys.stderr)
    if failures:
        print("microexec_harness_calibration=fail", file=sys.stderr)
        return 1
    print("microexec_harness_calibration=pass")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=Path("analysis/microexec"))
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--payload", type=Path, default=Path(
        "reports/logs/cycle-739-pac-mission-gate/fhm/idx_0009/000_00_00_00_10.bin"))
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)

    if arguments.emit:
        if not arguments.payload.exists():
            raise SystemExit(f"payload not found: {arguments.payload}")
        return emit(arguments.root, arguments.workdir, arguments.payload.resolve())
    return check(arguments.root, arguments.workdir)


if __name__ == "__main__":
    raise SystemExit(main())
