#!/usr/bin/env python3
"""Exercise the `dump` directive, which nothing ran.

Cycle 1459 counted three directives exercised nowhere -- `dump`, `hint`, `vmx` --
and `dump` is the one already implicated in this campaign's longest silent
failure: the comparator that reported **0 of 138 for eighty-seven commits** was
counting an absent `region_dumps` key as a semantic difference. The directive
that produced the key had, and until now still had, no caller.

WHAT IT CHECKS, and it needs no port and no second harness. `dump NAME` emits a
region's final bytes for **both poison passes** -- `after_hex` at `0xCD` and
`after_hex_b` at `0x00` -- beside the `memory_writes` the same run derives from
comparing them. Those two outputs must agree, and three ways:

  1. **every reported write appears in the dump.** A `memory_writes` range says
     bytes changed at an offset; `after_hex` must carry those bytes there.
  2. **every byte outside a reported write is still poison** -- `0xCD` in pass A
     and `0x00` in pass B. A byte that moved without being reported is a write
     the detector missed.
  3. **the two passes agree wherever a byte was written.** This is the reason
     the harness emits both, in its own words: so a reader can see that a
     seeded region's result does not depend on the poison. It is not a
     tautology -- write detection fires when EITHER pass differs from its
     poison, so a byte copied out of uninitialised memory is reported as written
     and differs between passes. That byte is a bug in the case, and this finds
     it.

Together they say the dump and the write list are two views of one emulation. A
`dump` that emitted the wrong region, the wrong length, a stale buffer or only
one pass fails at least one of them.

    python3 tools/audit_microexec_dump_directive.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_microexec_dump_directive.py --check --workdir W

The middle step is a Ghidra pass, which is why this is two phases like the
calibration it sits beside.
"""

import argparse
import json
import os
import sys

PAYLOAD = ("reports/logs/cycle-739-pac-mission-gate/fhm/idx_0009/"
           "000_00_00_00_10.bin")

# Cases lifted from the calibration corpus's own shape, so the only thing new
# here is `dump`. Each is (name, function, case label, payload offset).
CASES = [
    ("actbin", "0x82330688", "ActBin@node+0x11b390", 0x11B390),
    ("actbin2", "0x82330688", "ActBin@node+0x15890", 0x15890),
    ("actbin3", "0x82330688", "ActBin@node+0x166650", 0x166650),
]

SPEC = """# Generated by tools/audit_microexec_dump_directive.py --emit.
# The calibration's own case shape, plus `dump` -- the directive cycle 1459
# found had no caller anywhere in the repository.

function {function}
case {case}

region payload 0xb0000000 file:{payload}
region record  0xb4000000 poison:0x100
region buffer  0xb5000000 poison:0x8000
region stack   0xc0000000 zero:0x1000

sp  0xc0000e00
gpr r3 record
gpr r4 payload+{offset:#x}
gpr r5 buffer

stub 0x823828b8 error printer

dump record
dump buffer
"""


def emit(workdir):
    os.makedirs(os.path.join(workdir, "specs"), exist_ok=True)
    os.makedirs(os.path.join(workdir, "out"), exist_ok=True)
    manifest = []
    payload = os.path.abspath(PAYLOAD)
    if not os.path.exists(payload):
        print("dump_directive=skip no payload at %s" % PAYLOAD)
        return 0
    for name, function, case, offset in CASES:
        spec_path = os.path.join(workdir, "specs", name + ".spec")
        with open(spec_path, "w") as handle:
            handle.write(SPEC.format(function=function, case=case,
                                     payload=payload, offset=offset))
        out_path = os.path.join(workdir, "out", name + ".ppc.json")
        manifest.append("%s %s" % (spec_path, out_path))
    with open(os.path.join(workdir, "manifest"), "w") as handle:
        handle.write("\n".join(manifest) + "\n")
    print("emitted specs=%d manifest=%s"
          % (len(CASES), os.path.join(workdir, "manifest")))
    return 0


def written_ranges(document):
    """(address, pass-A bytes, pass-B bytes) per reported write.

    A write entry names no region -- it carries `address`, `size`, `after_hex`
    and `after_hex_b` -- so the caller matches each into whichever dump covers
    its address. That the entry ALSO carries both passes is what makes the
    cross-check meaningful: the dump and the write list are produced by
    different code paths from the same two emulations.
    """
    out = []
    for entry in document.get("memory_writes", []):
        out.append((int(entry["address"], 16),
                    bytes.fromhex(entry["after_hex"]),
                    bytes.fromhex(entry["after_hex_b"])))
    return out


def check(workdir):
    failures = []
    checked = 0
    for name, _f, _c, _o in CASES:
        path = os.path.join(workdir, "out", name + ".ppc.json")
        if not os.path.exists(path):
            print("dump_directive=fail missing %s -- was the batch run?" % path)
            return 1
        document = json.load(open(path))
        dumps = document.get("region_dumps")
        if not dumps:
            failures.append("%s: no region_dumps -- the directive produced nothing"
                            % name)
            continue
        writes = written_ranges(document)
        for dump in dumps:
            checked += 1
            region = dump["name"]
            base = int(dump["base"], 16)
            a = bytes.fromhex(dump["after_hex"])
            b = bytes.fromhex(dump["after_hex_b"])
            if len(a) != dump["size"] or len(b) != dump["size"]:
                failures.append("%s/%s: dump length %d/%d against size %d"
                                % (name, region, len(a), len(b), dump["size"]))
                continue
            touched = bytearray(len(a))
            covered = 0
            for address, data_a, data_b in writes:
                offset = address - base
                if offset < 0 or offset + len(data_a) > len(a):
                    continue                    # belongs to another region
                covered += 1
                # 1. the write appears in the dump, in both passes
                if a[offset:offset + len(data_a)] != data_a:
                    failures.append("%s/%s: write at %#x is not in after_hex"
                                    % (name, region, address))
                if b[offset:offset + len(data_b)] != data_b:
                    failures.append("%s/%s: write at %#x is not in after_hex_b"
                                    % (name, region, address))
                # 3. and does not depend on the poison
                if data_a != data_b:
                    failures.append("%s/%s: write at %#x DIFFERS between poison "
                                    "passes -- uninitialised data reached it"
                                    % (name, region, address))
                for i in range(offset, offset + len(data_a)):
                    touched[i] = 1
            if covered == 0:
                failures.append("%s/%s: the dump matched no reported write at all"
                                % (name, region))
            # 2. everything else is still poison
            stray = [i for i in range(len(a))
                     if not touched[i] and (a[i] != 0xCD or b[i] != 0x00)]
            if stray:
                failures.append("%s/%s: %d byte(s) moved without being reported, "
                                "first at offset %#x"
                                % (name, region, len(stray), stray[0]))
    for line in failures:
        print("  " + line)
    print("dump_directive=%s dumps=%d failures=%d"
          % ("pass" if not failures else "fail", checked, len(failures)))
    return 0 if not failures else 1


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", required=True)
    args = parser.parse_args()
    if args.emit:
        return emit(args.workdir)
    if args.check:
        return check(args.workdir)
    parser.error("one of --emit or --check")


if __name__ == "__main__":
    sys.exit(main())
