#!/usr/bin/env python3
"""Run the flight model's two export functions and compare the whole buffer.

0x82303898 and 0x82303940 are slots 20 and 21 of the live vtable 0x8200F310 --
the boundary between the flight model and whatever consumes it. Each fills part
of a caller-supplied buffer with the model's control outputs and some raw fields.

THIS IS THE CAMPAIGN'S FIRST FULLY-LIVE COMPOSITE. Every earlier composite
stubbed something: cycle 1381 stubbed slots 31 and 32, cycle 1389 stubbed
everything but slot 30. Here NOTHING is stubbed. The synthetic vtable holds the
genuine addresses of slots 16, 17 and 18, all three run for real through real
virtual dispatches, and `calls` is asserted empty.

That is possible because all three accessors are small and scalar -- slot 16 is
two instructions -- and it is worth having because the composed result then
exercises retail_control_blend through the dispatch that actually reaches it,
rather than through a Python restatement.

WHAT IS COMPARED is the ENTIRE 128-byte buffer, not the words the exporters
write. The buffer is seeded with -1.0 everywhere, so every offset a given
exporter does NOT write is asserted to still hold -1.0. A port that zeroed the
buffer first, or wrote one word too many, fails on the untouched offsets rather
than on the written ones.

    python3 tools/audit_flight_export_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_flight_export_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

MODEL = 0xB8000000
VTABLE = 0xB9000000
OUTPUT = 0xB4000000
OUTPUT_SIZE = 0x80
SLOT20 = 0x82303898
SLOT21 = 0x82303940
ACCESSORS = {16: 0x822B65C8, 17: 0x82281E10, 18: 0x82281EA8,
             20: SLOT20, 21: SLOT21}
EPSILON = 1.52587890625e-05
SCALE17 = 0.6366198062896729
SCALE18 = 0.3183099031448364
FIELDS = {304: 0.37777779, 308: -0.633333, 312: 0.13333334, 144: 1.7000001,
          152: -2.3000001, 408: 0.26666668, 412: -0.11333334, 368: 0.9933333,
          372: 0.4066667, 376: 0.7333333, 32: 300.70001, 356: 0.13333334}
CASES = [("slot20-plain", SLOT20, 0, "slot 20 with the reset bit clear"),
         ("slot20-reset", SLOT20, 2, "slot 20 with it set, so the blends replace"),
         ("slot21-plain", SLOT21, 0, "slot 21 with the reset bit clear"),
         ("slot21-reset", SLOT21, 2, "slot 21 with it set")]


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def blend(axis, rate, stored, flags, scale):
    axis, rate, stored, scale = (f32(v) for v in (axis, rate, stored, scale))
    value = axis
    if flags & 2:
        scaled = f32(rate * scale)
        if abs(scaled) > abs(value):
            value = scaled
    elif not (abs(stored) < EPSILON):
        value = f32(stored + value)
    return -1.0 if value < -1.0 else (1.0 if value > 1.0 else value)


def expected(function, flags):
    slot16 = f32(FIELDS[308])
    slot17 = blend(FIELDS[304], FIELDS[144], FIELDS[408], flags, SCALE17)
    slot18 = blend(FIELDS[312], FIELDS[152], FIELDS[412], flags, SCALE18)
    want = {offset: -1.0 for offset in range(0, OUTPUT_SIZE, 4)}
    if function == SLOT20:
        want.update({12: slot16, 8: slot17, 16: slot18,
                     28: f32(FIELDS[376]), 20: f32(FIELDS[368]),
                     24: f32(FIELDS[372]), 32: f32(FIELDS[32]),
                     36: f32(FIELDS[356]), 52: f32(FIELDS[376])})
    else:
        want.update({44: f32(FIELDS[376]), 48: slot17, 52: slot18, 56: slot16})
    return want


SPEC = """\
# Generated by tools/audit_flight_export_microexec.py --emit.
# {why}
#
# NOTHING is stubbed: slots 16, 17 and 18 hold their genuine addresses and all
# three run for real through real virtual dispatches.

function {fn:#010x}
case export:{name}

region model {model:#010x} bytes:{model_bytes}
region vt    {vtable:#010x} bytes:{vtable_bytes}
region out   {output:#010x} bytes:{output_bytes}
region stack 0xC0000000 zero:0x2000

sp 0xC0001000
gpr r3 model
gpr r4 out
gpr r0 0
dump out
"""


def vtable_bytes() -> str:
    blob = bytearray(4 * 40)
    for index, address in ACCESSORS.items():
        struct.pack_into(">I", blob, 4 * index, address)
    return blob.hex()


def model_bytes(flags: int) -> str:
    blob = bytearray(0x600)
    struct.pack_into(">I", blob, 0, VTABLE)
    struct.pack_into(">I", blob, 332, flags)
    for offset, value in FIELDS.items():
        struct.pack_into(">f", blob, offset, f32(value))
    return blob.hex()


def output_bytes() -> str:
    blob = bytearray(OUTPUT_SIZE)
    for offset in range(0, OUTPUT_SIZE, 4):
        struct.pack_into(">f", blob, offset, -1.0)
    return blob.hex()


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for name, fn, flags, why in CASES:
        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(SPEC.format(why=why, fn=fn, name=name, model=MODEL,
                                    model_bytes=model_bytes(flags),
                                    vtable=VTABLE, vtable_bytes=vtable_bytes(),
                                    output=OUTPUT, output_bytes=output_bytes()),
                        encoding="utf-8")
        manifest.append(f"{spec.resolve()} "
                        f"{(workdir / 'out' / (name + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures, compared, lines = [], 0, []
    for name, fn, flags, why in CASES:
        path = workdir / "out" / f"{name}.json"
        if not path.exists():
            failures.append(f"{name}: no snapshot")
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            failures.append(f"{name}: exit {document['exit']}")
            continue
        if document["calls"]:
            failures.append(f"{name}: {len(document['calls'])} stubbed call(s); "
                            "this audit stubs nothing")
            continue
        dump = next(e for e in document["region_dumps"] if e["name"] == "out")
        after = bytes.fromhex(dump["after_hex"])
        if after != bytes.fromhex(dump["after_hex_b"]):
            failures.append(f"{name}: the two poison passes disagree")
            continue
        want = expected(fn, flags)
        bad = []
        for offset, value in sorted(want.items()):
            got = struct.unpack_from(">f", after, offset)[0]
            compared += 1
            if struct.pack(">f", got) != struct.pack(">f", f32(value)):
                bad.append(f"+{offset}: retail {got!r} port {value!r}")
        if bad:
            failures.append(f"{name}: " + "; ".join(bad[:4]))
        lines.append(f"{name}\t{'ok' if not bad else 'MISMATCH'}\t"
                     f"{len(want)}\t{why}")
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(
            "# 0x82303898 and 0x82303940, slots 20 and 21, micro-executed with\n"
            "# slots 16, 17 and 18 running FOR REAL and nothing stubbed, against\n"
            "# ac6::retail::export_flight_state_slot20 / _slot21.\n"
            "# The whole 128-byte buffer is compared, including every offset the\n"
            "# exporter does not write, which is seeded to -1.0.\n"
            "# case\tverdict\twords_compared\twhy the case exists\n"
            + "\n".join(lines) + "\n", encoding="utf-8")
    for problem in failures:
        print("  FAIL  " + problem)
    print(f"flight_export_microexec={'pass' if not failures else 'fail'} "
          f"cases={len(CASES)} values_compared={compared}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", required=True, type=Path)
    parser.add_argument("--report", type=Path)
    arguments = parser.parse_args()
    if arguments.emit == arguments.check:
        print("choose exactly one of --emit and --check")
        return 2
    return emit(arguments.workdir) if arguments.emit else check(
        arguments.workdir, arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
