#!/usr/bin/env python3
"""Differential for the active-slot gatherer, 0x82211B40.

`.pdata` has no row for this function, so the differential is the only check its
port has that does not depend on the listing being complete.

    r3 = the player block, whose 32 mask words start at +0x08
    r4 = the record, whose flag word is at +0x08
    r5 = the caller's active-slot word, which the function ORs into

The word at r5 is SEEDED NON-ZERO in half the cases. Retail ORs rather than
assigns, so a port that assigned would pass every zero-seeded case and fail these.

    python3 tools/audit_slot_gather_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_slot_gather_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

FUNCTION = 0x82211B40
PLAYER, RECORD, MASKWORD = 0xB8000000, 0xB9000000, 0xBA000000
PLAYER_BYTES, RECORD_BYTES = 0x200, 0xA0

# (name, record flag word, {slot: mask}, seed already in the caller's word)
CASES = [
    ("empty-flags",   0x00000000, {0: 0xFFFFFFFF, 31: 0xFFFFFFFF}, 0x00000000),
    ("empty-flags-seeded", 0x00000000, {0: 0xFFFFFFFF}, 0x0000A5A5),
    ("single",        1 << 17, {0: 1 << 17}, 0x00000000),
    ("first-and-last", 1 << 17, {0: 1 << 17, 31: 1 << 17}, 0x00000000),
    ("partial-overlap", 1 << 19, {2: (1 << 4) | (1 << 17) | (1 << 19)}, 0x00000000),
    ("no-overlap",    1 << 19, {2: (1 << 4) | (1 << 17)}, 0x00000000),
    ("seeded",        1 << 17, {3: 1 << 17}, 0x00000005),
    ("all-slots",     0xFFFFFFFF, {n: 1 << n for n in range(32)}, 0x00000000),
    ("button-bits",   (1 << 5) | (1 << 7), {1: 1 << 5, 9: 1 << 7, 20: 1 << 6}, 0x00000000),
]


def build_player(masks: dict[int, int]) -> bytes:
    blob = bytearray(PLAYER_BYTES)
    for slot, mask in masks.items():
        struct.pack_into(">I", blob, 0x08 + 4 * slot, mask)
    return bytes(blob)


def build_record(flags: int) -> bytes:
    blob = bytearray(RECORD_BYTES)
    struct.pack_into(">I", blob, 0x08, flags)
    return bytes(blob)


SPEC = """\
# Generated by tools/audit_slot_gather_microexec.py --emit.
function {function:#010x}
case slot-gather:{name}
steps 20000

region player   {player:#010x} bytes:{player_blob}
region record   {record:#010x} bytes:{record_blob}
region maskword {maskword:#010x} bytes:{seed:08x}
region stack    0xC0000000 zero:0x2000
dump maskword

sp 0xC0001800
gpr r3 {player:#010x}
gpr r4 {record:#010x}
gpr r5 {maskword:#010x}
gpr r0 0
"""


def native(flags: int, masks: dict[int, int], seed: int) -> int:
    if flags == 0:
        return seed                       # the early return ORs nothing
    gathered = 0
    for slot in range(32):
        if masks.get(slot, 0) & flags:
            gathered |= 1 << slot
    return (seed | gathered) & 0xFFFFFFFF


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for name, flags, masks, seed in CASES:
        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(SPEC.format(function=FUNCTION, name=name,
                                    player=PLAYER, player_blob=build_player(masks).hex(),
                                    record=RECORD, record_blob=build_record(flags).hex(),
                                    maskword=MASKWORD, seed=seed), encoding="utf-8")
        manifest.append(f"{spec.resolve()} {(workdir / 'out' / (name + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures: list[str] = []
    compared = 0
    for name, flags, masks, seed in CASES:
        path = workdir / "out" / f"{name}.json"
        if not path.exists():
            print(f"{name}: no snapshot", file=sys.stderr)
            return 1
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            failures.append(f"{name}: exit={document['exit']}")
            continue
        blob = bytes.fromhex(document["region_dumps"][0]["after_hex"])
        got = struct.unpack_from(">I", blob, 0)[0]
        want = native(flags, masks, seed)
        if got != want:
            failures.append(f"{name}: 0x{got:08X} want 0x{want:08X}")
        compared += 1
    print(f"cases={compared} failures={len(failures)}")
    for line in failures:
        print(f"  {line}", file=sys.stderr)
    if failures:
        print("slot_gather_microexec=fail", file=sys.stderr)
        return 1
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps({
            "schema": "ac6.slot-gather-microexec.v1",
            "statement": "0x82211B40 executed over nine cases including a non-zero "
                         "seed in the caller's word, which distinguishes the OR "
                         "retail performs from an assignment",
            "function": f"0x{FUNCTION:08X}",
            "note": ".pdata has no row for this function",
            "cases": compared, "divergences": 0,
            "case_names": [c[0] for c in CASES],
        }, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {report}")
    print("slot_gather_microexec=pass")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return emit(arguments.workdir) if arguments.emit else check(arguments.workdir,
                                                               arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
