#!/usr/bin/env python3
"""Run XMScalarSinCos (0x8209CB70) against the port, and arbitrate one instruction.

Cycle 1411 measured this routine as the only unfaithful scalar seam in the flight
chain: `std::sin`/`std::cos` differ from it at 242 of 412 values, worst absolute
error 3.20e-07, and every rotation in the chain goes through it. This ports it.

WHAT IT IS. 92 instructions, a leaf, and a Taylor series to the 23rd order
evaluated four terms at a time in the vector unit:

    q  = trunc((a + copysign(pi, a)) * float32(1/(2pi)))     round-half-away
    x  = fmaf(-(float)q, float32(2pi), a)                    fnmsubs, ONE rounding
    v  = (1, x, x^2, x^3)
    cos = dot(v*v,            (1, -1/2!, 1/4!, -1/6!))       lanes x^0..x^6
        + dot(v*v*x^8,        (1/8!, -1/10!, 1/12!, -1/14!))
        + dot(v*v*x^16,       (1/16!, -1/18!, 1/20!, -1/22!))
    sin = the same with the odd lanes and 1/1!..1/23!

The coefficients are read from 0x8204F6F0..0x8204F74F, six 16-byte vectors, and
they are exact reciprocal factorials -- not decimal literals, which is worth
saying because two constants in this campaign turned out to be seven-digit
decimals wearing a reciprocal's clothes (cycles 1374, 1386). So does
float32(1/(2pi)) at 0x82069BEC: it IS the rounded reciprocal, not `0.15915494`.

THE ONE THING THAT HAD TO BE ARBITRATED is `vmsum4fp128`. A four-lane dot product
has a summation order, the order decides the last ulp, and the ISA reference this
campaign has does not fix it. Rather than assume, eight candidates -- four
association orders crossed with fused and unfused products -- were each scored
against the micro-executed result at every argument of the sweep:

    order=LR    fused=False  exact 412/412      <- the only one
    order=LR    fused=True   exact 298/412
    order=TREE  fused=False  exact 292/412
    order=RL / REV, either   exact 223 or 188/412

One candidate reproduces every value and the next best misses 114. That is an
arbitration by cross-match, the same standard the `vpermwi128` reading was held
to, and `--arbitrate` re-runs it so the claim is reproducible rather than
recorded.

WHAT REMAINS ASSERTED, and it is not nothing. The order above is the SLEIGH
module's, executed as retail p-code with `asserted_semantics` EMPTY -- no model
of this campaign's was involved. But the module has been found broken four times,
and nothing here compares it against the console. What is established is that the
port reproduces the micro-execution exactly; that the micro-execution reproduces
the hardware is the standing assumption of the whole campaign, not a result of
this cycle.

AND IT NEEDS `alias on`. Without the register-file bridge this routine's first
output is not sine at all -- 1.0 at angle 0. That is cycle 1300's defect and
cycle 1302's fix, and cycle 1411 walked into it again.

    python3 tools/audit_scalar_sin_cos_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_scalar_sin_cos_microexec.py --check --workdir W
    python3 tools/audit_scalar_sin_cos_microexec.py --arbitrate --workdir W
"""

from __future__ import annotations

import argparse
import json
import math
import struct
from pathlib import Path

SINCOS = 0x8209CB70

PI = 3.1415927410125732            # 0x40490FDB, inserted by the rlwimi at 0x8209CBE0
TWO_PI = 6.2831854820251465        # 0x82069BF0
INV_TWO_PI = 0.15915493667125702   # 0x82069BEC -- float32(1/(2pi)), not a decimal

# 0x8204F6F0..0x8204F74F. Named by the register that loads them.
COEFFICIENTS = {
    "cos_lo": [1.0, -0.5, 0.0416666679084301, -0.0013888889225199819],
    "sin_lo": [1.0, -0.1666666716337204, 0.008333333767950535, -0.00019841270113829523],
    "cos_mid": [2.4801587642286904e-05, -2.755731998149713e-07,
                2.08767581000302e-09, -1.147074536050896e-11],
    "sin_mid": [2.7557318844628753e-06, -2.5052107943679403e-08,
                1.6059044372074283e-10, -7.647163609812713e-13],
    "cos_hi": [4.7794772561329454e-14, -1.5619206814541513e-16,
               4.110317590937049e-19, -8.896790959566848e-22],
    "sin_hi": [2.8114573589663704e-15, -8.220635078476521e-18,
               1.9572941524685808e-20, -3.868170297964731e-23],
}

SWEEP = 192
NAMED = [0.0, -0.0, PI, -PI, PI / 2, -PI / 2, PI / 4, -PI / 4, 1.0, -1.0,
         0.7853981852531433, 2.3561944961547852, 1e-7, -1e-7]

SPEC = """\
# Generated by tools/audit_scalar_sin_cos_microexec.py --emit.
# 0x8209CB70 at {angle!r}.
#
# `alias on` is REQUIRED: without the register-file bridge this routine's first
# output is 1.0 at angle 0, which is cycle 1300's defect, not a property of the
# routine.  Nothing is stubbed and nothing is asserted -- the snapshot's
# asserted_semantics is empty, so every one of the 92 instructions is retail's.

function {fn:#010x}
case sincos:{name}

region out   0xB4000000 zero:0x10
region stack 0xC0000000 zero:0x2000

alias on
sp 0xC0001000
gpr r3 out
gpr r4 0xB4000008
gpr r0 0
fpr f1 f:{angle!r}
steps 200
dump out
"""


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def bits(value: float) -> int:
    return struct.unpack(">I", struct.pack(">f", value))[0]


def angles() -> list[float]:
    return NAMED + [f32(-PI + 2.0 * PI * index / (SWEEP - 1)) for index in range(SWEEP)]


def dot4(lanes: list[float], coefficients: list[float],
         order: str = "LR", fused: bool = False) -> float:
    """vmsum4fp128, with its association order a parameter so it can be arbitrated."""
    products = ([lanes[i] * coefficients[i] for i in range(4)] if fused
                else [f32(lanes[i] * coefficients[i]) for i in range(4)])
    if order == "LR":
        return f32(f32(f32(products[0] + products[1]) + products[2]) + products[3])
    if order == "TREE":
        return f32(f32(products[0] + products[1]) + f32(products[2] + products[3]))
    if order == "RL":
        return f32(products[0] + f32(products[1] + f32(products[2] + products[3])))
    if order == "REV":
        return f32(f32(f32(products[3] + products[2]) + products[1]) + products[0])
    raise ValueError(order)


def model(angle: float, order: str = "LR", fused: bool = False) -> tuple[float, float]:
    """The port, in Python. `retail_scalar_sin_cos.cpp` is the same steps in C++."""
    a = f32(angle)
    # 0x8209CBE0: rlwimi inserts pi's bits 1..31 over the angle's, keeping its
    # sign bit -- copysign(pi, a) built out of the argument's own word.
    quotient = f32(f32(a + math.copysign(PI, a)) * INV_TWO_PI)
    # fctiwz truncates toward zero and saturates; the reachable domain keeps
    # |quotient| well inside int32, and the port carries the saturation anyway.
    whole = int(max(-2147483648.0, min(2147483647.0, quotient)))
    x = f32(math.fma(-f32(float(whole)), TWO_PI, a))  # fnmsubs: ONE rounding

    vector = [1.0, x, f32(x * x), f32(f32(x * x) * x)]
    even = [f32(v * v) for v in vector]                       # x^0, x^2, x^4, x^6
    odd = [f32(v * x) for v in even]                          # x^1, x^3, x^5, x^7
    # `vspltw v5,v13,2` splats lane 2 of the BASE vector -- x^2 -- not of the
    # squared one. Taking it from `even` gives x^4 and a step of x^10, which the
    # differential rejected at 336 of 412 values before this file was finished.
    step = f32(even[3] * vector[2])                           # x^6 * x^2 = x^8

    cos_lo = dot4(even, COEFFICIENTS["cos_lo"], order, fused)
    sin_lo = dot4(odd, COEFFICIENTS["sin_lo"], order, fused)
    even8 = [f32(v * step) for v in even]                     # x^8 .. x^14
    odd8 = [f32(v * step) for v in odd]                       # x^9 .. x^15
    even16 = [f32(v * step) for v in even8]                   # x^16 .. x^22
    odd16 = [f32(v * step) for v in odd8]                     # x^17 .. x^23
    cos_mid = dot4(even8, COEFFICIENTS["cos_mid"], order, fused)
    sin_mid = dot4(odd8, COEFFICIENTS["sin_mid"], order, fused)
    cos_hi = dot4(even16, COEFFICIENTS["cos_hi"], order, fused)
    sin_hi = dot4(odd16, COEFFICIENTS["sin_hi"], order, fused)

    # 0x8209CCB4..0x8209CCD8, and the grouping is retail's: hi+mid first, then lo.
    cosine = f32(f32(cos_hi + cos_mid) + cos_lo)
    sine = f32(f32(sin_hi + sin_mid) + sin_lo)
    return sine, cosine


def retail_values(workdir: Path) -> list[tuple[float, float, float]]:
    found = []
    for index, angle in enumerate(angles()):
        path = workdir / "out" / f"sincos-{index}.json"
        if not path.exists():
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            raise RuntimeError(f"{path} exited {document['exit']}")
        dumps = {d["name"]: d["after_hex"] for d in document["region_dumps"]}
        blob = bytes.fromhex(dumps["out"])
        found.append((angle,
                      struct.unpack_from(">f", blob, 0)[0],
                      struct.unpack_from(">f", blob, 8)[0]))
    return found


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for index, angle in enumerate(angles()):
        name = f"sincos-{index}"
        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(SPEC.format(fn=SINCOS, name=name, angle=angle), encoding="utf-8")
        manifest.append(f"{spec.resolve()} {(workdir / 'out' / (name + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def arbitrate(workdir: Path) -> int:
    """Score every candidate reading of vmsum4fp128 against the executed result."""
    found = retail_values(workdir)
    if not found:
        print("FAIL no snapshots")
        return 1
    scores = []
    for order in ("LR", "TREE", "RL", "REV"):
        for fused in (False, True):
            exact = 0
            for angle, retail_sin, retail_cos in found:
                got_sin, got_cos = model(angle, order, fused)
                exact += (bits(retail_sin) == bits(got_sin))
                exact += (bits(retail_cos) == bits(got_cos))
            scores.append((exact, order, fused))
            print(f"  order={order:<5} fused={str(fused):<5} exact {exact}/{2 * len(found)}")
    scores.sort(reverse=True)
    best, runner = scores[0], scores[1]
    total = 2 * len(found)
    if best[0] != total:
        print(f"FAIL no candidate reproduces every value; best {best[1]}/{best[2]} "
              f"at {best[0]}/{total}")
        return 1
    if runner[0] == total:
        print(f"FAIL two candidates are indistinguishable: {best[1:]} and {runner[1:]}")
        return 1
    print(f"arbitration: vmsum4fp128 is {best[1]}, products {'fused' if best[2] else 'rounded'}"
          f" -- {best[0]}/{total}, next best {runner[0]}/{total}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    found = retail_values(workdir)
    lines, failures = [], 0
    for angle, retail_sin, retail_cos in found:
        got_sin, got_cos = model(angle)
        for label, retail, port in (("sin", retail_sin, got_sin),
                                    ("cos", retail_cos, got_cos)):
            same = bits(retail) == bits(port)
            if not same:
                failures += 1
                print(f"FAIL {label} at {angle!r}: retail={retail!r} port={port!r}")
            lines.append(f"{angle!r}\t{label}\t{retail!r}\t{port!r}\t"
                         f"{'ok' if same else 'FAIL'}")
    print(f"cases={len(found)} values={2 * len(found)} failures={failures}")
    if report:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text("angle\twhich\tretail\tport\tverdict\n" + "\n".join(lines) + "\n",
                          encoding="utf-8")
        print(f"wrote {report}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--arbitrate", action="store_true")
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    if args.emit:
        return emit(args.workdir)
    if args.arbitrate:
        return arbitrate(args.workdir)
    if args.check:
        return check(args.workdir, args.report)
    parser.error("one of --emit, --check or --arbitrate")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
