#!/usr/bin/env python3
"""Run the flight model's three command setters against the port.

0x82281608, 0x822816C0 and 0x82281778 are slots 12, 13 and 14 of the base
vtable, inherited unchanged by every branch. Cycle 1388 established that the
live model's slot 30 reads its commands from [+36], [+40] and [+44]; these three
are the ONLY members of the flight-model family that write them. So this is how
the game flies the aeroplane, and a native session drives the contracted chain
through these and nothing else.

FOUR THINGS ARE COMPARED per case, which is why the count is 4x the cases:
the return code in r3 (retail returns 0 for changed and 1 for unchanged), the
accumulator, the target field, and the FLAG BYTE. The flag is a byte and the
rest are floats; a port that stored the target without the flag, or the flag
without the increment, fails here and nowhere else.

    python3 tools/audit_flight_command_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_flight_command_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

PI = 3.1415927410125732
MINUS_PI = -3.1415927410125732
TWO_PI = 6.2831854820251465
DEGREE = 0.01745329238474369
SEED_ACCUMULATOR = 5.0
SEED_TARGET = -99.0
INCREMENT = 1.0

# slot -> (function, current, target, flag, accumulator)
SLOTS = {
    "slot12": (0x82281608, 16, 60, 56, 36),
    "slot13": (0x822816C0, 20, 68, 64, 44),
    "slot14": (0x82281778, 24, 76, 72, 40),
}
CASES = [
    ("unchanged", 0.5, 0.5 + DEGREE * 0.5, "half a degree: discarded, increment and all"),
    ("changed", 0.5, 0.5 + DEGREE * 2.0, "two degrees: taken"),
    ("boundary", 0.5, 0.5 + DEGREE, "exactly one degree -- the comparison is strict"),
    ("wrap-low", 0.0, -PI - 1.0, "below -pi wraps up once"),
    ("wrap-high", 0.0, PI + 1.0, "above +pi wraps down once"),
    ("far", 0.0, PI + 3.0 * TWO_PI, "three turns out stays out: one step, not a modulo"),
    ("pi-positive", 0.5, PI, "exactly pi takes the sign of the current angle"),
    ("pi-negative", -0.5, PI, "and flips for a negative one"),
    ("pi-negzero", -0.0, PI, "NEGATIVE ZERO takes the positive branch -- fsel"),
    ("mantissas", 0.37777779, 1.7000001, "full mantissas"),
]


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def port(current: float, target: float):
    current, target = f32(current), f32(target)
    if target < MINUS_PI:
        target = f32(target + TWO_PI)
    elif target > PI:
        target = f32(target - TWO_PI)
    if abs(target) != PI:
        changed = abs(f32(current - target)) > DEGREE
    else:
        target = PI if current >= 0.0 else MINUS_PI
        changed = abs(f32(abs(current) - PI)) > DEGREE
    return changed, target


SPEC = """\
# Generated by tools/audit_flight_command_microexec.py --emit.
# {slot}: {why}

function {fn:#010x}
case cmd:{name}

region model 0xb8000000 bytes:{model_bytes}
region stack 0xC0000000 zero:0x2000

sp 0xC0001000
gpr r3 model
gpr r0 0
fpr f1 f:{increment!r}
fpr f2 f:{target!r}
capture gpr:r3
dump model
"""


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for slot, (fn, cur, tgt, _flag, acc) in SLOTS.items():
        for name, current, target, why in CASES:
            blob = bytearray(0x600)
            struct.pack_into(">f", blob, cur, f32(current))
            struct.pack_into(">f", blob, acc, f32(SEED_ACCUMULATOR))
            struct.pack_into(">f", blob, tgt, f32(SEED_TARGET))
            full = f"{slot}-{name}"
            spec = workdir / "specs" / f"{full}.spec"
            spec.write_text(SPEC.format(slot=slot, why=why, fn=fn, name=full,
                                        model_bytes=blob.hex(),
                                        increment=f32(INCREMENT),
                                        target=f32(target)), encoding="utf-8")
            manifest.append(f"{spec.resolve()} "
                            f"{(workdir / 'out' / (full + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures, compared, lines = [], 0, []
    for slot, (fn, cur, tgt, flag, acc) in SLOTS.items():
        for name, current, target, why in CASES:
            full = f"{slot}-{name}"
            path = workdir / "out" / f"{full}.json"
            if not path.exists():
                failures.append(f"{full}: no snapshot")
                continue
            document = json.loads(path.read_text(encoding="utf-8"))
            if document["exit"]["kind"] != "return":
                failures.append(f"{full}: exit {document['exit']}")
                continue
            after = bytes.fromhex(next(
                e for e in document["region_dumps"] if e["name"] == "model")["after_hex"])
            code = int(document["registers"]["r3"], 16)
            changed, want_target = port(current, target)
            want_code = 0 if changed else 1
            want_acc = f32(SEED_ACCUMULATOR + INCREMENT) if changed \
                else f32(SEED_ACCUMULATOR)
            want_tgt = f32(want_target) if changed else f32(SEED_TARGET)
            want_flag = 1 if changed else 0
            got_acc = struct.unpack_from(">f", after, acc)[0]
            got_tgt = struct.unpack_from(">f", after, tgt)[0]
            got_flag = after[flag]
            compared += 4
            bad = []
            if code != want_code:
                bad.append(f"r3 {code} want {want_code}")
            if struct.pack(">f", got_acc) != struct.pack(">f", want_acc):
                bad.append(f"+{acc} {got_acc!r} want {want_acc!r}")
            if struct.pack(">f", got_tgt) != struct.pack(">f", want_tgt):
                bad.append(f"+{tgt} {got_tgt!r} want {want_tgt!r}")
            if got_flag != want_flag:
                bad.append(f"+{flag} byte {got_flag} want {want_flag}")
            if bad:
                failures.append(f"{full}: " + "; ".join(bad))
            lines.append(f"{full}\t{'ok' if not bad else 'MISMATCH'}\t{code}\t"
                         f"{got_acc!r}\t{got_tgt!r}\t{got_flag}\t{why}")
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(
            "# 0x82281608, 0x822816C0 and 0x82281778 -- slots 12, 13, 14, the\n"
            "# flight model's command input API -- micro-executed against\n"
            "# ac6::retail::set_flight_command. Four things per case: the return\n"
            "# code, the accumulator, the target field and the FLAG BYTE.\n"
            "# case\tverdict\tr3\taccumulator\ttarget\tflag\twhy the case exists\n"
            + "\n".join(lines) + "\n", encoding="utf-8")
    for problem in failures:
        print("  FAIL  " + problem)
    print(f"flight_command_microexec={'pass' if not failures else 'fail'} "
          f"cases={len(lines)} values_compared={compared}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", required=True, type=Path)
    parser.add_argument("--report", type=Path)
    arguments = parser.parse_args()
    if arguments.emit == arguments.check:
        print("choose exactly one of --emit and --check")
        return 2
    return emit(arguments.workdir) if arguments.emit else check(
        arguments.workdir, arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
