#!/usr/bin/env python3
"""Run the LIVE flight model's step and compare the composed result.

0x82306A38 is slot 15 of the vtable 0x8200F310 -- the step that actually runs
every frame, cycle 1379 having shown that this branch overrides the base class's
slot 11 with the empty `blr`, and cycle 1384 that this branch is the one the
entity drives.

This is a COMPOSITE differential, the second in the campaign after cycle 1381's.
It runs the step with the REAL slot 30 (0x82303E68, contracted) reached through a
REAL virtual dispatch over a synthetic vtable holding genuine addresses, stubs
everything else, and compares:

  - the two decays at [+408] and [+412] against apply_live_step_decays;
  - the STUBBED-CALL COUNT, which differs per flag combination and is therefore
    the evidence that each bit selects the branch it is claimed to select.

BIT 7 DOES TWO JOBS, and finding that out is what the first run was for. In the
step it skips the three attitude virtuals; in slot 30 it is ALSO the bypass that
dispatches slot 38. A vtable without slot 38 filled faults at 34 steps, inside
slot 30, on a flag the step was supposed to be handling. One bit, two uses, two
different functions -- and no amount of reading 0x82306A38 would have shown it.

    python3 tools/audit_live_flight_step_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_live_flight_step_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path

STEP_FN = 0x82306A38
MODEL = 0xB8000000
VTABLE = 0xB9000000
POSITION = 0xB4000000
SLOT30 = 0x82303E68
SLOTS = {31: 0x823042D0, 32: 0x82306038, 33: 0x82282C50,
         38: 0x82282C50, 39: 0x82305690}
DIRECT = (0x82283168, 0x822831E8, 0x82304AB8, 0x82282938,
          0x82281C18, 0x82282E20, 0x82283480, 0x82326FE8)

RESET_BIT = 1 << 1
EPSILON = 1.52587890625e-05
RATE = 3.0

# (name, flags, expected stubbed calls, why)
CASES = [
    ("plain", 0x00, 10, "no flags: every virtual and every direct call runs"),
    ("skip-attitude", 0x80, 8, "bit 7 skips slots 31, 32 and 39 -- and is ALSO "
     "slot 30's bypass, which dispatches slot 38"),
    ("slot39", 0x40, 9, "bit 6 substitutes slot 39 for slot 31 and drops 0x82304AB8"),
    ("reset", 0x02, 11, "bit 1 substitutes slot 33 for the two decays"),
    ("skip-and-reset", 0x82, 9, "both, which is neither branch alone"),
]


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def fmaf(a: float, b: float, c: float) -> float:
    return f32(math.fma(a, b, c))


def expected(at408: float, at412: float, flags: int, step: float):
    if flags & RESET_BIT:
        return f32(at408), f32(at412)

    def once(value):
        value = f32(value)
        if abs(value) < EPSILON:
            return value
        return fmaf(f32(-value * f32(step)), RATE, value)

    return once(at408), once(at412)


SEED = ((408, 0.5), (412, -0.25), (360, 0.5), (364, 0.25), (368, 0.5),
        (372, 0.5), (304, 0.5), (308, -0.5), (312, 0.25), (1352, 0.25),
        (1356, 0.25), (48, 1.0), (52, 1.0), (404, 0.25), (952, 3.0),
        (956, 3.0), (36, 0.7), (40, -0.7), (44, 1.0), (32, 300.0))
STEP = 0.016666668


def vtable_bytes() -> str:
    blob = bytearray(4 * 40)
    struct.pack_into(">I", blob, 4 * 30, SLOT30)
    for index, address in SLOTS.items():
        struct.pack_into(">I", blob, 4 * index, address)
    return blob.hex()


def model_bytes(flags: int) -> str:
    blob = bytearray(0x600)
    struct.pack_into(">I", blob, 0, VTABLE)
    struct.pack_into(">I", blob, 332, flags)
    for offset, value in SEED:
        struct.pack_into(">f", blob, offset, f32(value))
    blob[1224] = 1
    for index, value in enumerate((4.0, 3.0, 5.0)):
        struct.pack_into(">f", blob, 576 + 4 * index, f32(value))
    for index, value in enumerate((2.0, 1.5, 2.5)):
        struct.pack_into(">f", blob, 592 + 4 * index, f32(value))
    return blob.hex()


SPEC = """\
# Generated by tools/audit_live_flight_step_microexec.py --emit.
# {why}
#
# Slot 30 runs FOR REAL; every other callee is stubbed at its genuine address,
# so the dispatch under test is the real one even where the callee is not.

function {step_fn:#010x}
case live-step:{name}

region model {model:#010x} bytes:{model_bytes}
region vt    {vtable:#010x} bytes:{vtable_bytes}
region pos   {position:#010x} zero:0x100
region stack 0xC0000000 zero:0x4000

sp 0xC0002000
gpr r3 model
gpr r5 pos
gpr r0 0
fpr f1 f:{step!r}
{stubs}
dump model
"""


def stub_lines() -> str:
    targets = sorted(set(list(SLOTS.values()) + list(DIRECT)))
    return "\n".join(f"stub {a:#010x} contracted elsewhere or unread" for a in targets)


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for name, flags, _, why in CASES:
        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(SPEC.format(
            why=why, step_fn=STEP_FN, name=name, model=MODEL,
            model_bytes=model_bytes(flags), vtable=VTABLE,
            vtable_bytes=vtable_bytes(), position=POSITION,
            step=f32(STEP), stubs=stub_lines()), encoding="utf-8")
        manifest.append(f"{spec.resolve()} "
                        f"{(workdir / 'out' / (name + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures, compared, lines = [], 0, []
    for name, flags, wanted_calls, why in CASES:
        path = workdir / "out" / f"{name}.json"
        if not path.exists():
            failures.append(f"{name}: no snapshot")
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            failures.append(f"{name}: exit {document['exit']}")
            continue
        if document["provenance"]["callee_entries"] != 1:
            failures.append(f"{name}: entered "
                            f"{document['provenance']['callee_entries']} callee(s); "
                            "exactly one -- slot 30 -- should run for real")
            continue
        if len(document["calls"]) != wanted_calls:
            failures.append(f"{name}: {len(document['calls'])} stubbed call(s), "
                            f"expected {wanted_calls}")
            continue
        dump = next(e for e in document["region_dumps"] if e["name"] == "model")
        after = bytes.fromhex(dump["after_hex"])
        if after != bytes.fromhex(dump["after_hex_b"]):
            failures.append(f"{name}: the two poison passes disagree")
            continue
        want408, want412 = expected(0.5, -0.25, flags, STEP)
        got408 = struct.unpack_from(">f", after, 408)[0]
        got412 = struct.unpack_from(">f", after, 412)[0]
        compared += 2
        bad = []
        for label, got, want in (("+408", got408, want408),
                                 ("+412", got412, want412)):
            if struct.pack(">f", got) != struct.pack(">f", want):
                bad.append(f"{label}: retail {got!r} port {want!r}")
        if bad:
            failures.append(f"{name}: " + "; ".join(bad))
        lines.append(f"{name}\t{'ok' if not bad else 'MISMATCH'}\t{got408!r}\t"
                     f"{got412!r}\t{len(document['calls'])}\t{why}")
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(
            "# 0x82306A38 (slot 15, the LIVE flight model's step) micro-executed\n"
            "# with the real slot 30 reached through a real virtual dispatch,\n"
            "# against ac6::retail::apply_live_step_decays. The stubbed-call\n"
            "# count is part of the comparison: it differs per flag combination.\n"
            "# case\tverdict\t+408\t+412\tstubbed_calls\twhy the case exists\n"
            + "\n".join(lines) + "\n", encoding="utf-8")
    for problem in failures:
        print("  FAIL  " + problem)
    print(f"live_flight_step_microexec={'pass' if not failures else 'fail'} "
          f"cases={len(CASES)} values_compared={compared}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", required=True, type=Path)
    parser.add_argument("--report", type=Path)
    arguments = parser.parse_args()
    if arguments.emit == arguments.check:
        print("choose exactly one of --emit and --check")
        return 2
    return emit(arguments.workdir) if arguments.emit else check(
        arguments.workdir, arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
