#!/usr/bin/env python3
"""Run the rate servo 0x822831E8 and compare it against the port.

It is a DIRECT call from the live flight model's step 0x82306A38 (and from
0x82329968), made immediately after slot 30, and it is the first consumer of the
control state retail_live_flight_axes produces: it reads +304, +308 and +312 and
writes three rates at +144, +148 and +152.

166 instructions, no call and no vector, one object through r3 -- so it runs end
to end from its own entry with nothing stubbed and nothing capped.

    python3 tools/audit_flight_rate_servo_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_flight_rate_servo_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path

START = 0x822831E8
MODEL = 0xB8000000
RATES = (144, 148, 152)
AXES = (304, 308, 312)
LIMITS = (1248, 1252, 1256)
DRIVEN = (544, 548, 552)
CENTRED = (560, 564, 568)
EPSILON = 1.52587890625e-05
BIASES = (0.5, 0.800000011920929, 0.4000000059604645)


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def fmaf(a: float, b: float, c: float) -> float:
    return f32(math.fma(a, b, c))


def expected(state, step):
    r = {k: f32(v) for k, v in state.items()}
    step = f32(step)
    sats = []
    for index in range(3):
        limit = r[LIMITS[index]]
        magnitude = 0.0
        if not (abs(limit) < EPSILON):
            magnitude = abs(f32(r[RATES[index]] / limit))
        value = f32(magnitude + BIASES[index])
        value = 0.0 if value < 0.0 else (1.0 if value > 1.0 else value)
        sats.append(value)
    out = dict(r)
    for index in range(3):
        limit = r[LIMITS[index]]
        rate = r[RATES[index]]
        axis = r[AXES[index]]
        gap = fmaf(axis, limit, -rate)
        gain = (f32(r[DRIVEN[index]] * sats[index])
                if not (abs(axis) < EPSILON) else r[CENTRED[index]])
        value = fmaf(f32(gain * gap), step, rate)
        if value < -limit:
            value = -limit
        elif value > limit:
            value = limit
        out[RATES[index]] = value
    return out


def case(name, why, step=0.016666668, **kwargs):
    state = {}
    for group, default in ((RATES, 0.0), (AXES, 0.0), (LIMITS, 5.0),
                           (DRIVEN, 2.0), (CENTRED, 3.0)):
        for field in group:
            state[field] = default
    for key, value in kwargs.items():
        state[int(key[1:])] = value
    return {"name": name, "why": why, "step": step, "state": state}


CASES = [
    case("idle", "everything centred and at rest"),
    case("driven", "all three driven, so all three gains are scaled",
         f304=1.0, f308=1.0, f312=1.0, f144=2.0, f148=2.0, f152=2.0),
    case("centred-with-rate", "centred axes use the UNSCALED gain",
         f144=1.0, f148=1.0, f152=1.0),
    case("saturation-clamped", "|rate/limit| = 1 plus the bias exceeds 1",
         f304=1.0, f144=5.0),
    case("degenerate-limit", "|limit| < 2^-16 makes the magnitude zero",
         f304=1.0, f144=0.25, f1248=1.0e-6),
    case("rate-clamped", "a huge step drives both signs onto the limits",
         f304=1.0, f308=-1.0, step=1000.0),
    case("axis-isolation", "the first axis must not reach the other two",
         f304=1.0),
    case("distinct-biases", "equal inputs on all three must give three answers",
         f304=1.0, f308=1.0, f312=1.0, f144=2.0, f148=2.0, f152=2.0,
         f1248=5.0, f1252=5.0, f1256=5.0),
    case("full-mantissas", "long binary expansions everywhere",
         f304=0.37777779, f308=-0.633333, f312=0.13333334,
         f144=1.7000001, f148=-2.3000001, f152=0.9933333,
         f1248=5.3000002, f1252=1.7000001, f1256=4.3000002,
         f544=2.3000001, f548=1.7000001, f552=3.7000001,
         f560=3.3000002, f564=2.7000001, f568=1.3000001),
]

SPEC = """\
# Generated by tools/audit_flight_rate_servo_microexec.py --emit.
# {why}

function {start:#010x}
case rate-servo:{name}

region model {model:#010x} bytes:{model_bytes}
region stack 0xC0000000 zero:0x4000

sp 0xC0002000
gpr r3 model
gpr r5 model
gpr r0 0
fpr f1 f:{step!r}
dump model
"""


def model_bytes(entry) -> str:
    blob = bytearray(0x600)
    for field, value in entry["state"].items():
        struct.pack_into(">f", blob, field, f32(value))
    return blob.hex()


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for entry in CASES:
        spec = workdir / "specs" / f"{entry['name']}.spec"
        spec.write_text(SPEC.format(why=entry["why"], start=START,
                                    name=entry["name"], model=MODEL,
                                    model_bytes=model_bytes(entry),
                                    step=f32(entry["step"])), encoding="utf-8")
        manifest.append(f"{spec.resolve()} "
                        f"{(workdir / 'out' / (entry['name'] + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures, compared, lines = [], 0, []
    for entry in CASES:
        path = workdir / "out" / f"{entry['name']}.json"
        if not path.exists():
            failures.append(f"{entry['name']}: no snapshot")
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            failures.append(f"{entry['name']}: exit {document['exit']}")
            continue
        if document["provenance"]["callee_entries"] != 0:
            failures.append(f"{entry['name']}: entered a callee; it calls nothing")
            continue
        dump = next(e for e in document["region_dumps"] if e["name"] == "model")
        after = bytes.fromhex(dump["after_hex"])
        if after != bytes.fromhex(dump["after_hex_b"]):
            failures.append(f"{entry['name']}: the two poison passes disagree")
            continue
        want = expected(entry["state"], entry["step"])
        bad, got = [], {}
        for field in RATES:
            value = struct.unpack_from(">f", after, field)[0]
            got[field] = value
            compared += 1
            if struct.pack(">f", value) != struct.pack(">f", want[field]):
                bad.append(f"+{field}: retail {value!r} port {want[field]!r}")
        if bad:
            failures.append(f"{entry['name']}: " + "; ".join(bad))
        lines.append(f"{entry['name']}\t{'ok' if not bad else 'MISMATCH'}\t"
                     + "\t".join(repr(got[f]) for f in RATES)
                     + f"\t{entry['why']}")
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(
            "# 0x822831E8, the rate servo, micro-executed against\n"
            "# ac6::retail::update_flight_rate_servo.\n"
            "# case\tverdict\t+144\t+148\t+152\twhy the case exists\n"
            + "\n".join(lines) + "\n", encoding="utf-8")
    for problem in failures:
        print("  FAIL  " + problem)
    print(f"flight_rate_servo_microexec={'pass' if not failures else 'fail'} "
          f"cases={len(CASES)} values_compared={compared}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", required=True, type=Path)
    parser.add_argument("--report", type=Path)
    arguments = parser.parse_args()
    if arguments.emit == arguments.check:
        print("choose exactly one of --emit and --check")
        return 2
    return emit(arguments.workdir) if arguments.emit else check(
        arguments.workdir, arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
