#!/usr/bin/env python3
"""Sentinel capsules for the transform kernel: 0x822A1E80 and its three callees.

A3.1. Cycle 1325 established what 0x822A1E80 is -- 40 instructions that copy the
identity basis out of .rodata into object+0x10/+0x20/+0x30 and then call three
rotations with the angles in the order f2, f1, f3. Cycle 1326 then found that
every vpermwi128 in that closure had been running on a wrong immediate.

This re-runs the capsule with the immediate corrected, and it does NOT start from
"the answer should be the identity". The cases are chosen so the output names the
contract:

  identity-zero      0x822A1E80, all three angles zero. The function writes the
                     identity itself, so a non-identity result is a statement
                     about the callees and about nothing else.
  sentinel-zero      one callee, an ASYMMETRIC basis, angle zero. A rotation by
                     zero must return its input unchanged; a copy, a transpose, a
                     row or column permutation, a pre- or post-multiplication by
                     a basis and a partial overwrite are all distinguishable in
                     one read because no two rows and no two columns are alike.
  sentinel-<angle>   the same, at 0.25, -0.5 and 0.75 -- distinct magnitudes and
                     mixed signs, so the axis, the sign convention and the
                     composition order are readable.

The object lives in a poison region, so every byte the function writes is
detected by the union of two passes and every byte it does not write is visible
as untouched. Sixteen words are NOT printed as a matrix here; the tool reports
raw slots and lets the report do the interpreting.

    python3 tools/audit_transform_kernel_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_transform_kernel_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path

ASSEMBLER = 0x822A1E80          # seeds the identity, then calls the three below
ROTATIONS = {
    "0x820A9B30": 0x820A9B30,   # called first, with the caller's f2
    "0x820A99F8": 0x820A99F8,   # called second, with the caller's f1
    "0x82211828": 0x82211828,   # called third, with the caller's f3
}

OBJECT = 0xB8000000
OBJECT_BYTES = 0x100
# 0x822A1E80 does r31 = r3 + 0x80 and writes rows at r31+0x10/+0x20/+0x30, so a
# row of the basis sits at object+0x90/+0xA0/+0xB0 when r3 is the object base.
# The callees take r3 = r31 directly, so for them the rows are at +0x10/+0x20/+0x30.
ASSEMBLER_ROWS = (0x90, 0xA0, 0xB0)
ROTATION_ROWS = (0x10, 0x20, 0x30)

# THE ASYMMETRIC SENTINEL. Every one of the twelve words distinct, no row equal to
# any other, no column equal to any other, and no value equal to 0 or 1 -- so a
# result that looks like the input, the transpose, a permutation or a product is
# separable by inspection rather than by argument.
SENTINEL_ROWS = [
    (1.0, 2.0, 3.0, 4.0),
    (5.0, 6.0, 7.0, 8.0),
    (9.0, 10.0, 11.0, 12.0),
]
# And a translation sentinel in the 16 bytes 0x822A1E80 never writes, so a
# function that reaches them is visible.
SENTINEL_HEAD = (17.0, 29.0, 43.0, 61.0)

ANGLES = (0.0, 0.25, -0.5, 0.75)

# THE MODEL, stated so the measurement can refute it. Each callee leaves one row
# untouched and rotates the other two in their own plane:
#
#     kept row k;  a' = a*cos + s*sign*b;  b' = a*(-sign)*sin + b*cos
#
# `kept` and `sign` are NOT derived from a convention -- they are what the run
# produced, and the check below either reproduces every lane of every case or
# says which one it missed.
ROTATION_MODEL = {
    # called second, with the caller's f1; row 0 is fixed
    "0x820A99F8": {"kept": 0, "first": 1, "second": 2, "sign": +1},
    # called first, with the caller's f2; row 1 is fixed, and its sign is the
    # opposite of the other two -- which is what a consistent right-handed
    # convention does to the middle axis.
    "0x820A9B30": {"kept": 1, "first": 0, "second": 2, "sign": -1},
    # called third, with the caller's f3; row 2 is fixed
    "0x82211828": {"kept": 2, "first": 0, "second": 1, "sign": +1},
}
TOLERANCE = 2e-5


def object_blob(seed_rows: bool) -> bytes:
    blob = bytearray(OBJECT_BYTES)
    if not seed_rows:
        return bytes(blob)
    for index, value in enumerate(SENTINEL_HEAD):
        struct.pack_into(">f", blob, 0x00 + 4 * index, value)
    for row, values in enumerate(SENTINEL_ROWS):
        for index, value in enumerate(values):
            struct.pack_into(">f", blob, ROTATION_ROWS[row] + 4 * index, value)
    return bytes(blob)


SPEC = """\
# Generated by tools/audit_transform_kernel_microexec.py --emit.
# {note}

function {function:#010x}
case transform-kernel:{name}
steps 20000

# The object is a `bytes:` region because most of these cases must PRE-SEED it,
# and a region that is pre-filled cannot also carry a poison fill. So write
# detection is traded away here and `dump` reads the final bytes instead. What is
# lost is "written" versus "left alone"; what is kept is every value.
region object {object:#010x} bytes:{blob}
region stack  0xC0000000 zero:0x4000
dump object

sp 0xC0002000
gpr r3 {r3:#010x}
gpr r0 0

vmx on
alias on
{overrides}
{floats}
"""


def vpermwi_sites(path: Path) -> dict[int, int]:
    sites = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or not line:
            continue
        columns = line.split("\t")
        sites[int(columns[0], 16)] = int(columns[1], 0)
    return sites


def cases(sites: dict[int, int]) -> list[dict]:
    built = [{
        "name": "identity-zero",
        "function": ASSEMBLER,
        "r3": OBJECT,
        "rows": ASSEMBLER_ROWS,
        "seed_rows": False,
        "floats": {"f1": 0.0, "f2": 0.0, "f3": 0.0},
        "note": "0x822A1E80 with all three angles zero; it writes the identity "
                "itself, so the result is a statement about the three callees",
    }]
    for label, address in ROTATIONS.items():
        for angle in ANGLES:
            built.append({
                "name": f"sentinel-{label}-{angle:+.2f}".replace(".", "p"),
                "function": address,
                "r3": OBJECT,
                "rows": ROTATION_ROWS,
                "seed_rows": True,
                "floats": {"f1": angle},
                "note": f"{label} on the asymmetric sentinel at angle {angle}",
            })
    return built


def emit(workdir: Path, sites_path: Path) -> int:
    sites = vpermwi_sites(sites_path)
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for case in cases(sites):
        # EVERY vpermwi128 SITE IN THE IMAGE IS LISTED. Not a window around the
        # entry point -- that is what the first version did, and it produced a
        # silent wrong answer: 0x822A1E80's own 0x400 bytes contain no
        # vpermwi128, so the case ran with NO overrides at all and its three
        # callees, which are elsewhere in the image, executed on the module's
        # wrong immediate and wrong lane order. The rows came back all zeros and
        # nothing in the snapshot said why.
        #
        # An override only fires when the PC reaches its address, so listing all
        # 545 costs spec text and removes the entire class of error. The ladder
        # names it: with the override chosen over a SLEIGH patch, a forgotten
        # site is a silent error, so no spec may be scoped by hand.
        overrides = "\n".join(f"override {address:#010x} vpermwi128"
                               for address in sorted(sites))
        floats = "\n".join(f"fpr {name} f:{value}"
                           for name, value in case["floats"].items())
        spec = workdir / "specs" / f"{case['name']}.spec"
        spec.write_text(SPEC.format(
            note=case["note"], function=case["function"], name=case["name"],
            object=OBJECT, blob=object_blob(case["seed_rows"]).hex(),
            r3=case["r3"], overrides=overrides, floats=floats), encoding="utf-8")
        out = workdir / "out" / f"{case['name']}.json"
        manifest.append(f"{spec.resolve()} {out.resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    findings: list[dict] = []
    failures: list[str] = []
    for case in cases({}):
        path = workdir / "out" / f"{case['name']}.json"
        if not path.exists():
            print(f"{case['name']}: no snapshot", file=sys.stderr)
            return 1
        document = json.loads(path.read_text(encoding="utf-8"))
        dumps = {entry["name"]: entry for entry in document.get("region_dumps", [])}
        if "object" not in dumps:
            print(f"{case['name']}: no object dump; regenerate with the current "
                  "harness", file=sys.stderr)
            return 1
        blob = bytes.fromhex(dumps["object"]["after_hex"])
        other = bytes.fromhex(dumps["object"]["after_hex_b"])
        rows = []
        for offset in case["rows"]:
            rows.append([round(struct.unpack_from(">f", blob, offset + 4 * lane)[0], 6)
                         for lane in range(4)])
        head = [round(struct.unpack_from(">f", blob, 4 * lane)[0], 6) for lane in range(4)]
        row = {"case": case["name"], "exit": document["exit"]["kind"],
               "steps": document["provenance"]["steps"],
               "overrides_fired": document["provenance"]
                                  .get("asserted_semantics", {})
                                  .get("override:vpermwi128", 0),
               "poison_independent": blob == other,
               "head": head, "rows": rows}
        print(f"{case['name']:32s} exit={row['exit']:10s} steps={row['steps']:6d} "
              f"vperm={row['overrides_fired']} "
              f"{'' if row['poison_independent'] else 'POISON-DEPENDENT '}")
        for index, values in enumerate(rows):
            print(f"    row{index} {values}")
        # THE MODEL, CHECKED. A table of numbers that agrees with a rotation is
        # not a rotation until something has tried to reproduce it lane by lane.
        if case["name"].startswith("sentinel-"):
            label = case["name"].split("-")[1]
            angle = case["floats"]["f1"]
            model = ROTATION_MODEL[label]
            cosine, sine = math.cos(angle), math.sin(angle)
            worst = 0.0
            for lane in range(4):
                a = SENTINEL_ROWS[model["first"]][lane]
                b = SENTINEL_ROWS[model["second"]][lane]
                expected = {
                    model["kept"]: SENTINEL_ROWS[model["kept"]][lane],
                    model["first"]: a * cosine + model["sign"] * sine * b,
                    model["second"]: -model["sign"] * sine * a + b * cosine,
                }
                for index in range(3):
                    worst = max(worst, abs(rows[index][lane] - expected[index]))
            row["worst_deviation"] = worst
            row["matches_rotation"] = worst <= TOLERANCE
            print(f"    rotation about row {model['kept']}, sign "
                  f"{model['sign']:+d}: worst deviation {worst:.2e} "
                  f"{'OK' if row['matches_rotation'] else 'MISMATCH'}")
            if not row["matches_rotation"]:
                failures.append(case["name"])
        findings.append(row)
    if failures:
        print(f"transform_kernel=fail cases={failures}", file=sys.stderr)
        return 1
    print("transform_kernel=pass")
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps({
            "schema": "ac6.transform-kernel-microexec.v1",
            "statement": "0x822A1E80 returns the identity at zero angles, and each "
                         "of its three callees is an exact plane rotation fixing one "
                         "row -- measured with the vpermwi128 immediate decoded from "
                         "the instruction word, which is what changed",
            "model": ROTATION_MODEL,
            "tolerance": TOLERANCE,
            "cases": findings,
        }, indent=2) + "\n", encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--sites", type=Path,
                        default=Path("analysis/vmx128/vpermwi128-sites.tsv"))
    parser.add_argument("--report", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return (emit(arguments.workdir, arguments.sites) if arguments.emit
            else check(arguments.workdir, arguments.report))


if __name__ == "__main__":
    raise SystemExit(main())
