#!/usr/bin/env python3
"""Differential for the slot edge and auto-repeat bank, 0x82211988.

`.pdata` has no row for this function, so its length has no independent control
and the port rests on the recompiled corpus. A differential is therefore worth
more here than usual: it checks the behaviour without depending on the listing
being complete.

The capsule is one object, seeded and dumped:

    [obj+0xE44] active mask     [obj+0x1058] initial delay
    [obj+0xE48] previous mask   [obj+0x105C] repeat interval
    [obj+0x1060] 32 (timer, limit) pairs

and f1 is the frame's elapsed time.

    python3 tools/audit_slot_repeat_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_slot_repeat_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

FUNCTION = 0x82211988
OBJECT = 0xB8000000
OBJECT_BYTES = 0x1200
ACTIVE, PREVIOUS = 0xE44, 0xE48
NEWLY_ACTIVE, NEWLY_INACTIVE, TRIGGERED = 0xE4C, 0xE50, 0xE54
DELAY, INTERVAL, SLOTS = 0x1058, 0x105C, 0x1060

DELAY_VALUE, INTERVAL_VALUE = 0.5, 0.125

# Each case names the slot states it seeds. The interesting points are equality
# with the limit, just under it, a slot released, and a slot whose timer is far
# past -- which must fire once, not repeatedly.
CASES = [
    ("idle",            0x00000000, 0x00000000, [], 0.016),
    ("newly-active",    0x00000001, 0x00000000, [(0, 0.0, 0.5)], 0.016),
    ("held-under",      0x00000001, 0x00000001, [(0, 0.124, 0.125)], 0.0),
    ("held-equal",      0x00000001, 0x00000001, [(0, 0.125, 0.125)], 0.0),
    ("held-far-past",   0x00000001, 0x00000001, [(0, 9.0, 0.125)], 0.016),
    ("released",        0x00000000, 0x00000001, [(0, 9.0, 0.125)], 0.016),
    ("two-slots",       0x00000005, 0x00000004, [(0, 0.0, 0.5), (2, 1.0, 0.125)], 0.02),
    ("high-slot",       0x80000000, 0x00000000, [(31, 1.0, 0.125)], 0.033),
    ("all-held",        0xFFFFFFFF, 0xFFFFFFFF,
     [(n, 1.0, 0.125) for n in range(32)], 0.016),
]


def build(active: int, previous: int, seeds: list[tuple[int, float, float]]) -> bytes:
    blob = bytearray(OBJECT_BYTES)
    struct.pack_into(">I", blob, ACTIVE, active)
    struct.pack_into(">I", blob, PREVIOUS, previous)
    struct.pack_into(">f", blob, DELAY, DELAY_VALUE)
    struct.pack_into(">f", blob, INTERVAL, INTERVAL_VALUE)
    for slot, timer, limit in seeds:
        struct.pack_into(">f", blob, SLOTS + 8 * slot, timer)
        struct.pack_into(">f", blob, SLOTS + 8 * slot + 4, limit)
    return bytes(blob)


SPEC = """\
# Generated by tools/audit_slot_repeat_microexec.py --emit.
function {function:#010x}
case slot-repeat:{name}
steps 40000

region obj   {obj:#010x} bytes:{blob}
region stack 0xC0000000 zero:0x4000
dump obj

sp 0xC0002000
gpr r3 {obj:#010x}
gpr r0 0
fpr f1 f:{elapsed}
"""


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def native(active: int, previous: int, seeds: list[tuple[int, float, float]],
           elapsed: float) -> tuple[dict[str, int], dict[int, tuple[float, float]]]:
    """The port's rule, expressed a second time so a mistranscription shows."""
    elapsed = f32(elapsed)
    delay, interval = f32(DELAY_VALUE), f32(INTERVAL_VALUE)
    slots = {n: (0.0, 0.0) for n in range(32)}
    for slot, timer, limit in seeds:
        slots[slot] = (f32(timer), f32(limit))
    edges = {"newly_active": active & ~previous & 0xFFFFFFFF,
             "newly_inactive": previous & ~active & 0xFFFFFFFF,
             "triggered": active & ~previous & 0xFFFFFFFF}
    for slot in range(32):
        timer, limit = slots[slot]
        if (active >> slot) & 1:
            fired = not (timer < limit)
            if fired:
                limit, timer = interval, 0.0
                edges["triggered"] |= 1 << slot
            timer = f32(timer + elapsed)
        else:
            timer, limit = 0.0, delay
        slots[slot] = (timer, limit)
    return edges, slots


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for name, active, previous, seeds, elapsed in CASES:
        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(SPEC.format(function=FUNCTION, name=name, obj=OBJECT,
                                    blob=build(active, previous, seeds).hex(),
                                    elapsed=elapsed), encoding="utf-8")
        manifest.append(f"{spec.resolve()} {(workdir / 'out' / (name + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures: list[str] = []
    compared = 0
    for name, active, previous, seeds, elapsed in CASES:
        path = workdir / "out" / f"{name}.json"
        if not path.exists():
            print(f"{name}: no snapshot", file=sys.stderr)
            return 1
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            failures.append(f"{name}: exit={document['exit']}")
            continue
        blob = bytes.fromhex(document["region_dumps"][0]["after_hex"])
        want_edges, want_slots = native(active, previous, seeds, elapsed)
        for label, offset in (("newly_active", NEWLY_ACTIVE),
                              ("newly_inactive", NEWLY_INACTIVE),
                              ("triggered", TRIGGERED)):
            got = struct.unpack_from(">I", blob, offset)[0]
            if got != want_edges[label]:
                failures.append(f"{name}: {label} 0x{got:08X} want 0x{want_edges[label]:08X}")
        for slot in range(32):
            for index, field in enumerate(("timer", "limit")):
                got = struct.unpack_from(">I", blob, SLOTS + 8 * slot + 4 * index)[0]
                want = struct.unpack(">I", struct.pack(">f", want_slots[slot][index]))[0]
                if got != want:
                    failures.append(f"{name}: slot {slot} {field} "
                                    f"0x{got:08X} want 0x{want:08X}")
        compared += 1
    print(f"cases={compared} failures={len(failures)}")
    for line in failures[:16]:
        print(f"  {line}", file=sys.stderr)
    if failures:
        print("slot_repeat_microexec=fail", file=sys.stderr)
        return 1
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps({
            "schema": "ac6.slot-repeat-microexec.v1",
            "statement": "0x82211988 executed on a seeded object over nine cases, "
                         "all three edge words and all 32 (timer, limit) pairs "
                         "compared bit for bit -- including the timer exactly at "
                         "the limit, just under it, and a slot released",
            "function": f"0x{FUNCTION:08X}",
            "note": ".pdata has no row for this function, so the differential is "
                    "the only length-independent check the port has",
            "cases": compared, "divergences": 0,
            "case_names": [c[0] for c in CASES],
        }, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {report}")
    print("slot_repeat_microexec=pass")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return emit(arguments.workdir) if arguments.emit else check(arguments.workdir,
                                                               arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
