#!/usr/bin/env python3
"""Run 0x821CAA50 on a built input service and read what it writes.

Cycles 1315-1318 derived the consumer by reading: a flag word at record+0x08, a
parallel float array whose slot for bit b is (b + 3) * 4, four signed axis floats
at +0x4C..+0x58, a deadzone and two reciprocal scales. Every step is an
instruction, and none of it has been executed.

This executes it. The function reaches its snapshot through the service singleton
at 0x8290DE00, so the run builds that singleton, its DriverContext at +0x24, the
five driver pointers at context+0x04 and four DriverControllers -- as memory,
not as stubs, so the API path under test is the real one. Only the lock is
stubbed, because 0x823D6A7C/8C have not been read and a critical section is not
what this measures.

THE FOUR CONTROLLERS ARE MADE DISTINGUISHABLE. Each carries a different axis
pushed to a different value, so the output says by itself which controller
reached which record -- a question the reading could not settle, since the index
the API receives is a constant 1 while the loop runs 0..3.

    python3 tools/audit_input_consumer_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_input_consumer_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

CONSUMER = 0x821CAA50
SERVICE = 0x8290DE00          # cycle 1309
CONTEXT = SERVICE + 0x24
CONTROLLER_0 = CONTEXT + 0x18  # cycle 1308: four, stride 0x88
CONTROLLER_STRIDE = 0x88
CONTEXT_VTABLE = 0x820110C8
CONTROLLER_VTABLE = 0x820124F8
RECORDS = 0x826EDB98           # cycle 1313
RECORD_0 = RECORDS + 0x08
RECORD_STRIDE = 0xA0
LOCK_STUBS = (0x823D6A7C, 0x823D6A8C, 0x823D6A9C)
# 0x821F3BB0 is memset, and it is VECTORISED -- it faults on vspltisb, which this
# Ghidra language leaves without emulation semantics. Stubbing it asserts nothing:
# its two calls zero r1+0x60 and r1+0x140, both inside a region the harness has
# already filled with zeros, so the stub and the call leave identical memory.
MEMSET = 0x821F3BB0
# Pure cache hints: the architecture defines them as having no effect on program
# state, so a no-op reproduces them rather than modelling them.
HINTS = ("dataCacheBlockTouch", "dataCacheBlockTouchForStore")

# Device offsets of the eight axis halves, from the table at 0x8201250C.
HALVES = {"LX+": 0x2E, "LX-": 0x2C, "LY+": 0x28, "LY-": 0x2A,
          "RX+": 0x36, "RX-": 0x34, "RY+": 0x30, "RY-": 0x32}
# Slot each axis lands in, and its sign, from cycle 1318.
SLOTS = {"LX": 0x4C, "LY": 0x50, "RX": 0x54, "RY": 0x58}
SCALE_HALF = 1.0 / 32767.0     # float32(1/32767) at 0x82069BFC

# One distinct axis per controller, all far above any plausible deadzone.
PLAN = [
    {"axis": "LY", "half": "LY+", "value": 30000, "sign": +1},
    {"axis": "LX", "half": "LX-", "value": 25000, "sign": -1},
    {"axis": "RX", "half": "RX+", "value": 20000, "sign": +1},
    {"axis": "RY", "half": "RY-", "value": 15000, "sign": -1},
]


def build_service() -> tuple[int, bytes]:
    """The singleton, its context, five driver pointers and four controllers."""
    span = (CONTROLLER_0 + 4 * CONTROLLER_STRIDE) - SERVICE + 0x40
    blob = bytearray(span)

    def put32(address: int, value: int) -> None:
        struct.pack_into(">I", blob, address - SERVICE, value & 0xFFFFFFFF)

    def put16(address: int, value: int) -> None:
        struct.pack_into(">H", blob, address - SERVICE, value & 0xFFFF)

    put32(SERVICE + 0x00, 1)              # 0x82337E88 sets this after construction
    put32(CONTEXT + 0x00, CONTEXT_VTABLE)
    for index in range(5):
        # context+0x04 is five driver pointers, bound-checked at 5 (0x82343A30).
        # The fifth is the object at context+0x238; it is given controller 3 so a
        # read through it is visible rather than a fault.
        which = min(index, 3)
        put32(CONTEXT + 0x04 + 4 * index, CONTROLLER_0 + which * CONTROLLER_STRIDE)

    for index, plan in enumerate(PLAN):
        base = CONTROLLER_0 + index * CONTROLLER_STRIDE
        put32(base + 0x00, CONTROLLER_VTABLE)
        put32(base + 0x08, 0)             # connection state: valid
        put32(base + 0x1C, 0x1000 + index)  # current buttons, distinguishable
        put16(base + HALVES[plan["half"]], plan["value"])
    return SERVICE, bytes(blob)


SPEC = """\
# Generated by tools/audit_input_consumer_microexec.py --emit.
# 0x821CAA50 on a built NU::Input service. The four controllers carry different
# axes at different values, so the output names the index-to-record mapping.

function {consumer:#010x}
case retail-input-consumer:{name}

region service {service:#010x} bytes:{service_blob}
region records {records:#010x} poison:0x290
region stack   0xC0000000 zero:0x2000

sp 0xC0001800
gpr r3 {this:#010x}
gpr r0 0

{stubs}
"""


def cases() -> list[dict]:
    base, blob = build_service()
    return [{
        "name": "four-distinct-controllers",
        "service": base,
        "service_blob": blob.hex(),
        # `this` is the caller's object; 0x821CA908 passes its own r3 through.
        # It is read at +0x08 and +0x19/+0x1C, so it gets a slice of the stack.
        "this": 0xC0000100,
    }]


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for case in cases():
        stubs = "\n".join(f"stub {address:#010x} lock, not read"
                          for address in LOCK_STUBS)
        stubs += (f"\nstub {MEMSET:#010x} vectorised memset; its targets are "
                  "already zero in this run, so the stub is equivalent")
        for hint in HINTS:
            stubs += f"\nhint {hint}"
        spec = workdir / "specs" / f"{case['name']}.spec"
        spec.write_text(SPEC.format(consumer=CONSUMER, name=case["name"],
                                    service=case["service"],
                                    service_blob=case["service_blob"],
                                    records=RECORDS, this=case["this"],
                                    stubs=stubs), encoding="utf-8")
        out = workdir / "out" / f"{case['name']}.json"
        manifest.append(f"{spec.resolve()} {out.resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    findings: list[dict] = []
    for case in cases():
        path = workdir / "out" / f"{case['name']}.json"
        if not path.exists():
            print(f"{case['name']}: no snapshot", file=sys.stderr)
            return 1
        document = json.loads(path.read_text(encoding="utf-8"))
        memory: dict[int, int] = {}
        for run in document.get("memory_writes", []):
            address = int(run["address"], 16)
            for index, value in enumerate(bytes.fromhex(run["after_hex"])):
                memory[address + index] = value

        def word(address: int) -> int | None:
            if any(address + n not in memory for n in range(4)):
                return None
            return int.from_bytes(bytes(memory[address + n] for n in range(4)), "big")

        print(f"exit={document['exit']['kind']} steps={document['provenance']['steps']}")
        for index in range(4):
            base = RECORD_0 + index * RECORD_STRIDE
            flags = word(base + 0x08)
            row = {"record": index, "flags": None if flags is None else f"0x{flags:08X}"}
            for axis, slot in SLOTS.items():
                raw = word(base + slot)
                row[axis] = (None if raw is None
                             else round(struct.unpack(">f", raw.to_bytes(4, "big"))[0], 6))
            findings.append(row)
            print(f"  record {index} @ 0x{base:08X}  flags={row['flags']}  " +
                  "  ".join(f"{axis}={row[axis]}" for axis in SLOTS))

    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps({
            "schema": "ac6.retail-input-consumer-microexec.v1",
            "statement": "0x821CAA50 executed on a built NU::Input service, with the "
                         "four controllers carrying distinct axes so the output names "
                         "the index-to-record mapping",
            "consumer": f"0x{CONSUMER:08X}",
            "stubbed": [f"0x{address:08X}" for address in LOCK_STUBS]
                       + [f"0x{MEMSET:08X}"],
            "hint_noops": list(HINTS),
            "plan": PLAN,
            "records": findings,
        }, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {report}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return emit(arguments.workdir) if arguments.emit else check(arguments.workdir,
                                                               arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
