#!/usr/bin/env python3
"""Run retail's container header parser and getter against the port.

`0x82234C18` parses the header every FHM in the model package carries, and
`0x82234DD0` indexes the arrays it produces. Cycle 1422 established that these
two are the last unported hop between a mission's model byte and an NDXR span:

    binding.primary -> ModelDirectory.entry(id)   0x8228E9B8   ported
       -> an FHM span
          -> 0x82234C18 parses its header                      THIS
             -> 0x82234DD0 indexes sub-entry j                 THIS
                -> NdxrContainer::Open                         ported

THE DESCRIPTOR IS THE INTERFACE and it is written field by field, so the
differential compares its words rather than a return code:

    +0x00 u32  count            [header + 0]
    +0x04 u32  base             the file pointer, verbatim
    +0x08 u16  header size      from file+6, byte-swapped when the flag says so
    +0x0A u8   version          from file+4
    +0x0B u8   endian flag      from file+5
    +0x0C u32  array 0          header + 4          offsets
    +0x10 u32  array 1          array0 + count*4    lengths
    +0x18 u32  array 2          array0 + count*8
    +0x1C u32  array 3          array0 + count*12

`+0x14` is NOT written by the parser, which is why the caller zeroes the whole
struct first (0x821C176C..0x821C1790). The port leaves it alone too.

THE ENDIAN FLAG IS THE POINT OF HALF THESE CASES. When `file+5` is not 1 the
parser byte-swaps the header size, the count, and then walks all four arrays
swapping every entry IN PLACE. Every FHM in Mission 01's package carries 1, so a
port tested only against real files would never execute that path -- and cycle
1422 found this only because the parser was read rather than the file. The
swapped cases here are synthetic for exactly that reason, and the dump covers
the file region so the in-place rewrite is visible.

    python3 tools/audit_container_index_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_container_index_microexec.py --check --workdir W
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

PARSE = 0x82234C18
GETTER = 0x82234DD0

DESC = 0xB4000000
FILE = 0xB0000000
DESC_BYTES = 0x40

MDLP = ("reports/logs/cycle-739-pac-mission-gate/fhm/idx_0009/001_MDLP.mdlp")

PARSE_SPEC = """\
# Generated by tools/audit_container_index_microexec.py --emit.
# 0x82234C18 on {why}.

function {fn:#010x}
case container:{name}

region desc {desc:#010x} bytes:{desc_bytes}
region file {file:#010x} bytes:{file_bytes}
region stack 0xC0000000 zero:0x2000

sp 0xC0001000
gpr r3 desc
gpr r4 file
gpr r0 0
steps 4000
dump desc
dump file
"""

GETTER_SPEC = """\
# Generated by tools/audit_container_index_microexec.py --emit.
# 0x82234DD0 at index {index} of a {count}-entry descriptor: {why}.

function {fn:#010x}
case getter:{name}

region desc {desc:#010x} bytes:{desc_bytes}
region file {file:#010x} bytes:{file_bytes}
region stack 0xC0000000 zero:0x2000

sp 0xC0001000
gpr r3 desc
gpr r4 {index}
gpr r0 0
steps 40
capture gpr:r3
"""


def real_header(count: int = 18) -> bytes:
    """Entry 0 of Mission 01's package: version 1, endian 1, header size 0x10."""
    data = Path(MDLP).read_bytes()
    be = lambda o: struct.unpack_from(">I", data, o)[0]  # noqa: E731
    body, table = be(0x10), be(0xC)
    start = body + be(table)
    return data[start:start + 0x400]


def swap32(word: bytes) -> bytes:
    return bytes(reversed(word))


def little_endian_header(source: bytes) -> bytes:
    """The same container with every parsed field byte-reversed and flag != 1.

    Synthetic, because Mission 01 carries none -- and that is the reason to have
    it: the swap path is half of 0x82234C18 and no shipped file reaches it.
    """
    blob = bytearray(source)
    blob[5] = 0                                     # the flag that selects the swap
    size = struct.unpack_from(">H", blob, 6)[0]
    struct.pack_into(">H", blob, 6, ((size & 0xFF) << 8) | (size >> 8))
    count = struct.unpack_from(">I", blob, size)[0]
    blob[size:size + 4] = swap32(bytes(blob[size:size + 4]))
    for index in range(4 * count):
        at = size + 4 + 4 * index
        blob[at:at + 4] = swap32(bytes(blob[at:at + 4]))
    return bytes(blob)


def parse_cases() -> list[tuple[str, bytes, str]]:
    real = real_header()
    swapped = little_endian_header(real)
    truncated = bytearray(real)
    struct.pack_into(">I", truncated, 0x10, 3)      # a smaller count, same arrays
    return [
        ("real", real, "entry 0 of Mission 01's package, verbatim"),
        ("byte-swapped", swapped,
         "the same container with flag 0 -- the in-place swap path"),
        ("small-count", bytes(truncated), "count 3, so the arrays land elsewhere"),
    ]


def descriptor(count: int, base: int, table: int) -> bytes:
    blob = bytearray(DESC_BYTES)
    struct.pack_into(">I", blob, 0x00, count)
    struct.pack_into(">I", blob, 0x04, base)
    struct.pack_into(">I", blob, 0x0C, table)
    return bytes(blob)


def getter_cases() -> list[tuple[str, int, int, bytes, bytes, int | None, str]]:
    """(name, index, count, desc bytes, file bytes, expected r3, why)"""
    count = 4
    offsets = [0x100, 0x200, 0x000, 0x300]           # one deliberate ZERO
    blob = bytearray(0x400)
    for i, off in enumerate(offsets):
        struct.pack_into(">I", blob, 0x20 + 4 * i, off)
    table = FILE + 0x20
    desc = descriptor(count, FILE, table)
    return [
        ("first", 0, count, desc, bytes(blob), FILE + 0x100, "index 0"),
        ("last", 3, count, desc, bytes(blob), FILE + 0x300, "the final index"),
        ("zero-entry", 2, count, desc, bytes(blob), 0,
         "a ZERO table entry returns null, not base+0 -- 0x82234DF0"),
        ("past-end", 4, count, desc, bytes(blob), 0, "index == count is refused"),
        ("far-past", 99, count, desc, bytes(blob), 0, "and so is anything above"),
    ]


# ---------------------------------------------------------------- the port
def parse_header(blob: bytes, base: int) -> dict:
    """The port, in Python. `retail_container_index.cpp` is the same steps."""
    version = blob[4]
    endian = blob[5]
    size = struct.unpack_from(">H", blob, 6)[0]
    if endian != 1:
        size = ((size & 0xFF) << 8) | (size >> 8)
    header = size
    raw = struct.unpack_from(">I", blob, header)[0]
    table = base + header + 4
    # THE ARRAY POINTERS ARE COMPUTED FROM THE *RAW* COUNT, even on the swap
    # path. 0x82234C7C multiplies the word as loaded and 0x82234C84..0x82234C98
    # store the four pointers; only afterwards, at 0x82234CD0, does the swapped
    # count replace desc+0. So on a byte-swapped container the three array
    # pointers are computed from a count with its bytes reversed and run wildly
    # out of range -- retail's behaviour, reproduced rather than corrected.
    #
    # The differential rejected the tidy version at exactly these three fields:
    # array1 retail 0xf8000014 against a "fixed" 0xb000005c. No shipped file
    # reaches this path, so only the synthetic case could have found it.
    count = raw
    if endian != 1:
        count = struct.unpack("<I", struct.pack(">I", raw))[0]
    table_end = base + header + 4
    return {
        "count": count, "base": base, "header_size": size,
        "version": version, "endian": endian,
        "array0": table_end,
        "array1": (table_end + raw * 4) & 0xFFFFFFFF,
        "array2": (table_end + raw * 8) & 0xFFFFFFFF,
        "array3": (table_end + raw * 12) & 0xFFFFFFFF,
    }


def entry_at(desc: dict, blob: bytes, index: int) -> int:
    if index >= desc["count"]:
        return 0
    at = desc["array0"] - desc["base"] + 4 * index
    offset = struct.unpack_from(">I", blob, at)[0]
    if offset == 0:
        return 0
    return desc["base"] + offset


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for name, blob, why in parse_cases():
        spec = workdir / "specs" / f"parse-{name}.spec"
        spec.write_text(PARSE_SPEC.format(
            fn=PARSE, name=name, why=why, desc=DESC,
            desc_bytes=bytes(DESC_BYTES).hex(), file=FILE, file_bytes=blob.hex()),
            encoding="utf-8")
        manifest.append(f"{spec.resolve()} "
                        f"{(workdir / 'out' / f'parse-{name}.json').resolve()}")
    for name, index, count, desc, blob, _, why in getter_cases():
        spec = workdir / "specs" / f"getter-{name}.spec"
        spec.write_text(GETTER_SPEC.format(
            fn=GETTER, name=name, index=index, count=count, why=why, desc=DESC,
            desc_bytes=desc.hex(), file=FILE, file_bytes=blob.hex()),
            encoding="utf-8")
        manifest.append(f"{spec.resolve()} "
                        f"{(workdir / 'out' / f'getter-{name}.json').resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    lines, failures, compared = [], 0, 0

    for name, blob, _ in parse_cases():
        path = workdir / "out" / f"parse-{name}.json"
        if not path.exists():
            print(f"MISSING {path}")
            failures += 1
            continue
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        dumps = {d["name"]: d["after_hex"] for d in snapshot["region_dumps"]}
        got = bytes.fromhex(dumps["desc"])
        want = parse_header(blob, FILE)
        fields = [
            ("count", struct.unpack_from(">I", got, 0x00)[0], want["count"]),
            ("base", struct.unpack_from(">I", got, 0x04)[0], want["base"]),
            ("header_size", struct.unpack_from(">H", got, 0x08)[0], want["header_size"]),
            ("version", got[0x0A], want["version"]),
            ("endian", got[0x0B], want["endian"]),
            ("array0", struct.unpack_from(">I", got, 0x0C)[0], want["array0"]),
            ("array1", struct.unpack_from(">I", got, 0x10)[0], want["array1"]),
            ("array2", struct.unpack_from(">I", got, 0x18)[0], want["array2"]),
            ("array3", struct.unpack_from(">I", got, 0x1C)[0], want["array3"]),
        ]
        for field, actual, expected in fields:
            compared += 1
            ok = actual == expected
            if not ok:
                failures += 1
                print(f"FAIL parse-{name} {field}: retail={actual:#x} port={expected:#x}")
            lines.append(f"parse-{name}\t{field}\t{actual:#x}\t{expected:#x}\t"
                         f"{'ok' if ok else 'FAIL'}")

    for name, index, _, _, blob, expected, _ in getter_cases():
        path = workdir / "out" / f"getter-{name}.json"
        if not path.exists():
            print(f"MISSING {path}")
            failures += 1
            continue
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        actual = int(snapshot["registers"]["r3"], 16) & 0xFFFFFFFF
        compared += 1
        ok = actual == expected
        if not ok:
            failures += 1
            print(f"FAIL getter-{name}: retail={actual:#x} port={expected:#x}")
        lines.append(f"getter-{name}\tr3\t{actual:#x}\t{expected:#x}\t"
                     f"{'ok' if ok else 'FAIL'}")

    print(f"values={compared} failures={failures}")
    if report:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text("case\tfield\tretail\tport\tverdict\n" + "\n".join(lines) + "\n",
                          encoding="utf-8")
        print(f"wrote {report}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    if args.emit:
        return emit(args.workdir)
    if args.check:
        return check(args.workdir, args.report)
    parser.error("one of --emit or --check")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
