#!/usr/bin/env python3
"""Map device button bits onto record flag bits, one bit at a time, by execution.

Cycle 1320 ran 0x821CAA50 with the held-button word set to 0x1000 and found bit 5
of the record flag word set. Bit 12 in, bit 5 out: the consumer does not copy the
button word, it remaps it. Nothing in the campaign had read that mapping, and
thirteen or/stw pairs at 0x821CABE0..0x821CAC4C are where it lives.

This measures it instead. One case per device bit, that bit alone set, plus a
null control with no bit set at all -- because a flag bit that appears in the
null case did not come from the buttons and would otherwise be attributed to
whichever bit happened to be under test.

WHY PASS B IS THE ANSWER HERE, AND PASS A IS NOT. The flag word is accumulated
with lwz/or/stw, so under the 0xCD poison it reads 0xCD|mask and every mask bit
0xCD already carries -- bits 0, 2, 3, 6 and 7 of each byte -- is invisible.
Cycle 1320's "bit 5 and no other" was a claim pass A could not support, and this
file will not repeat it: `after_hex_b` is the 0x00 pass, where the byte reads the
mask itself.

That pass is also the physically right one. The frame stage 0x821CA908 clears
+0x00..+0x83 of every record before the consumer runs, so a zero-filled record
region is the consumer's real precondition and 0xCD is the artificial one.

    python3 tools/audit_input_button_map_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_input_button_map_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

# The object model is the consumer tool's, not a second copy of it: a divergence
# between two builds of the same service would be indistinguishable from a
# finding.
from audit_input_consumer_microexec import (  # noqa: E402
    CONSUMER, CONTEXT, CONTROLLER_0, CONTROLLER_STRIDE, CONTEXT_VTABLE,
    CONTROLLER_VTABLE, HINTS, LOCK_STUBS, MEMSET, RECORD_0, RECORD_STRIDE,
    RECORDS, SERVICE,
)

# Device offsets of the four button words (cycle 1310's snapshot layout).
HELD = 0x1C
PRESSED = 0x14
RELEASED = 0x18
COMPLEMENT = 0x20

# Which device word each sweep drives. `held` first because it is the one cycle
# 1320 accidentally exercised; the other two are what a game reads for edges.
SWEEPS = {"held": HELD, "pressed": PRESSED, "released": RELEASED}

# THE OPEN QUESTION FROM CYCLE 1318: record flag bits 14 and 15 exist -- they own
# float slots +0x44 and +0x48 under the (bit + 3) * 4 rule -- and none of the
# eight axis halves feeds them. That cycle guessed the triggers and wrote the
# guess down as a guess.
#
# These are the candidates, each driven to its maximum on its own. Two are the
# halfwords at device+0x38/+0x3A that cycle 1318 found between the axis halves
# and the raw thumbs and could not place; two are the trigger bytes, which sit
# beyond device+0x43 and are therefore OUTSIDE the 0x40-byte snapshot copy -- so
# if they reach a record at all, the consumer read the device directly.
FIELD_SWEEPS = [
    ("dev38", 0x38, 2, 0xFFFF),
    ("dev3a", 0x3A, 2, 0xFFFF),
    ("trigL", 0x4A, 1, 0xFF),
    ("trigR", 0x4B, 1, 0xFF),
]


def build_service(word_offset: int | None, bit: int | None,
                  field: tuple[int, int, int] | None = None) -> bytes:
    """One controller in slot 0 with a single button bit set, and nothing else.

    Slot 0 is the only slot this path reads (cycle 1320, three plans), so one
    controller is enough and four would only add ways to be wrong.
    """
    span = (CONTROLLER_0 + CONTROLLER_STRIDE) - SERVICE + 0x40
    blob = bytearray(span)

    def put32(address: int, value: int) -> None:
        struct.pack_into(">I", blob, address - SERVICE, value & 0xFFFFFFFF)

    put32(SERVICE + 0x00, 1)
    put32(CONTEXT + 0x00, CONTEXT_VTABLE)
    for index in range(5):
        put32(CONTEXT + 0x04 + 4 * index, CONTROLLER_0)
    put32(CONTROLLER_0 + 0x00, CONTROLLER_VTABLE)
    put32(CONTROLLER_0 + 0x08, 0)          # connection state: valid
    if word_offset is not None and bit is not None:
        put32(CONTROLLER_0 + word_offset, 1 << bit)
    if field is not None:
        offset, width, value = field
        struct.pack_into(">H" if width == 2 else ">B",
                         blob, CONTROLLER_0 + offset - SERVICE, value)
    return bytes(blob)


SPEC = """\
# Generated by tools/audit_input_button_map_microexec.py --emit.
# One device button bit set, everything else zero.

function {consumer:#010x}
case retail-input-buttons:{name}

region service {service:#010x} bytes:{service_blob}
region records {records:#010x} poison:0x290
region stack   0xC0000000 zero:0x2000

sp 0xC0001800
gpr r3 0xC0000100
gpr r0 0

vmx on
alias on
capture gpr:r0

{stubs}
"""


def cases() -> list[dict]:
    built = [{"name": "null", "sweep": None, "bit": None,
              "service_blob": build_service(None, None).hex()}]
    for sweep, offset in SWEEPS.items():
        for bit in range(32):
            built.append({
                "name": f"{sweep}-bit{bit:02d}",
                "sweep": sweep,
                "bit": bit,
                "service_blob": build_service(offset, bit).hex(),
            })
    for name, offset, width, value in FIELD_SWEEPS:
        built.append({
            "name": f"field-{name}",
            "sweep": f"device+0x{offset:02X}",
            "bit": None,
            "service_blob": build_service(None, None,
                                          (offset, width, value)).hex(),
        })
    return built


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    stubs = "\n".join(f"stub {address:#010x} lock, not read"
                      for address in LOCK_STUBS)
    stubs += f"\nstub {MEMSET:#010x} vectorised memset; its targets are already zero"
    for hint in HINTS:
        stubs += f"\nhint {hint}"
    manifest = []
    for case in cases():
        spec = workdir / "specs" / f"{case['name']}.spec"
        spec.write_text(SPEC.format(consumer=CONSUMER, name=case["name"],
                                    service=SERVICE,
                                    service_blob=case["service_blob"],
                                    records=RECORDS, stubs=stubs),
                        encoding="utf-8")
        out = workdir / "out" / f"{case['name']}.json"
        manifest.append(f"{spec.resolve()} {out.resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def flag_word(document: dict) -> int | None:
    """The record-0 flag word as the 0x00 pass left it -- the mask, not poison."""
    memory: dict[int, int] = {}
    for run in document.get("memory_writes", []):
        address = int(run["address"], 16)
        clean = run.get("after_hex_b")
        if clean is None:
            return None
        for index, value in enumerate(bytes.fromhex(clean)):
            memory[address + index] = value
    base = RECORD_0 + 0x08
    return int.from_bytes(bytes(memory.get(base + n, 0) for n in range(4)), "big")


def check(workdir: Path, report: Path | None) -> int:
    rows: list[dict] = []
    baseline: int | None = None
    stale = []
    for case in cases():
        path = workdir / "out" / f"{case['name']}.json"
        if not path.exists():
            print(f"{case['name']}: no snapshot", file=sys.stderr)
            return 1
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            print(f"{case['name']}: exit={document['exit']}", file=sys.stderr)
            return 1
        word = flag_word(document)
        if word is None:
            stale.append(case["name"])
            continue
        if case["name"] == "null":
            baseline = word
            print(f"null control: flag word 0x{word:08X}")
            continue
        rows.append({"sweep": case["sweep"], "bit": case["bit"], "flags": word,
                     "name": case["name"]})

    if stale:
        print(f"{len(stale)} snapshots carry no after_hex_b; regenerate them with "
              "the current harness", file=sys.stderr)
        return 1
    if baseline is None:
        print("no null control", file=sys.stderr)
        return 1

    mapping: list[dict] = []
    for row in rows:
        # What THIS bit contributed, over and above what the null run produced.
        added = row["flags"] & ~baseline
        row["added"] = added
        if added:
            mapping.append({
                "device_word": row["sweep"],
                "device_bit": row["bit"],
                "case": row["name"],
                "record_flag_bits": [b for b in range(32) if added >> b & 1],
            })

    print(f"cases={len(rows)} baseline=0x{baseline:08X} mapped={len(mapping)}")
    for entry in mapping:
        bits = ",".join(str(b) for b in entry["record_flag_bits"])
        which = ("bit --" if entry["device_bit"] is None
                 else f"bit {entry['device_bit']:2d}")
        print(f"  {entry['device_word']:13s} {which} "
              f"-> record flag bit(s) {bits}")

    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps({
            "schema": "ac6.retail-input-button-map.v1",
            "statement": "one device button bit set per run of 0x821CAA50, with a "
                         "null control, read from the 0x00 poison pass because the "
                         "flag word is accumulated with or/stw and the 0xCD pass "
                         "hides every mask bit 0xCD already carries",
            "consumer": f"0x{CONSUMER:08X}",
            "record": f"0x{RECORD_0:08X}",
            "record_stride": f"0x{RECORD_STRIDE:02X}",
            "flag_word_offset": "0x08",
            "null_control_flags": f"0x{baseline:08X}",
            "device_words": {name: f"device+0x{offset:02X}"
                             for name, offset in SWEEPS.items()},
            "mapping": mapping,
        }, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {report}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return emit(arguments.workdir) if arguments.emit else check(arguments.workdir,
                                                               arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
