#!/usr/bin/env python3
"""Run retail's input-field router against the port.

`sub_82229250` is the only function that fills all six of the entity's input
fields -- +2096, +2100, +2104, +2108, +2112 and +2116 -- the six words the five
accumulators of `retail_flight_input_apply` consume.  Cycle 1409 established
where they come from: SIX CONSECUTIVE FLOATS of the binding layer's first
output array, `[binding+3672 .. binding+3692]`, which cycle 1404 had already
found the first two of.

The routing is not fixed.  Two words select it:

  * the DEVICE MODE, read through a config chain before this block, which picks
    between a digital source for +2112/+2116 and an analog one;
  * the LAYOUT word `[0x826EDB5C]`, which when it equals 1 swaps the analog pair
    onto the hold fields and gives the axis-difference pair the digital bits.

The digital values are 1.0 or 0.0 taken from bits of `[binding+3652]`, and
WHICH BIT FEEDS WHICH FIELD DEPENDS ON THE ARM: the digital device sends bits
2 and 3 to +2112 and +2116; layout 0 sends bits 4 and 5 to +2096 and +2100;
layout 1 sends bits 5 and 4 to +2112 and +2116.  Layout 1 transposes both pairs
and reverses each.

WHAT THIS DIFFERENTIAL COVERS is the routing block, 0x82229310..0x8222946C,
entered at whichever of its two heads the case selects.  It stops before
0x82229470, which is a separate behaviour -- the layout-1 response curve
`sign(x) * (1 - cos(|x| * pi/2))` on +2104/+2108, snapped to sign(x) past 0.9.
`steps` is computed per case by simulating the block's control flow, and the
`exit == step_limit` assertion is what makes a miscount visible.

THE ENTITY SITS AT 0xB8000000 ON PURPOSE.  The common tail calls 0x82228480
with `r3 = entity` and tests `clrlwi r11,r3,24`; a stub returns without touching
r3, so the low byte of the entity's own address decides the branch.  Zero takes
the path that does NOT suppress +2096, which is the path being measured.

    python3 tools/audit_flight_input_router_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_flight_input_router_microexec.py --check --workdir W
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

ENTITY = 0xB8000000
BINDING = 0xB8100000
LAYOUT = 0x826EDB58

DIGITAL_HEAD = 0x82229310
ANALOG_HEAD = 0x82229370
STOP = 0x82229470

FLAGS_AT = 3652
ARRAY_AT = 3672
FIELDS = (2096, 2100, 2104, 2108, 2112, 2116)

# Which bit of [binding+3652] feeds which field, PER ARM.  These are not one
# table: the first draft assumed the digital pair always took bits 2 and 3 and
# the differential rejected three values for it.  Layout 1 transposes BOTH pairs
# and swaps each -- the analog pair 3680/3684 lands on +2096/+2100 reversed, and
# bits 5/4 land on +2112/+2116 reversed.
DIGITAL_BITS_DEVICE = {2112: 2, 2116: 3}
DIGITAL_BITS_LAYOUT0 = {2096: 4, 2100: 5}
DIGITAL_BITS_LAYOUT1 = {2112: 5, 2116: 4}

# the six binding-layer outputs, deliberately unequal and fully mantissa'd so a
# port that crossed two of them cannot pass
ARRAY = [0.125, -0.375, 0.6171875, -0.8203125, 0.37777779, -0.94999999]

CASES = [
    ("digital-clear", 0, 0x00000000, "device mode 0, no buttons: the axis pair is 0.0"),
    ("digital-both", 0, 0x0000000C, "device mode 0, bits 2 and 3: both halves at 1.0"),
    ("digital-bit2", 0, 0x00000004, "bit 2 alone -- +2112 only"),
    ("digital-bit3", 0, 0x00000008, "bit 3 alone -- +2116 only"),
    ("analog-a-clear", 0, 0x00000000, "layout 0: array[2],array[3] to the axis pair"),
    ("analog-a-holds", 0, 0x00000030, "layout 0: bits 4 and 5 drive the holds"),
    ("analog-a-bit4", 0, 0x00000010, "bit 4 alone -- +2096 only"),
    ("analog-a-bit5", 0, 0x00000020, "bit 5 alone -- +2100 only"),
    ("analog-b-clear", 1, 0x00000000, "layout 1: array[3],array[2] to the holds, SWAPPED"),
    ("analog-b-axes", 1, 0x00000030, "layout 1: bits 5 and 4 drive the axis pair"),
    ("analog-b-bit5", 1, 0x00000020, "layout 1, bit 5 alone -- +2112, not +2100"),
    ("analog-b-bits23", 1, 0x0000000C, "layout 1: bits 2 and 3 must NOT show"),
    ("analog-b-noise", 1, 0xFFFFFFC3, "every OTHER bit set: none of them may show"),
]

SPEC = """\
# Generated by tools/audit_flight_input_router_microexec.py --emit.
# {why}
#
# Entered at {head:#010x}, the head of the {which} arm.  Nothing is stubbed but
# 0x82228480, whose result is decided by the entity's own low address byte.

function {head:#010x}
case router:{name}

region entity  {entity:#010x} bytes:{entity_bytes}
region binding {binding:#010x} bytes:{binding_bytes}
region layout  {layout:#010x} bytes:{layout_bytes}
region stack   0xC0000000 zero:0x2000

sp 0xC0001000
gpr r31 entity
gpr r28 binding
gpr r30 layout
gpr r0 0
fpr f28 f:0.0
steps {steps}
stub 0x82228480 the +2096 suppression predicate
dump entity
"""


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def load_listing() -> dict[int, tuple[str, str]]:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import map_object_layout as mol  # noqa: E402

    corpus = mol.load_corpus("/fastdata/lavaulta/auto-re-agent/.tools/recomp-eval/ac6/output")
    return {addr: (mn, op) for addr, mn, op in corpus[0x82229250]}


def simulate(listing: dict[int, tuple[str, str]], head: int, flags: int, layout: int) -> int:
    """Count the steps from `head` to STOP, following the block's real branches.

    Only the forms this block uses are modelled; anything else is a fall-through
    of one step.  An unmodelled branch would run off the end and raise, which is
    the behaviour worth having -- a silent guess is what `exit == step_limit`
    exists to catch, and this refuses to make one.
    """
    pc, steps, r11 = head, 0, 0
    while pc != STOP:
        if steps > 200:
            raise RuntimeError(f"runaway at {pc:#010x}")
        mn, op = listing[pc]
        steps += 1
        if mn == "lwz" and op == f"r11,{FLAGS_AT}(r28)":
            r11 = flags
        elif mn == "lwz" and op == "r11,4(r30)":
            r11 = layout
        elif mn == "rlwinm" and op.startswith("r11,r11,0,"):
            mb = int(op.rsplit(",", 2)[1])
            r11 &= 1 << (31 - mb)
        elif mn == "cmplwi":
            r11_cmp = int(op.rsplit(",", 1)[1])
            eq = (r11 == r11_cmp)
        elif mn in ("beq", "bne"):
            target = int(op.rsplit(",", 1)[1], 16)
            if (mn == "beq") == eq:
                pc = target
                continue
        elif mn == "b":
            pc = int(op, 16)
            continue
        elif mn == "bl":
            steps += 1  # the stub is its own step
        pc += 4
    return steps


def expected(flags: int, layout: int, digital_device: bool) -> dict[int, float]:
    """What the six fields must hold, derived from the listing, not the port."""
    out: dict[int, float] = {}
    bit = lambda n: 1.0 if flags & (1 << n) else 0.0  # noqa: E731
    out[2104] = f32(ARRAY[0])
    out[2108] = f32(ARRAY[1])
    if digital_device:
        out[2112] = bit(DIGITAL_BITS_DEVICE[2112])
        out[2116] = bit(DIGITAL_BITS_DEVICE[2116])
        out[2096] = f32(ARRAY[4])
        out[2100] = f32(ARRAY[5])
    elif layout == 1:
        out[2096] = f32(ARRAY[3])
        out[2100] = f32(ARRAY[2])
        out[2112] = bit(DIGITAL_BITS_LAYOUT1[2112])
        out[2116] = bit(DIGITAL_BITS_LAYOUT1[2116])
    else:
        out[2112] = f32(ARRAY[2])
        out[2116] = f32(ARRAY[3])
        out[2096] = bit(DIGITAL_BITS_LAYOUT0[2096])
        out[2100] = bit(DIGITAL_BITS_LAYOUT0[2100])
    return out


def emit(workdir: Path) -> int:
    listing = load_listing()
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for name, layout, flags, why in CASES:
        digital = name.startswith("digital")
        head = DIGITAL_HEAD if digital else ANALOG_HEAD

        entity = bytearray(0x2A00)
        for field in FIELDS:  # poison: every field must be written
            struct.pack_into(">f", entity, field, f32(-777.0))
        binding = bytearray(0xE80)
        struct.pack_into(">I", binding, FLAGS_AT, flags & 0xFFFFFFFF)
        for index, value in enumerate(ARRAY):
            struct.pack_into(">f", binding, ARRAY_AT + 4 * index, f32(value))
        layout_bytes = bytearray(0x10)
        struct.pack_into(">I", layout_bytes, 4, layout)

        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(SPEC.format(
            why=why, name=name, head=head,
            which="digital-device" if digital else "analog-device",
            entity=ENTITY, entity_bytes=entity.hex(),
            binding=BINDING, binding_bytes=binding.hex(),
            layout=LAYOUT, layout_bytes=layout_bytes.hex(),
            steps=simulate(listing, head, flags, layout),
        ), encoding="utf-8")
        manifest.append(f"{spec.resolve()} {(workdir / 'out' / (name + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures, compared, lines = 0, 0, []
    for name, layout, flags, why in CASES:
        path = workdir / "out" / f"{name}.json"
        if not path.exists():
            print(f"MISSING {path}")
            failures += 1
            continue
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        exit_kind = (snapshot.get("exit") or {}).get("kind")
        if exit_kind != "step_limit":
            print(f"FAIL {name}: exit={snapshot.get('exit')!r}")
            failures += 1
            continue
        dumps = {d["name"]: d["after_hex"] for d in snapshot["region_dumps"]}
        blob = bytes.fromhex(dumps["entity"])
        want = expected(flags, layout, name.startswith("digital"))
        for field in FIELDS:
            got = struct.unpack_from(">f", blob, field)[0]
            compared += 1
            mark = "ok"
            if got != want[field]:
                mark, failures = "FAIL", failures + 1
            lines.append(f"{name}\t+{field}\t{got!r}\t{want[field]!r}\t{mark}")
            if mark == "FAIL":
                print(f"FAIL {name} +{field}: retail={got!r} port={want[field]!r}")
    print(f"cases={len(CASES)} values={compared} failures={failures}")
    if report:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text("case\tfield\tretail\tport\tverdict\n" + "\n".join(lines) + "\n",
                          encoding="utf-8")
        print(f"wrote {report}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    if args.emit:
        return emit(args.workdir)
    if args.check:
        return check(args.workdir, args.report)
    parser.error("one of --emit or --check")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
