#!/usr/bin/env python3
"""Identify 0x82381068, then run the layout-1 axis response curve against the port.

Cycle 1409 ported the routing block of 0x82229250 and left the tail at
0x82229470 out of it, named but unread: on layout 1 it rewrites +2104 and +2108
before anything downstream sees them.  This is that tail.

TWO QUESTIONS, AND THE FIRST HAS TO GO FIRST.  The tail calls 0x82381068 with
|x| * (pi/2) and subtracts the result from 1.0.  It LOOKS like cosine and the
port would be plausible and wrong if it were sine -- so 0x82381068 is identified
by RUNNING it, at angles chosen where cos and sin disagree, and comparing both.
It is a 54-instruction leaf: argument reduction by fctid, a quadrant parity in
`clrldi r10,r10,63`, and a minimax polynomial.  Nothing about that shape says
which of the two it is.

The `identify` cases capture f1 on return.  The `curve` cases enter at
0x82229470 with the callee LIVE -- nothing is stubbed, so the comparison covers
the polynomial as well as the arithmetic around it.

WHICH IS WHY THIS RUNS IN TWO PASSES.  The block is 33 straight-line
instructions, but the callee's length DEPENDS ON ITS ARGUMENT: the identify runs
came back at 47, 51 and 52 steps for different angles.  A guessed budget ran 190
steps into the rest of the function and exited on a fault, and a fault-exit dump
is not an assertion about where execution stopped.  So pass 1 measures the
callee at each of the sixteen arguments these cases actually use, and pass 2
sets `steps = 33 + cost_a + cost_b` exactly, which puts `exit == step_limit`
one instruction past the second store.

WHAT THE TAIL DOES, read at 0x82229470..0x822294F0:

    t = 1.0 - float32(cos_or_sin(|x| * pi/2))     f29 is 1.0 on every arm
    if (t > 0.9) t = 1.0                          fcmpu then ble; 0x820078C0
    x' = fsel(x, t, -t)                           so -0.0 takes +t

computed for +2104 first and +2108 second, both stored after both are computed.

    python3 tools/audit_flight_axis_curve_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_flight_axis_curve_microexec.py --check --workdir W
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path

ENTITY = 0xB8000000
LAYOUT = 0x826EDB58
CURVE_HEAD = 0x82229470
CURVE_STOP = 0x822294F4
LIBM = 0x82381068

HALF_PI = 1.5707963705062866   # 0x82069E48, float32
SNAP_ABOVE = 0.8999999761581421  # 0x820078C0, float32

# Angles where cos and sin are far apart, so one run settles which this is.
IDENTIFY = [0.0, 0.25, 0.5, 1.0, HALF_PI, 2.0, 3.0]

# THE SEAM.  The port calls std::cos and retail calls its own polynomial, and
# they are NOT the same function -- the identify runs agree bit-for-bit in the
# double at only 3 of 7 angles.  What saves the port is `frsp`: the block rounds
# the result to float32 before using it, and a one-ulp double difference almost
# always vanishes there.  "Almost always" is not a verification, so this sweeps
# the whole domain the curve can reach -- |x| in [0, 1] maps to [0, pi/2] -- and
# the checker reports how many of them survive the rounding.  A single survivor
# is a real defect in the port and this is what would find it.
SEAM_POINTS = 96

# (+2104, +2108). Chosen so the snap fires on some and not others, and so the
# sign path is exercised in both directions including negative zero.
CURVE_CASES = [
    ("zero", 0.0, 0.0),
    ("negzero", -0.0, 0.0),
    ("small", 0.125, -0.125),
    ("mid", 0.5, -0.5),
    ("just-under-snap", 0.75, -0.75),
    ("over-snap", 0.95, -0.95),
    ("full", 1.0, -1.0),
    ("mantissas", 0.37777779, -0.94999999),
]

BLOCK_INSNS = 33  # 0x82229470..0x822294F0 inclusive

IDENTIFY_SPEC = """\
# Generated by tools/audit_flight_axis_curve_microexec.py --emit.
# 0x82381068 at {angle!r}: cos and sin disagree here, so the run names it.

function {libm:#010x}
case libm:{name}

region stack 0xC0000000 zero:0x2000
sp 0xC0001000
gpr r0 0
fpr f1 f:{angle!r}
steps 200
capture fpr:f1
"""

CURVE_SPEC = """\
# Generated by tools/audit_flight_axis_curve_microexec.py --emit.
# The layout-1 response curve on +2104={a!r} and +2108={b!r}.
#
# 0x82381068 runs LIVE.  f28 and f29 are the 0.0 and 1.0 every arm of
# 0x82229250 loads before reaching here, which a mid-function entry skips.

function {head:#010x}
case curve:{name}

region entity {entity:#010x} bytes:{entity_bytes}
region layout {layout:#010x} bytes:{layout_bytes}
region stack  0xC0000000 zero:0x2000

sp 0xC0001000
gpr r31 entity
gpr r30 layout
gpr r0 0
fpr f28 f:0.0
fpr f29 f:1.0
steps {steps}
dump entity
"""


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def load_listing() -> dict[int, tuple[str, str]]:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import map_object_layout as mol  # noqa: E402

    corpus = mol.load_corpus("/fastdata/lavaulta/auto-re-agent/.tools/recomp-eval/ac6/output")
    return {addr: (mn, op) for addr, mn, op in corpus[0x82229250]}


def block_insns(listing: dict[int, tuple[str, str]]) -> int:
    """The straight-line length of 0x82229470..0x822294F0, counted not assumed."""
    steps, pc = 0, CURVE_HEAD
    while pc != CURVE_STOP:
        listing[pc]  # KeyError if the block is not contiguous
        steps += 1
        pc += 4
    return steps


def curve_arguments(a: float, b: float) -> tuple[float, float]:
    """The two angles the block hands to 0x82381068, in its own rounding."""
    return f32(f32(abs(a)) * HALF_PI), f32(f32(abs(b)) * HALF_PI)


def curve_expected(value: float, raw: float) -> float:
    """The block's arithmetic AROUND the callee, given the callee's own result.

    `raw` is what 0x82381068 actually returned, measured -- NOT std::cos.  The
    two claims have to be separated: whether the port reproduces this block, and
    whether a native cosine may stand in for retail's.  Feeding std::cos in here
    conflates them, and it conflates them in the direction that passes.
    """
    term = f32(1.0 - f32(raw))
    if term > SNAP_ABOVE:
        term = 1.0
    # fsel(value, term, -term): the test is >= 0, so -0.0 takes term.
    return term if not (value < 0.0) else -term


def measure_name(angle: float) -> str:
    return "measure-" + struct.pack(">d", angle).hex()


def emit(workdir: Path) -> int:
    """Pass 1: identify the callee, and measure its cost at every argument used."""
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []

    angles = []
    for _, a, b in CURVE_CASES:
        angles.extend(curve_arguments(a, b))
    seam = [f32(f32(index / (SEAM_POINTS - 1)) * HALF_PI) for index in range(SEAM_POINTS)]
    for angle in dict.fromkeys(angles + seam):
        name = measure_name(angle)
        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(IDENTIFY_SPEC.format(libm=LIBM, name=name, angle=angle),
                        encoding="utf-8")
        manifest.append(f"{spec.resolve()} {(workdir / 'out' / (name + '.json')).resolve()}")

    for index, angle in enumerate(IDENTIFY):
        name = f"identify-{index}"
        spec = workdir / "specs" / f"{name}.spec"
        spec.write_text(IDENTIFY_SPEC.format(libm=LIBM, name=name, angle=angle),
                        encoding="utf-8")
        manifest.append(f"{spec.resolve()} {(workdir / 'out' / (name + '.json')).resolve()}")

    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted pass=1 cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def emit_curve(workdir: Path) -> int:
    """Pass 2: the block itself, with a step budget taken from pass 1."""
    listing = load_listing()
    block = block_insns(listing)
    if block != BLOCK_INSNS:
        print(f"FAIL block is {block} instructions, not {BLOCK_INSNS}")
        return 1

    def cost(angle: float) -> int:
        path = workdir / "out" / f"{measure_name(angle)}.json"
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        if snapshot["exit"]["kind"] != "return":
            raise RuntimeError(f"{path} exited {snapshot['exit']}")
        return int(snapshot["provenance"]["steps"])

    manifest = []
    for name, a, b in CURVE_CASES:
        entity = bytearray(0x2A00)
        struct.pack_into(">f", entity, 2104, f32(a))
        struct.pack_into(">f", entity, 2108, f32(b))
        layout = bytearray(0x10)
        struct.pack_into(">I", layout, 4, 1)
        angle_a, angle_b = curve_arguments(a, b)
        budget = block + cost(angle_a) + cost(angle_b)
        spec = workdir / "specs" / f"curve-{name}.spec"
        spec.write_text(CURVE_SPEC.format(
            name=name, a=a, b=b, head=CURVE_HEAD,
            entity=ENTITY, entity_bytes=entity.hex(),
            layout=LAYOUT, layout_bytes=layout.hex(), steps=budget), encoding="utf-8")
        manifest.append(
            f"{spec.resolve()} {(workdir / 'out' / ('curve-' + name + '.json')).resolve()}")

    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted pass=2 cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures, compared, lines = 0, 0, []

    # ---- which function is it
    cos_hits = sin_hits = 0
    for index, angle in enumerate(IDENTIFY):
        path = workdir / "out" / f"identify-{index}.json"
        if not path.exists():
            print(f"MISSING {path}")
            failures += 1
            continue
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        raw = snapshot.get("registers", {}).get("f1")
        got = struct.unpack(">d", struct.pack(">Q", int(raw, 16)))[0]
        cos_hits += (got == math.cos(angle))
        sin_hits += (got == math.sin(angle))
        lines.append(f"identify\t{angle!r}\t{got!r}\t{math.cos(angle)!r}\t{math.sin(angle)!r}")
    cosine = cos_hits > sin_hits

    # ---- may std::cos stand in for retail's?  Measured on the BLOCK'S OUTPUT,
    # because that is the quantity anything downstream sees, and because the snap
    # at 0.9 hides most of the disagreement without hiding all of it.
    seam_checked = cos_split = out_split = 0
    survivors = []
    for index in range(SEAM_POINTS):
        angle = f32(f32(index / (SEAM_POINTS - 1)) * HALF_PI)
        path = workdir / "out" / f"{measure_name(angle)}.json"
        if not path.exists():
            continue
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        retail = struct.unpack(">d", struct.pack(">Q", int(snapshot["registers"]["f1"], 16)))[0]
        native = math.cos(angle) if cosine else math.sin(angle)
        seam_checked += 1
        split = f32(retail) != f32(native)
        cos_split += split
        out_r, out_n = curve_expected(1.0, retail), curve_expected(1.0, native)
        if out_r != out_n:
            out_split += 1
            survivors.append((index / (SEAM_POINTS - 1), angle, out_r, out_n))
        lines.append(f"seam\t{angle!r}\t{f32(retail)!r}\t{f32(native)!r}\t"
                     f"{out_r!r}\t{out_n!r}\t"
                     f"{'OUT-SPLIT' if out_r != out_n else ('cos-split' if split else 'same')}")
    print(f"seam: {seam_checked} arguments over [0, pi/2] -- "
          f"{cos_split} split at the cosine, {out_split} SURVIVE the 0.9 snap")
    for x, angle, out_r, out_n in survivors:
        print(f"  x={x:.4f} angle={angle!r}: retail={out_r!r} std::cos={out_n!r}")
    print("VERDICT: std::cos " + ("MAY NOT" if out_split else "may")
          + " stand in for 0x82381068 in this block")
    print(f"0x82381068: cos matches {cos_hits}/{len(IDENTIFY)}, "
          f"sin matches {sin_hits}/{len(IDENTIFY)} -> {'cos' if cosine else 'sin'}")
    if cos_hits == sin_hits:
        print("FAIL identify: the two readings do not separate")
        failures += 1

    # ---- and does the port reproduce the block
    for name, a, b in CURVE_CASES:
        path = workdir / "out" / f"curve-{name}.json"
        if not path.exists():
            print(f"MISSING {path}")
            failures += 1
            continue
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        if snapshot["exit"]["kind"] != "step_limit":
            print(f"FAIL curve-{name}: exit={snapshot['exit']!r}")
            failures += 1
            continue
        dumps = {d["name"]: d["after_hex"] for d in snapshot["region_dumps"]}
        blob = bytes.fromhex(dumps["entity"])
        for field, seed in ((2104, a), (2108, b)):
            got = struct.unpack_from(">f", blob, field)[0]
            angle = curve_arguments(seed, seed)[0]
            measured = json.loads(
                (workdir / "out" / f"{measure_name(angle)}.json").read_text(encoding="utf-8"))
            raw = struct.unpack(">d", struct.pack(">Q",
                                                  int(measured["registers"]["f1"], 16)))[0]
            want = curve_expected(seed, raw)
            compared += 1
            mark = "ok"
            if got != want or math.copysign(1.0, got) != math.copysign(1.0, want):
                mark, failures = "FAIL", failures + 1
                print(f"FAIL curve-{name} +{field}: retail={got!r} port={want!r}")
            lines.append(f"curve-{name}\t+{field}\t{got!r}\t{want!r}\t{mark}")
    print(f"block: cases={len(CURVE_CASES)} values={compared} failures={failures}")
    if report:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text("case\tfield\tretail\tport\tverdict\n" + "\n".join(lines) + "\n",
                          encoding="utf-8")
        print(f"wrote {report}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--emit-curve", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    if args.emit:
        return emit(args.workdir)
    if args.emit_curve:
        return emit_curve(args.workdir)
    if args.check:
        return check(args.workdir, args.report)
    parser.error("one of --emit, --emit-curve or --check")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
