#!/usr/bin/env python3
"""Run the retail input stages and compare them against the native port.

`include/ac6/retail_input.h` derives `split_axis` and `button_edges` by reading
0x8234D110 and 0x8234D378. Derived and tested is not the same as verified: the
tests check the port against the rules I wrote down, and if I read the branch
wrongly both would agree and both would be wrong.

This closes that. Each case executes the **retail instructions** on a synthetic
device through scripts/MicroExecuteFunction.java and compares every byte they
write against what the port says they should write. Both stages are scalar and
stay inside one register family, which cycle 1306 named as exactly what the
micro-execution instrument can certify.

The device is split into three regions so the same object can be both pre-filled
and write-detected: the output block is poison, the XINPUT_STATE is a literal,
and the tail is zeroed.

    python3 tools/audit_retail_input_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_retail_input_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

DEVICE = 0xB4000000
STATE = 0x44          # XINPUT_STATE inside the device, cycle 1307
OUTPUT_BYTES = 0x44   # +0x00..+0x43, everything 0x8234D0A0 later copies

AXIS_STAGE = 0x8234D110
BUTTON_STAGE = 0x8234D378
# 0x8234D378 calls these two; neither is read, so neither is executed.
BUTTON_STUBS = (0x8234D1B8, 0x8234D210)

# source, positive, negative -- the table at 0x8201250C, as the port carries it.
AXIS_TABLE = ((0x3C, 0x2E, 0x2C), (0x3E, 0x28, 0x2A),
              (0x40, 0x36, 0x34), (0x42, 0x30, 0x32))

# (LX, LY, RX, RY) per case: zero, the extremes, and the boundaries where a
# misread branch and the right one disagree.
AXIS_CASES = [
    (0, 0, 0, 0),
    (1, -1, 0, 0),
    (32767, -32768, -32768, 32767),
    (-1, 1, 12345, -12345),
    (256, -256, 1, -1),
    (-32768, 32767, 0, -1),
]

# (previous mask, current buttons)
BUTTON_CASES = [
    (0x0000, 0x0000),
    (0x0000, 0x8000),
    (0x0001, 0x0011),
    (0x0011, 0x0010),
    (0xFFFF, 0xFFFF),
    (0xA5A5, 0x5A5A),
]


def split_axis(raw: int) -> tuple[int, int]:
    """The port's rule, restated here so the two sides are independent code."""
    return (raw, 0) if raw >= 0 else (0, -1 - raw)


def button_edges(previous: int, buttons: int) -> dict[int, int]:
    current = buttons & 0xFFFF
    changed = (previous ^ current) & 0xFFFFFFFF
    return {
        0x14: changed & current,
        0x18: changed & (~current & 0xFFFFFFFF),
        0x1C: current,
        0x20: (~current) & 0xFFFFFFFF,
    }


def state_bytes(lx: int, ly: int, rx: int, ry: int, buttons: int = 0) -> str:
    """XINPUT_STATE: packet, buttons, two triggers, four thumbs, big-endian."""
    blob = struct.pack(">IHBB hhhh", 0, buttons, 0, 0, lx, ly, rx, ry)
    return blob.hex()


SPEC = """\
# Generated by tools/audit_retail_input_microexec.py --emit.
# {title}

function {function:#010x}
case retail-input:{name}

region out    {device:#010x} poison:{output:#x}
region state  {state_base:#010x} bytes:{state}
region tail   {tail_base:#010x} zero:0x34
region stack  0xC0000000 zero:0x1000

sp 0xC0000E00
gpr r3 out
gpr r0 0
"""


def cases() -> list[dict]:
    built = []
    for index, (lx, ly, rx, ry) in enumerate(AXIS_CASES):
        built.append({
            "name": f"axis-{index}",
            "title": f"0x8234D110 on LX={lx} LY={ly} RX={rx} RY={ry}",
            "function": AXIS_STAGE,
            "state": state_bytes(lx, ly, rx, ry),
            "expect": axis_expectation(lx, ly, rx, ry),
        })
    for index, (previous, buttons) in enumerate(BUTTON_CASES):
        built.append({
            "name": f"button-{index}",
            "title": f"0x8234D378 on prev={previous:#06x} buttons={buttons:#06x}",
            "function": BUTTON_STAGE,
            "state": state_bytes(0, 0, 0, 0, buttons),
            "previous": previous,
            "stubs": BUTTON_STUBS,
            # The button stage calls the axis stage first, so a zeroed stick
            # writes its splits too; both are expected.
            "expect": {**button_edges(previous, buttons),
                       **axis_expectation(0, 0, 0, 0)},
        })
    return built


def axis_expectation(lx: int, ly: int, rx: int, ry: int) -> dict[int, int]:
    """Halfword writes, keyed by device offset."""
    expected: dict[int, int] = {}
    for (source, positive, negative), raw in zip(AXIS_TABLE, (lx, ly, rx, ry)):
        expected[source] = raw & 0xFFFF          # the verbatim copy
        pos, neg = split_axis(raw)
        expected[positive] = pos & 0xFFFF
        expected[negative] = neg & 0xFFFF
    return expected


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for case in cases():
        lines = [SPEC.format(title=case["title"], function=case["function"],
                             name=case["name"], device=DEVICE, output=OUTPUT_BYTES,
                             state_base=DEVICE + STATE, state=case["state"],
                             tail_base=DEVICE + STATE + 0x10)]
        if "previous" in case:
            # device+0x74 is the previous mask; it lives in the zeroed tail, so
            # a non-zero one is seeded through a second literal region.
            lines.append(f"region prev {DEVICE + 0x74:#010x} "
                         f"bytes:{case['previous']:08x}")
        for stub in case.get("stubs", ()):
            lines.append(f"stub {stub:#010x} not read, not executed")
        spec = workdir / "specs" / f"{case['name']}.spec"
        spec.write_text("\n".join(lines) + "\n", encoding="utf-8")
        manifest.append(f"{spec.resolve()} "
                        f"{(workdir / 'out' / (case['name'] + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def written_bytes(document: dict) -> dict[int, int]:
    """Every byte the run wrote, keyed by device offset."""
    out: dict[int, int] = {}
    for run in document.get("memory_writes", []):
        address = int(run["address"], 16)
        payload = bytes.fromhex(run["after_hex"])
        for index, value in enumerate(payload):
            offset = address + index - DEVICE
            if 0 <= offset < OUTPUT_BYTES:
                out[offset] = value
    return out


def check(workdir: Path, report: Path | None) -> int:
    passed, failures, compared = 0, [], 0
    for case in cases():
        path = workdir / "out" / f"{case['name']}.json"
        if not path.exists():
            failures.append(f"{case['name']}: no snapshot")
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        if document["exit"]["kind"] != "return":
            failures.append(f"{case['name']}: exit {document['exit']}")
            continue
        actual = written_bytes(document)
        bad = []
        for offset, value in sorted(case["expect"].items()):
            width = 4 if offset in (0x14, 0x18, 0x1C, 0x20) else 2
            got = 0
            for byte in range(width):
                if offset + byte not in actual:
                    bad.append(f"+0x{offset:02X} not written")
                    break
                got = (got << 8) | actual[offset + byte]
            else:
                compared += 1
                if got != value:
                    bad.append(f"+0x{offset:02X} retail=0x{got:X} port=0x{value:X}")
        if bad:
            failures.append(f"{case['name']}: " + "; ".join(bad))
        else:
            passed += 1

    print(f"cases={len(cases())} passed={passed} failures={len(failures)} "
          f"fields_compared={compared}")
    for failure in failures:
        print(f"  {failure}", file=sys.stderr)
    if report is not None and not failures:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(json.dumps({
            "schema": "ac6.retail-input-microexec.v1",
            "statement": "the retail input stages executed on a synthetic device "
                         "write what include/ac6/retail_input.h says they write",
            "axis_stage": f"0x{AXIS_STAGE:08X}",
            "button_stage": f"0x{BUTTON_STAGE:08X}",
            "cases": len(cases()),
            "passed": passed,
            "fields_compared": compared,
            "stubbed": [f"0x{stub:08X}" for stub in BUTTON_STUBS],
        }, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {report}")
    if failures:
        print("retail_input_microexec=fail", file=sys.stderr)
        return 1
    print("retail_input_microexec=pass")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return emit(arguments.workdir) if arguments.emit else check(arguments.workdir,
                                                               arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
