#!/usr/bin/env python3
"""Run the blended control accessors and compare them against the port.

0x82281E10 and 0x82281EA8 are slots 17 and 18 of the flight-model base vtable,
inherited unchanged by BOTH concrete branches -- so unlike almost everything else
in this thread, one port covers both, and this audit runs both functions against
the same implementation with different fields and a different constant.

Each is 38 instructions, no call and no vector. Two things are compared: the
value returned in f1, captured, and the field the reset path stores, dumped.
Both matter, and they are not the same value -- the store happens BEFORE the
[-1, +1] clamp, so a case whose result clamps leaves an unclamped number in
memory. `slot17-reset-mantissas` is that case: it returns 1.0 and stores
1.0822536945343018.

    python3 tools/audit_control_blend_microexec.py --emit --workdir W
    <analyzeHeadless ... -postScript MicroExecuteFunction.java --batch W/manifest>
    python3 tools/audit_control_blend_microexec.py --check --workdir W [--report R]
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

EPSILON = 1.52587890625e-05
RESET_BIT = 2
# name -> (function, axis, rate, stored, scale)
SLOTS = {
    "slot17": (0x82281E10, 304, 144, 408, 0.6366198062896729),
    "slot18": (0x82281EA8, 312, 152, 412, 0.3183099031448364),
}
# (name, flags, axis, rate, stored, why)
CASES = [
    ("idle", 0, 0.0, 0.0, 0.0, "everything zero"),
    ("add-stored", 0, 0.25, 9.0, 0.5, "off the bit the stored value is added"),
    ("sub-epsilon", 0, 0.25, 9.0, 7.62939453125e-06,
     "a stored value below 2^-16 contributes nothing"),
    ("reset-rate-wins", RESET_BIT, 0.1, 1.0, 0.0,
     "on the bit a larger scaled rate replaces the axis"),
    ("reset-axis-wins", RESET_BIT, 0.9, 0.1, 0.0, "a smaller one does not"),
    ("clamp-high", 0, 0.9, 0.0, 0.9, "the sum clamps at +1"),
    ("clamp-low", 0, -0.9, 0.0, -0.9, "and at -1"),
    ("mantissas", 0, 0.37777779, 1.7000001, 0.13333334, "full mantissas"),
    ("reset-mantissas", RESET_BIT, 0.37777779, 1.7000001, 0.13333334,
     "the STORE precedes the clamp: this returns 1.0 and stores 1.08"),
]

SPEC = """\
# Generated by tools/audit_control_blend_microexec.py --emit.
# {why}

function {fn:#010x}
case blend:{name}

region model 0xb8000000 bytes:{model_bytes}
region stack 0xC0000000 zero:0x2000

sp 0xC0001000
gpr r3 model
gpr r0 0
capture fpr:f1
dump model
"""


def f32(value: float) -> float:
    return struct.unpack(">f", struct.pack(">f", value))[0]


def port(axis, rate, stored, flags, scale):
    axis, rate, stored, scale = (f32(v) for v in (axis, rate, stored, scale))
    value, kept = axis, stored
    if flags & RESET_BIT:
        scaled = f32(rate * scale)
        if abs(scaled) > abs(value):
            value = scaled
        kept = value
    elif not (abs(stored) < EPSILON):
        value = f32(stored + value)
    if value < -1.0:
        value = -1.0
    elif value > 1.0:
        value = 1.0
    return value, kept


def emit(workdir: Path) -> int:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "specs").mkdir(exist_ok=True)
    (workdir / "out").mkdir(exist_ok=True)
    manifest = []
    for slot, (fn, axo, rato, sto, _) in SLOTS.items():
        for name, flags, axis, rate, stored, why in CASES:
            blob = bytearray(0x600)
            struct.pack_into(">I", blob, 332, flags)
            struct.pack_into(">f", blob, axo, f32(axis))
            struct.pack_into(">f", blob, rato, f32(rate))
            struct.pack_into(">f", blob, sto, f32(stored))
            full = f"{slot}-{name}"
            spec = workdir / "specs" / f"{full}.spec"
            spec.write_text(SPEC.format(why=f"{slot}: {why}", fn=fn, name=full,
                                        model_bytes=blob.hex()), encoding="utf-8")
            manifest.append(f"{spec.resolve()} "
                            f"{(workdir / 'out' / (full + '.json')).resolve()}")
    (workdir / "manifest").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"emitted cases={len(manifest)} manifest={workdir / 'manifest'}")
    return 0


def check(workdir: Path, report: Path | None) -> int:
    failures, compared, lines = [], 0, []
    for slot, (fn, axo, rato, sto, scale) in SLOTS.items():
        for name, flags, axis, rate, stored, why in CASES:
            full = f"{slot}-{name}"
            path = workdir / "out" / f"{full}.json"
            if not path.exists():
                failures.append(f"{full}: no snapshot")
                continue
            document = json.loads(path.read_text(encoding="utf-8"))
            if document["exit"]["kind"] != "return":
                failures.append(f"{full}: exit {document['exit']}")
                continue
            raw = document["registers"]["f1"]
            got = f32(struct.unpack(">d", struct.pack(">Q", int(raw, 16)))[0])
            dump = next(e for e in document["region_dumps"] if e["name"] == "model")
            after = bytes.fromhex(dump["after_hex"])
            got_stored = struct.unpack_from(">f", after, sto)[0]
            want, want_stored = port(axis, rate, stored, flags, scale)
            compared += 2
            bad = []
            if struct.pack(">f", got) != struct.pack(">f", want):
                bad.append(f"f1: retail {got!r} port {want!r}")
            if struct.pack(">f", got_stored) != struct.pack(">f", want_stored):
                bad.append(f"+{sto}: retail {got_stored!r} port {want_stored!r}")
            if bad:
                failures.append(f"{full}: " + "; ".join(bad))
            lines.append(f"{full}\t{'ok' if not bad else 'MISMATCH'}\t{got!r}\t"
                         f"{got_stored!r}\t{why}")
    if report is not None:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(
            "# 0x82281E10 and 0x82281EA8, slots 17 and 18, micro-executed against\n"
            "# ac6::retail::blend_control_axis. Both the returned value and the\n"
            "# stored field are compared, and they differ when the clamp fires.\n"
            "# case\tverdict\tf1\tstored\twhy the case exists\n"
            + "\n".join(lines) + "\n", encoding="utf-8")
    for problem in failures:
        print("  FAIL  " + problem)
    print(f"control_blend_microexec={'pass' if not failures else 'fail'} "
          f"cases={len(lines)} values_compared={compared}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workdir", required=True, type=Path)
    parser.add_argument("--report", type=Path)
    arguments = parser.parse_args()
    if arguments.emit == arguments.check:
        print("choose exactly one of --emit and --check")
        return 2
    return emit(arguments.workdir) if arguments.emit else check(
        arguments.workdir, arguments.report)


if __name__ == "__main__":
    raise SystemExit(main())
