// Native consumption of the Mission 01 retail manifests.
//
// The manifests are generated by tools/emit_mission01_retail_manifests.py from
// the retail scenario payload. This test loads them through the same product
// code a mission uses, publishes every record into the unit registry and the
// combat world, and asserts the invariants the static analysis established:
//
//   - 230 unit records, the count byte of the parsed 'Obj & Unit' slot;
//   - faction indices 0, 1 and 2 with 140, 42 and 48 records, the distribution
//     of the byte 0x820A7070 uses to index the mission faction table;
//   - object classes 1, 3 and 4 only, the classes 0x820A7F48 allocates for the
//     class bytes present in this payload;
//   - 4 sub-missions, the count byte the mission manager bounds context+0x10
//     against, all Manual and none completed by loading or ticking.
//
// The manifest directory is passed as argv[1] so the test reads the committed
// files rather than a fixture written by the test itself.

#include "test_fixtures.h"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>

namespace {

std::string read_file(const std::filesystem::path& path) {
  std::ifstream input(path, std::ios::binary);
  std::ostringstream buffer;
  buffer << input.rdbuf();
  return buffer.str();
}

constexpr std::uint32_t kMissionId = 1;
constexpr std::size_t kUnitRecords = 230;
constexpr std::size_t kSubMissions = 4;
constexpr std::uint32_t kEntityBase = 4097;

std::map<std::uint32_t, std::size_t> faction_histogram(
    const ac6::MissionWaveSnapshot& snapshot) {
  std::map<std::uint32_t, std::size_t> counts;
  for (const ac6::MissionWaveEntrySnapshot& entry : snapshot.entries) {
    counts[entry.spawn.combat.faction] += 1;
  }
  return counts;
}

std::map<std::uint32_t, std::size_t> asset_histogram(
    const ac6::MissionWaveSnapshot& snapshot) {
  std::map<std::uint32_t, std::size_t> counts;
  for (const ac6::MissionWaveEntrySnapshot& entry : snapshot.entries) {
    counts[entry.spawn.unit.asset] += 1;
  }
  return counts;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 2) {
    std::fprintf(stderr, "usage: %s MANIFEST_DIR\n", argv[0]);
    return 2;
  }
  const std::filesystem::path root(argv[1]);

  ac6::MissionWaveDirector waves;
  REQUIRE(waves.load_manifest(root / "waves.tsv"));

  const ac6::MissionWaveSnapshot loaded = waves.snapshot();
  REQUIRE(loaded.entries.size() == kUnitRecords);
  REQUIRE(waves.pending(kMissionId) == kUnitRecords);
  REQUIRE(waves.spawned(kMissionId) == 0);

  // The faction byte the retail consumer reads, offset by one because the
  // native runtime rejects a zero faction.
  const std::map<std::uint32_t, std::size_t> factions = faction_histogram(loaded);
  REQUIRE(factions.size() == 3);
  REQUIRE(factions.at(1) == 140);
  REQUIRE(factions.at(2) == 42);
  REQUIRE(factions.at(3) == 48);

  // The object classes 0x820A7F48 allocates for this payload's class bytes.
  const std::map<std::uint32_t, std::size_t> assets = asset_histogram(loaded);
  REQUIRE(assets.size() == 3);
  REQUIRE(assets.at(1) == 1);
  REQUIRE(assets.at(3) == 1);
  REQUIRE(assets.at(4) == 228);

  // Every record is published in one pass, as retail builds them.
  ac6::UnitRegistry units;
  ac6::CombatWorld combat;
  REQUIRE(waves.spawn_due(kMissionId, 1, units, combat));
  REQUIRE(waves.pending(kMissionId) == 0);
  REQUIRE(waves.spawned(kMissionId) == kUnitRecords);

  std::size_t active = 0;
  for (std::size_t index = 0; index < kUnitRecords; ++index) {
    const ac6::CombatUnitState* unit =
        combat.unit(static_cast<ac6::EntityId>(kEntityBase + index));
    REQUIRE(unit != nullptr);
    REQUIRE(unit->active);
    REQUIRE(unit->faction >= 1 && unit->faction <= 3);
    active += 1;
  }
  REQUIRE(active == kUnitRecords);

  // Ticking the combat world must not destroy or deactivate a record: nothing
  // in the retail data asks for that.
  combat.tick(1.0f);
  REQUIRE(combat.unit(kEntityBase) != nullptr && combat.unit(kEntityBase)->active);
  REQUIRE(combat.unit(static_cast<ac6::EntityId>(kEntityBase + kUnitRecords - 1)) != nullptr);

  ac6::MissionObjectiveDatabase objectives;
  REQUIRE(objectives.load_manifest(root / "objectives.tsv"));
  const std::vector<const ac6::ObjectiveRecord*> mission_objectives =
      objectives.find_by_mission(kMissionId);
  REQUIRE(mission_objectives.size() == kSubMissions);
  for (const ac6::ObjectiveRecord* objective : mission_objectives) {
    REQUIRE(objective != nullptr);
    REQUIRE(objective->required);
    REQUIRE(objective->condition == ac6::ObjectiveCondition::Manual);
    REQUIRE(objective->state == ac6::ObjectiveState::Pending);
  }

  // A manifest that claims a record the payload does not have must be rejected
  // whole, leaving the loaded state untouched.
  ac6::MissionWaveDirector rejected;
  REQUIRE(!rejected.load_manifest(root / "waves-does-not-exist.tsv"));
  REQUIRE(rejected.pending(kMissionId) == 0);

  if (argc >= 3) {
    std::ofstream report(argv[2]);
    REQUIRE(static_cast<bool>(report));
    report << "{\n"
           << "  \"schema\": \"ac6.mission01-retail-scenario-test.v1\",\n"
           << "  \"mission_id\": " << kMissionId << ",\n"
           << "  \"waves_manifest_fnv64\": \"" << std::hex
           << ::ac6_test::fnv64(read_file(root / "waves.tsv")) << std::dec << "\",\n"
           << "  \"objectives_manifest_fnv64\": \"" << std::hex
           << ::ac6_test::fnv64(read_file(root / "objectives.tsv")) << std::dec << "\",\n"
           << "  \"unit_records_loaded\": " << loaded.entries.size() << ",\n"
           << "  \"unit_records_published\": " << waves.spawned(kMissionId) << ",\n"
           << "  \"faction_1\": " << factions.at(1) << ",\n"
           << "  \"faction_2\": " << factions.at(2) << ",\n"
           << "  \"faction_3\": " << factions.at(3) << ",\n"
           << "  \"object_class_1\": " << assets.at(1) << ",\n"
           << "  \"object_class_3\": " << assets.at(3) << ",\n"
           << "  \"object_class_4\": " << assets.at(4) << ",\n"
           << "  \"sub_missions\": " << mission_objectives.size() << ",\n"
           << "  \"objectives_completed\": 0,\n"
           << "  \"missing_manifest_rejected\": true\n"
           << "}\n";
    REQUIRE(static_cast<bool>(report));
  }

  return 0;
}
