# Generated by tools/audit_vmx128_behaviours.py --emit.
# One retail instruction, every input seeded, the output captured.
# Expected: 0x001122330f0e0d0c445566770b0a0908

function 0x820998e8
case vmx128:vmrghw
steps 1

region fixture 0xb6000000 bytes:000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
region stack   0xC0000000 zero:0x1000
sp 0xC0000E00

vmx on

vec vs42 00112233445566778899aabbccddeeff
vec vs40 0f0e0d0c0b0a09080706050403020100
capture vec:vs38
