# Generated by tools/audit_vmx128_behaviours.py --emit.
# One retail instruction, every input seeded, the output captured.
# Expected: 0x8899aabb07060504ccddeeff03020100

function 0x820998fc
case vmx128:vmrglw
steps 1

region fixture 0xb6000000 bytes:000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
region target  0xb7000000 poison:0x40
region stack   0xC0000000 zero:0x1000
sp 0xC0000E00

vmx on

vec vs38 00112233445566778899aabbccddeeff
vec vs37 0f0e0d0c0b0a09080706050403020100
capture vec:vs42
