# Generated by tools/audit_vmx128_behaviours.py --emit.
# One retail instruction, every input seeded, the output captured.
# Expected: 0x43960000439600004396000043960000

function 0x820a9be8
case vmx128:vmsum4fp128
steps 1

region fixture 0xb6000000 bytes:000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
region stack   0xC0000000 zero:0x1000
sp 0xC0000E00

vmx on

vec vr0 3f800000400000004040000040800000
vec vr11 4120000041a0000041f0000042200000
capture vec:vr4
