# Generated by tools/audit_vmx128_behaviours.py --emit.
# One retail instruction, every input seeded, the output captured.
# Expected: 0x070605040f0e0d0c030201000f0e0d0c

function 0x822118e0
case vmx128:vpermwi128-override-8c
steps 1

region fixture 0xb6000000 bytes:000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
region target  0xb7000000 poison:0x40
region stack   0xC0000000 zero:0x1000
sp 0xC0000E00

vmx on

vec vr12 0f0e0d0c0b0a09080706050403020100
vec vr13 0f0e0d0c0b0a09080706050403020100
override 0x822118e0 vpermwi128
capture vec:vr13
